(function(root){
  'use strict';
  const D=root.ClientPortalDomain,storageKey='pcolahome-client-portal-draft-v2';
  const listeners=new Set();let state;
  const blank=()=>({version:2,clients:[],projects:[],project_settings:[],documents:[],approvals:[],reimbursements:[],invoices:[],invoice_allocations:[],payments:[],receipts:[],photos:[],showroom_items:[],contacts:[],timeline:[],conversations:[],decisions:[],internal_notes:[],closeout:[],activity:[]});
  const uid=prefix=>`${prefix}-${Math.random().toString(16).slice(2)}-${Date.now().toString(16)}`;
  const today=()=>new Date().toISOString().slice(0,10);
  const plusDays=days=>{const d=new Date(`${today()}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);};
  function sample(){
    const owner='demo-owner',clientA='client-alex',clientB='client-rivera',projectA='project-kitchen',projectB='project-deck',projectOther='project-bath';
    const estimate=D.snapshotDocument({id:'doc-estimate-v1',document_group_id:'estimate-kitchen',kind:'estimate',project_id:projectA,version:1,title:'Kitchen renovation estimate',total_cents:2485000,status:'client_ready',content:{scope:['Cabinet preparation','Backsplash installation','Finish carpentry'],terms:'Draft development fixture — no real client communication.'}});
    return {version:2,owner_id:owner,clients:[{id:clientA,owner_id:owner,name:'Demo Client',email:'client@example.test'},{id:clientB,owner_id:owner,name:'Isolation Test Client',email:'other@example.test'}],projects:[
      {id:projectA,owner_id:owner,client_id:clientA,name:'Kitchen Renovation',address:'Development fixture',status:'estimating',archived_at:null},
      {id:projectB,owner_id:owner,client_id:clientA,name:'Deck Refresh',address:'Development fixture',status:'walkthrough',archived_at:null},
      {id:projectOther,owner_id:owner,client_id:clientB,name:'Bathroom Update',address:'Private isolation fixture',status:'scheduled',archived_at:null}
    ],project_settings:[
      {project_id:projectA,phase:'Walkthrough',next_step:'Review and approve the estimate',updated_at:new Date().toISOString()},
      {project_id:projectB,phase:'Planning & Logistics',next_step:'Confirm material selections',updated_at:new Date().toISOString()},
      {project_id:projectOther,phase:'Project Scheduled',next_step:'Owner-only isolation fixture',updated_at:new Date().toISOString()}
    ],documents:[estimate],approvals:[],reimbursements:[],invoices:[],invoice_allocations:[],payments:[],receipts:[],photos:[
      {id:'photo-before-1',project_id:projectA,name:'Before photo',stage:'before',client_visible:true,showroom_eligible:true,url:''},
      {id:'photo-private-1',project_id:projectOther,name:'Private client photo',stage:'progress',client_visible:true,showroom_eligible:false,url:''}
    ],showroom_items:[],contacts:[
      {id:'contact-client-alex',project_id:projectA,name:'Demo Client',role:'Client',email:'client@example.test',phone:'(850) 555-0100',client_visible:true,can_approve:true,access_active:true},
      {id:'contact-pm',project_id:projectA,name:'Project Manager',role:'Primary contact',email:'projects@example.test',phone:'(850) 555-0110',client_visible:true,can_approve:false,access_active:false}
    ],timeline:[
      {id:'timeline-walkthrough',project_id:projectA,title:'Project walkthrough',date:today(),status:'complete',client_visible:true,detail:'Initial walkthrough and scope review.'},
      {id:'timeline-estimate',project_id:projectA,title:'Estimate review',date:plusDays(2),status:'upcoming',client_visible:true,detail:'Review the estimate and send questions in Project Chat.'}
    ],conversations:[
      {id:'message-welcome',project_id:projectA,sender_type:'owner',sender_name:'Project Team',kind:'update',body:'Welcome to your project portal. Use Project Chat whenever you have a question.',created_at:new Date().toISOString(),client_visible:true,owner_read_at:new Date().toISOString()}
    ],decisions:[
      {id:'decision-backsplash',project_id:projectA,title:'Backsplash selection',description:'Choose the preferred backsplash finish.',options:['White subway tile','Warm stone mosaic','Provide another option'],choice:null,status:'open',due_on:plusDays(7),client_visible:true}
    ],internal_notes:[{id:'note-seed',project_id:projectA,body:'Internal development note. This must never enter the client view.',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}],closeout:[{project_id:projectA,status:'not_started',completed_at:null,acknowledged_at:null,warranty_summary:'',care_instructions:''}],activity:[{id:uid('activity'),project_id:projectA,type:'draft_seeded',created_at:new Date().toISOString(),message:'Local development fixture created.'}]};
  }
  function clone(value){return JSON.parse(JSON.stringify(value));}
  function validate(next){
    if(next.version!==2)throw new Error('Unsupported portal data version.');
    for(const name of Object.keys(blank()).filter(k=>k!=='version'))if(!Array.isArray(next[name]))throw new Error(`Portal data is missing ${name}.`);
    return next;
  }
  function load(){try{const saved=localStorage.getItem(storageKey);state=saved?validate(JSON.parse(saved)):sample();}catch{state=sample();}return state;}
  function persist(){localStorage.setItem(storageKey,JSON.stringify(state));listeners.forEach(fn=>fn(snapshot()));}
  function snapshot(){return clone(state||load());}
  function project(id){const row=state.projects.find(x=>x.id===id);if(!row)throw new Error('Project not found.');return row;}
  function activity(project_id,type,message){state.activity.unshift({id:uid('activity'),project_id,type,message,created_at:new Date().toISOString()});}
  function reset(){state=sample();persist();return snapshot();}
  function setPhase(project_id,phase,next_step){project(project_id);D.phase(phase);next_step=D.required(next_step,'Next step');const row=state.project_settings.find(x=>x.project_id===project_id),value={project_id,phase,next_step,updated_at:new Date().toISOString()};row?Object.assign(row,value):state.project_settings.push(value);activity(project_id,'phase_updated',`${phase}: ${next_step}`);persist();return value;}
  function approve(document_id,input){const document=state.documents.find(x=>x.id===document_id);if(!document)throw new Error('Document not found.');if(state.approvals.some(x=>x.document_id===document.id))throw new Error('This document version already has an approval record.');const approval=D.approveDocument(document,input);state.approvals.push(approval);document.status='approved';const setting=state.project_settings.find(x=>x.project_id===document.project_id);if(document.kind==='estimate'&&setting){setting.phase='Estimate Approved';setting.next_step='Schedule the project';setting.updated_at=new Date().toISOString();}activity(document.project_id,`${document.kind}_approved`,`${document.title} v${document.version} approved by ${approval.signed_name}.`);persist();return approval;}
  function addChangeOrder(project_id,{title,scope,amount_cents}){project(project_id);const estimate=state.documents.find(x=>x.project_id===project_id&&x.kind==='estimate'&&D.isApproved(x,state.approvals));if(!estimate)throw new Error('Approve the original estimate before adding a change order.');const versions=state.documents.filter(x=>x.project_id===project_id&&x.kind==='change_order').map(x=>x.version);const document=D.snapshotDocument({kind:'change_order',project_id,version:versions.length?Math.max(...versions)+1:1,title:D.required(title,'Change-order title'),total_cents:D.integer(amount_cents,'Change-order amount',{min:1}),status:'client_ready',content:{scope:D.required(scope,'Change-order scope'),appends_to_estimate_id:estimate.id,appends_to_estimate_checksum:estimate.content_checksum}});state.documents.push(document);activity(project_id,'change_order_created',`${document.title} prepared for approval.`);persist();return document;}
  function issueInvoice(project_id,amount_cents=null){project(project_id);const next=state.invoices.length+1,result=D.issueInvoice({project_id,number:`INV-${String(next).padStart(4,'0')}`,issued_on:today(),due_on:plusDays(14),amount_cents,documents:state.documents.filter(x=>x.project_id===project_id),approvals:state.approvals,reimbursements:state.reimbursements.filter(x=>x.project_id===project_id),allocations:state.invoice_allocations});state.invoices.push(result.invoice);state.invoice_allocations.push(...result.allocations);activity(project_id,'invoice_issued',`${result.invoice.number} issued for ${D.centsToMoney(result.invoice.total_cents)}.`);persist();return result.invoice;}
  function recordPayment(invoice_id,input){const index=state.invoices.findIndex(x=>x.id===invoice_id);if(index<0)throw new Error('Invoice not found.');const result=D.recordPayment(state.invoices[index],input,state.payments);state.invoices[index]=result.invoice;state.payments.push(result.payment);state.receipts.push(result.receipt);activity(result.payment.project_id,'payment_recorded',`${D.centsToMoney(result.payment.amount_cents)} recorded by ${result.payment.method}; receipt ${result.receipt.number} retained.`);persist();return result;}
  function setShowroom(project_id,photo_id,visible){project(project_id);const photo=state.photos.find(x=>x.id===photo_id&&x.project_id===project_id);if(!photo||!photo.showroom_eligible)throw new Error('Only approved project photos can be added to the showroom.');const existing=state.showroom_items.find(x=>x.project_id===project_id&&x.photo_id===photo_id),row={id:existing?.id||uid('showroom'),project_id,photo_id,visible:Boolean(visible),updated_at:new Date().toISOString()};existing?Object.assign(existing,row):state.showroom_items.push(row);activity(project_id,'showroom_updated',`${photo.name} ${visible?'added to':'removed from'} showroom.`);persist();return row;}
  function addMessage(project_id,{sender_type='owner',sender_name,kind='message',body}){project(project_id);if(!['owner','client'].includes(sender_type))throw new Error('Choose a valid message sender.');const row={id:uid('message'),project_id,sender_type,sender_name:D.required(sender_name,'Sender name'),kind:['message','question','request','update'].includes(kind)?kind:'message',body:D.required(body,'Message'),created_at:new Date().toISOString(),client_visible:true,owner_read_at:sender_type==='owner'?new Date().toISOString():null};state.conversations.push(row);activity(project_id,'chat_message',`${row.sender_name} added a ${row.kind}.`);persist();return row;}
  function markMessagesRead(project_id){project(project_id);const stamp=new Date().toISOString();state.conversations.filter(x=>x.project_id===project_id&&x.sender_type==='client'&&!x.owner_read_at).forEach(x=>x.owner_read_at=stamp);persist();}
  function addInternalNote(project_id,body){project(project_id);const row={id:uid('note'),project_id,body:D.required(body,'Internal note'),created_at:new Date().toISOString()};state.internal_notes.unshift(row);activity(project_id,'internal_note_added','An owner-only note was added.');persist();return row;}
  function saveProjectNotes(project_id,body){project(project_id);const stamp=new Date().toISOString();let row=state.internal_notes.find(x=>x.project_id===project_id);if(row){row.body=String(body??'');row.updated_at=stamp;}else{row={id:uid('note'),project_id,body:String(body??''),created_at:stamp,updated_at:stamp};state.internal_notes.push(row);}localStorage.setItem(storageKey,JSON.stringify(state));return row;}
  function addTimeline(project_id,{title,date,detail='',client_visible=true}){project(project_id);const row={id:uid('timeline'),project_id,title:D.required(title,'Timeline title'),date:D.date(date),detail:String(detail||'').trim(),status:'upcoming',client_visible:Boolean(client_visible)};state.timeline.push(row);activity(project_id,'timeline_updated',`${row.title} added to the project timeline.`);persist();return row;}
  function addDecision(project_id,{title,description='',options,due_on}){project(project_id);const list=String(options||'').split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean);if(list.length<2)throw new Error('Provide at least two selection options.');const row={id:uid('decision'),project_id,title:D.required(title,'Selection title'),description:String(description||'').trim(),options:list,choice:null,status:'open',due_on:D.date(due_on),client_visible:true};state.decisions.push(row);activity(project_id,'selection_requested',`${row.title} sent for client selection.`);persist();return row;}
  function chooseDecision(decision_id,choice){const row=state.decisions.find(x=>x.id===decision_id);if(!row)throw new Error('Selection not found.');if(!row.options.includes(choice))throw new Error('Choose an available option.');row.choice=choice;row.status='selected';row.selected_at=new Date().toISOString();activity(row.project_id,'selection_completed',`${row.title}: ${choice}.`);persist();return row;}
  function setContactAccess(contact_id,active){const row=state.contacts.find(x=>x.id===contact_id);if(!row)throw new Error('Contact not found.');row.access_active=Boolean(active);activity(row.project_id,'client_access_updated',`${row.name} portal access ${row.access_active?'enabled':'disabled'}.`);persist();return row;}
  function setDocumentStatus(document_id,status){const row=state.documents.find(x=>x.id===document_id);if(!row)throw new Error('Document not found.');if(row.status==='approved')throw new Error('Approved document versions are immutable.');if(!['draft','client_ready','superseded','void'].includes(status))throw new Error('Choose a valid document status.');row.status=status;activity(row.project_id,'document_status_updated',`${row.title} marked ${status.replace('_',' ')}.`);persist();return row;}
  function completeProject(project_id){const row=project(project_id),setting=state.project_settings.find(x=>x.project_id===project_id),closeout=state.closeout.find(x=>x.project_id===project_id)||{project_id};row.status='completed';if(setting){setting.phase='Project Completed';setting.next_step='Closeout package and acknowledgment';setting.updated_at=new Date().toISOString();}closeout.status='ready';closeout.completed_at=new Date().toISOString();if(!state.closeout.includes(closeout))state.closeout.push(closeout);activity(project_id,'project_completed','Project marked complete; records retained.');persist();return row;}
  function setArchived(project_id,archived){const row=project(project_id);row.archived_at=archived?new Date().toISOString():null;activity(project_id,archived?'project_archived':'project_restored',archived?'Project archived without deleting records.':'Project restored to the active workspace.');persist();return row;}
  function acknowledgeCloseout(project_id){project(project_id);const row=state.closeout.find(x=>x.project_id===project_id);if(!row||row.status!=='ready')throw new Error('The closeout package is not ready.');row.status='acknowledged';row.acknowledged_at=new Date().toISOString();activity(project_id,'closeout_acknowledged','Client acknowledged the project closeout package.');persist();return row;}
  function clientView(clientId){return D.visibleState(state,clientId);}
  function exportDraft(){return new Blob([JSON.stringify(state,null,2)],{type:'application/json'});}
  function session(){try{const raw=localStorage.getItem('tagims-ops-session');const value=raw&&JSON.parse(raw);return value?.access_token?value:null;}catch{return null;}}
  async function cloudRequest(path,init={}){const auth=session(),config=root.ClientPortalConfig||{};if(!auth)throw new Error('Sign in through the Hub before connecting the portal workspace.');if(!config.supabaseUrl||!config.publishableKey)throw new Error('Supabase public configuration is unavailable.');const response=await fetch(config.supabaseUrl+path,{...init,headers:{apikey:config.publishableKey,Authorization:`Bearer ${auth.access_token}`,'Content-Type':'application/json',...(init.headers||{})}});if(!response.ok){let body={};try{body=await response.json();}catch{}throw new Error(body.message||body.error||`Portal request failed (${response.status}).`);}return response.status===204?null:response.json();}
  async function inspectCloud(){
    const [clients,projects]=await Promise.all([cloudRequest('/rest/v1/ops_clients?select=id,name,email&order=name'),cloudRequest('/rest/v1/ops_projects?select=id,client_id,name,status,next_action&order=name')]);
    return {clients,projects,portalTables:'Migration draft has not been applied; cloud writes remain disabled.'};
  }
  async function cloudWrite(path,body){if(root.ClientPortalConfig?.enableCloudWrites!==true)throw new Error('Cloud portal writes are disabled for safe development. Apply and verify the reviewed migration in a development backend first.');return cloudRequest(path,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});}
  load();
  root.ClientPortalStore={get mode(){return root.ClientPortalConfig?.mode||'local-draft';},snapshot,reset,on(fn){listeners.add(fn);return()=>listeners.delete(fn);},setPhase,approve,addChangeOrder,issueInvoice,recordPayment,setShowroom,addMessage,markMessagesRead,addInternalNote,saveProjectNotes,addTimeline,addDecision,chooseDecision,setContactAccess,setDocumentStatus,completeProject,setArchived,acknowledgeCloseout,clientView,exportDraft,inspectCloud,cloudWrite};
})(globalThis);
