(function(root){
  'use strict';
  const D=root.ClientPortalDomain,S=root.ClientPortalStore,PDF=root.ClientPortalPDF,mounts=new Set();
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const money=D.centsToMoney;
  const option=(value,label,selected)=>`<option value="${esc(value)}" ${(selected===true||value===selected)?'selected':''}>${esc(label)}</option>`;
  const button=(label,action,id='')=>`<button type="button" class="nf-btn" data-portal-action="${action}" ${id?`data-id="${esc(id)}"`:''}>${esc(label)}</button>`;
  const report=(el,message,error=false)=>{const out=el.querySelector('[data-portal-status]');if(out){out.textContent=message;out.classList.toggle('nf-error',error);}};
  const selectedProject=(el,state)=>state.projects.find(x=>x.id===(el.dataset.projectId||state.projects[0]?.id))||state.projects[0];
  function documentLines(document){const content=document.content||{},lines=[`Version: ${document.version}`,`Status: ${document.status}`,`Total: ${money(document.total_cents)}`,`Version checksum: ${document.content_checksum}`];if(Array.isArray(content.scope))lines.push(...content.scope.map(x=>`Scope: ${x}`));else if(content.scope)lines.push(`Scope: ${content.scope}`);if(content.terms)lines.push(`Terms: ${content.terms}`);if(content.appends_to_estimate_id)lines.push(`Appends to approved estimate: ${content.appends_to_estimate_id}`);return lines;}
  function showPDF(el,document){el._pdfUrls??=[];const url=URL.createObjectURL(PDF.create(document.title,documentLines(document)));el._pdfUrls.push(url);const frame=el.querySelector('[data-portal-pdf]');frame.src=url;frame.title=`${document.title} PDF`;frame.hidden=false;}
  function summary(project,state){const setting=state.project_settings.find(x=>x.project_id===project.id)||{},financial=D.projectFinancials(project.id,state);return `<section class="fd-card nf-section"><small>Current phase</small><h2>${esc(setting.phase||'Not set')}</h2><p>${esc(setting.next_step||'Next step not set')}</p><div class="nf-kpis"><div class="nf-kpi"><small>Invoiced</small><strong>${money(financial.invoiced_cents)}</strong></div><div class="nf-kpi"><small>Paid</small><strong>${money(financial.paid_cents)}</strong></div><div class="nf-kpi"><small>Outstanding</small><strong>${money(financial.outstanding_cents)}</strong></div></div></section>`;}
  function ownerFinancials(project,state){const financial=D.projectFinancials(project.id,state);return `<div class="nf-kpis portal-financials"><div class="nf-kpi"><small>Invoiced</small><strong>${money(financial.invoiced_cents)}</strong></div><div class="nf-kpi"><small>Paid</small><strong>${money(financial.paid_cents)}</strong></div><div class="nf-kpi"><small>Outstanding</small><strong>${money(financial.outstanding_cents)}</strong></div></div>`;}
  function phaseGauge(setting){const current=Math.max(0,D.PHASES.indexOf(setting.phase)),progress=D.PHASES.length>1?current/(D.PHASES.length-1)*100:100;return `<section class="portal-progress" aria-label="Project progress"><div class="portal-phase-scroll"><ol class="portal-phase-rail" style="--portal-progress:${progress}%">${D.PHASES.map((phase,index)=>`<li class="${index<current?'is-complete':index===current?'is-current':''}"><label title="Set phase to ${esc(phase)}"><input type="radio" name="portal-phase-${esc(setting.project_id||'project')}" value="${esc(phase)}" data-portal-phase ${index===current?'checked':''}><i aria-hidden="true"></i><span>${esc(phase)}</span></label></li>`).join('')}</ol></div></section>`;}
  const ownerSection=(id,title,body)=>`<details class="fd-section portal-section" id="portal-${id}" data-portal-section="${id}" open><summary><h2>${esc(title)}</h2></summary><div class="fd-section-body">${body}</div></details>`;
  const ownerSubsection=(id,title,body,open=true)=>`<details class="fd-subsection portal-subsection" id="portal-${id}" ${open?'open':''}><summary><h3>${esc(title)}</h3></summary><div class="fd-subsection-body">${body}</div></details>`;
  function documentRows(documents,state){return documents.map(doc=>`<article class="nf-section"><div class="nf-heading"><div><strong>${esc(doc.title)}</strong><small>${esc(doc.kind.replace('_',' '))} · v${doc.version} · ${esc(doc.status)} · ${money(doc.total_cents)}<br>Version ${esc(doc.content_checksum)}</small></div></div><div class="nf-toolbar">${button('View PDF','view-pdf',doc.id)}${doc.status==='client_ready'?button(doc.kind==='estimate'?'APPROVE ESTIMATE':'APPROVE CHANGE ORDER','approve',doc.id):''}</div></article>`).join('')||'<p>No documents.</p>';}
  const dateLabel=value=>value?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(`${String(value).slice(0,10)}T12:00:00`)):'Not scheduled';
  const attentionRows=items=>items.length?`<div class="portal-attention-list">${items.map(item=>`<article class="portal-attention is-${esc(item.priority)}"><span>${esc(item.kind)}</span><strong>${esc(item.label)}</strong></article>`).join('')}</div>`:'<p class="portal-empty">Nothing needs attention right now.</p>';
  const timelineRows=rows=>rows.length?`<div class="portal-timeline">${[...rows].sort((a,b)=>a.date.localeCompare(b.date)).map(row=>`<article><time>${esc(dateLabel(row.date))}</time><i aria-hidden="true"></i><div><strong>${esc(row.title)}</strong><small>${esc(row.status)}${row.detail?` · ${esc(row.detail)}`:''}</small></div></article>`).join('')}</div>`:'<p class="portal-empty">No timeline events yet.</p>';
  const chatRows=rows=>rows.length?`<div class="portal-chat">${[...rows].sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(row=>`<article class="is-${esc(row.sender_type)}"><div><strong>${esc(row.sender_name)}</strong><small>${esc(row.kind)} · ${esc(new Date(row.created_at).toLocaleString())}</small></div><p>${esc(row.body)}</p></article>`).join('')}</div>`:'<p class="portal-empty">No messages yet.</p>';
  const decisionRows=(rows,interactive=false)=>rows.length?`<div class="portal-decisions">${rows.map(row=>`<article class="nf-section"><div class="nf-heading"><div><strong>${esc(row.title)}</strong><small>${esc(row.status)} · due ${esc(dateLabel(row.due_on))}</small></div></div><p>${esc(row.description||'')}</p>${row.status==='open'&&interactive?`<label>Choose an option<select data-decision-choice="${esc(row.id)}"><option value="">Select…</option>${row.options.map(value=>option(value,value,false)).join('')}</select></label>`:`<strong>${row.choice?`Selected: ${esc(row.choice)}`:'Awaiting selection'}</strong>`}</article>`).join('')}</div>`:'<p class="portal-empty">No selections are waiting.</p>';
  function ownerDocumentRows(documents,state){return documents.map(doc=>`<article class="nf-section"><div class="nf-heading"><div><strong>${esc(doc.title)}</strong><small>${esc(doc.kind.replace('_',' '))} · v${doc.version} · ${money(doc.total_cents)}<br>Version ${esc(doc.content_checksum)}</small></div><label class="portal-inline-field"><span>Status</span>${doc.status==='approved'?'<strong>Approved · locked</strong>':`<select data-document-status="${esc(doc.id)}">${['draft','client_ready','superseded','void'].map(value=>option(value,value.replace('_',' '),value===doc.status)).join('')}</select>`}</label></div><div class="nf-toolbar">${button('View PDF','view-pdf',doc.id)}</div></article>`).join('')||'<p>No documents.</p>';}
  function ownerMarkup(el,state){
    const project=selectedProject(el,state);if(!project)return '<section class="fd-card"><p>No projects are available.</p></section>';el.dataset.projectId=project.id;
    const setting=state.project_settings.find(x=>x.project_id===project.id)||{},client=state.clients.find(x=>x.id===project.client_id),documents=state.documents.filter(x=>x.project_id===project.id),invoices=state.invoices.filter(x=>x.project_id===project.id),receipts=state.receipts.filter(x=>x.project_id===project.id),photos=state.photos.filter(x=>x.project_id===project.id&&x.showroom_eligible),contacts=state.contacts.filter(x=>x.project_id===project.id),decisions=state.decisions.filter(x=>x.project_id===project.id),notes=state.internal_notes.filter(x=>x.project_id===project.id),activity=state.activity.filter(x=>x.project_id===project.id),closeout=state.closeout.find(x=>x.project_id===project.id),attention=D.attentionItems(project.id,state),approvedEstimate=documents.find(x=>x.kind==='estimate'&&D.isApproved(x,state.approvals));
    const changeOrder=approvedEstimate?`<div class="ops-form-grid"><label>Change-order title<input data-change-title value="Additional approved work"></label><label>Charge<input data-change-amount type="number" step="0.01" value="750"></label><label>Scope<textarea data-change-scope>Document the added scope without altering the original estimate.</textarea></label></div>${button('Create change order','create-change')}`:'<p class="nf-note">Approve the estimate before creating an appended change order.</p>';
    const invoiceBody=`<div class="nf-heading portal-section-actions">${button('Generate next invoice','issue-invoice')}</div>${invoices.map(inv=>`<article class="nf-section"><div><strong>${esc(inv.number)}</strong><small>${money(inv.total_cents)} · ${esc(inv.status)} · balance ${money(inv.balance_cents)}</small></div><div class="nf-toolbar">${inv.balance_cents?button('Record payment','record-payment',inv.id):''}</div></article>`).join('')||'<p>No invoices issued.</p>'}`;
    const receiptBody=receipts.map(r=>`<article class="nf-section"><div><strong>${esc(r.number)}</strong><small>${money(r.amount_cents)} · ${esc(r.method)} · ${r.sent_at?'sent':'recorded, not sent'}</small></div><div class="nf-toolbar"><button type="button" class="nf-btn" disabled title="Delivery is intentionally disabled during development">Send receipt</button></div></article>`).join('')||'<p>Every payment creates and retains a receipt. Delivery remains explicit and disabled.</p>';
    const showroomBody=`<p class="nf-note">Selections contain no financial documents, signatures, receipts, or contact details.</p>${photos.map(photo=>`<label class="ops-check"><input type="checkbox" data-showroom-photo="${esc(photo.id)}" ${state.showroom_items.some(x=>x.photo_id===photo.id&&x.visible)?'checked':''}> ${esc(photo.name)} · ${esc(photo.stage)}</label>`).join('')||'<p>No approved showroom photos.</p>'}`;
    const projectNote=notes[0];
    const overviewBody=`<div class="portal-overview-grid"><div class="portal-snapshot-attention"><div class="portal-snapshot-heading"><div><small>Needs attention</small><strong>${attention.length?`${attention.length} open item${attention.length===1?'':'s'}`:'All clear'}</strong></div><span>${esc(setting.next_step||'No next step set')}</span></div>${attentionRows(attention.slice(0,3))}</div>${ownerFinancials(project,state)}</div>`;
    const selectionsBody=`<div class="portal-section-actions">${button('Request selection','add-decision')}</div>${decisionRows(decisions)}`;
    const notesBody=`<div class="portal-notepad-wrap"><textarea class="portal-notepad" data-project-notes aria-label="Owner-only project notes" placeholder="Start typing project notes…">${esc(projectNote?.body||'')}</textarea><div class="portal-notepad-footer"><small>Owner only · excluded from the client portal</small><span data-notes-status>${projectNote?.updated_at?'Saved '+esc(new Date(projectNote.updated_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})):'Ready'}</span></div></div>`;
    const contactsBody=`<div class="portal-access">${contacts.map(contact=>`<article class="nf-section"><div><strong>${esc(contact.name)}</strong><small>${esc(contact.role)} · ${esc(contact.email||'')} · ${esc(contact.phone||'')}</small></div><label class="ops-check"><input type="checkbox" data-contact-access="${esc(contact.id)}" ${contact.access_active?'checked':''}> Portal access</label><small>${contact.can_approve?'Can approve documents':'View/contact access only'}</small></article>`).join('')||'<p>No project contacts.</p>'}</div>`;
    const activityBody=`<div class="portal-activity">${activity.slice(0,30).map(row=>`<article><time>${esc(new Date(row.created_at).toLocaleString())}</time><p>${esc(row.message)}</p></article>`).join('')||'<p>No activity yet.</p>'}</div>`;
    const completionBody=`<div class="portal-closeout"><p><strong>Project status:</strong> ${esc(project.status||'active')}</p><p><strong>Completion package:</strong> ${esc((closeout?.status||'not started').replace('_',' '))}</p><p class="nf-note">Completing a project preserves its estimates, approvals, invoices, receipts, photos, and history. Archiving simply removes it from the active workload.</p><div class="nf-toolbar">${project.status==='completed'?'':button('Mark project complete','complete-project')}${button(project.archived_at?'Restore project':'Archive project',project.archived_at?'restore-project':'archive-project')}</div></div>`;
    const projectNotesBody=`${ownerSubsection('selections','Selections',selectionsBody)}${ownerSubsection('notes','Notes',notesBody)}`;
    const financialBody=`${ownerSubsection('estimates','Estimates & Approvals',`${ownerDocumentRows(documents,state)}<iframe data-portal-pdf class="fd-card portal-pdf-frame" hidden></iframe>${changeOrder}`)}${ownerSubsection('invoices','Invoices',invoiceBody)}${ownerSubsection('receipts','Receipts',receiptBody)}`;
    const managementBody=`${ownerSubsection('access','Contacts & Access',contactsBody)}${ownerSubsection('activity','Activity History',activityBody)}${ownerSubsection('completion','Completion & Archive',completionBody)}`;
    const nav=[['Overview','overview'],['Financials','financials'],['Project Notes','project-notes'],['Photos','showroom'],['Management Admin','management']];
    return `<div class="portal-root fd-root nf-root" data-portal-mode="owner"><header class="portal-owner-header"><h1>Client Portal</h1><div class="portal-owner-controls"><div class="portal-client-name"><small>Client</small><strong>${esc(client?.name||'Client Name')}</strong></div><label><span>Project</span><select data-portal-project>${state.projects.filter(p=>p.client_id===project.client_id).map(p=>option(p.id,p.name,p.id===project.id)).join('')}</select></label>${button('Client preview','open-preview')}${button('Reset draft','reset')}</div></header>${phaseGauge(setting)}<nav class="fd-nav portal-nav" aria-label="Client Portal sections"><div class="fd-nav-links">${nav.map(([label,id])=>`<a href="#portal-${id}" data-portal-action="jump" data-id="${id}">${label}</a>`).join('')}</div><button type="button" class="fd-expand-all" data-expand="false" data-portal-action="toggle-sections" aria-label="Collapse all sections" title="Collapse all sections"><span class="fd-menu-icon" aria-hidden="true"></span></button></nav><div class="fd-scroll portal-scroll">${ownerSection('overview','Overview',overviewBody)}${ownerSection('financials','Financials',financialBody)}${ownerSection('project-notes','Project Notes',projectNotesBody)}${ownerSection('showroom','Photos',showroomBody)}${ownerSection('management','Management Admin',managementBody)}<p data-portal-status role="status" class="nf-note">Draft ready.</p></div></div>`;
  }
  function clientMarkup(el,state,clientId){
    const view=S.clientView(clientId),project=selectedProject(el,view);if(!project)return '<div class="portal-root fd-root nf-root"><section class="fd-card"><h1>Client Portal</h1><p>No authorized projects.</p></section></div>';el.dataset.projectId=project.id;const documents=view.documents.filter(x=>x.project_id===project.id),invoices=view.invoices.filter(x=>x.project_id===project.id),receipts=view.receipts.filter(x=>x.project_id===project.id),showroom=view.showroom_items.filter(x=>x.project_id===project.id&&x.visible),decisions=view.decisions.filter(x=>x.project_id===project.id),contacts=view.contacts.filter(x=>x.project_id===project.id),closeout=view.closeout.find(x=>x.project_id===project.id),attention=D.attentionItems(project.id,view,new Date().toISOString().slice(0,10),'client');
    return `<div class="portal-root fd-root nf-root" data-portal-mode="client"><div class="nf-topbar"><div><small>Secure project workspace · development preview</small><h1>Client Portal</h1></div><label>Project<select data-portal-project>${view.projects.map(p=>option(p.id,p.name,p.id===project.id)).join('')}</select></label></div>${summary(project,view)}<section class="fd-card nf-section"><h2>What needs your attention</h2>${attentionRows(attention)}</section><section class="fd-card nf-section"><h2>Selections and decisions</h2>${decisionRows(decisions,true)}</section><section class="fd-card nf-section"><h2>Documents</h2>${documentRows(documents,view)}<iframe data-portal-pdf class="fd-card portal-pdf-frame" hidden></iframe></section><section class="fd-card nf-section"><h2>Invoices and receipts</h2>${invoices.map(i=>`<p><strong>${esc(i.number)}</strong> · ${money(i.balance_cents)} remaining</p>`).join('')||'<p>No invoices.</p>'}${receipts.map(r=>`<p><strong>${esc(r.number)}</strong> · ${money(r.amount_cents)} received</p>`).join('')}</section><section class="fd-card nf-section"><h2>Project photos</h2>${showroom.map(item=>`<p>Shared project photo · ${esc(view.photos.find(p=>p.id===item.photo_id)?.stage||'project')}</p>`).join('')||'<p>No project photos shared yet.</p>'}</section><section class="fd-card nf-section"><h2>Your project contacts</h2>${contacts.map(contact=>`<article class="nf-section"><strong>${esc(contact.name)}</strong><small>${esc(contact.role)} · ${esc(contact.email||'')} · ${esc(contact.phone||'')}</small></article>`).join('')||'<p>No contacts available.</p>'}</section><section class="fd-card nf-section"><h2>Project closeout</h2><p>${closeout?.status==='ready'?'Your closeout package is ready.':closeout?.status==='acknowledged'?'Closeout package acknowledged.':'Closeout materials will appear here when the project is complete.'}</p>${closeout?.status==='ready'?button('Acknowledge closeout','acknowledge-closeout'):''}</section><p data-portal-status role="status" class="nf-note">Client isolation preview active.</p></div>`;
  }
  function render(el){const state=S.snapshot(),mode=el.dataset.portalHostMode||'owner',clientId=el.dataset.clientId||state.clients[0]?.id;el._pdfUrls?.forEach(URL.revokeObjectURL);el._pdfUrls=[];el.innerHTML=mode==='client'?clientMarkup(el,state,clientId):ownerMarkup(el,state);if(mode==='owner'){const title=el.querySelector('.portal-owner-header h1'),nav=el.querySelector('.portal-nav');if(title)title.textContent='Project Portal';if(nav)nav.setAttribute('aria-label','Project Portal sections');}}
  function dialog(title,content,onSubmit,submit='Save'){
    const box=document.createElement('dialog');box.className='nf-dialog';box.innerHTML=`<form><div class="nf-heading"><h2>${esc(title)}</h2><button type="button" class="nf-btn" data-close>×</button></div>${content}<p class="nf-error" role="alert"></p><div class="nf-toolbar"><button class="nf-btn nf-primary" type="submit">${esc(submit)}</button><button class="nf-btn" type="button" data-close>Cancel</button></div></form>`;document.body.append(box);box.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>box.close());box.addEventListener('close',()=>box.remove());box.querySelector('form').onsubmit=event=>{event.preventDefault();try{onSubmit(Object.fromEntries(new FormData(event.currentTarget)));box.close();}catch(error){box.querySelector('[role=alert]').textContent=error.message;}};box.showModal();
  }
  function action(el,button){const state=S.snapshot(),project=selectedProject(el,state),name=button.dataset.portalAction;
    if(name==='reset')return void S.reset();
    if(name==='open-preview'){const url=new URL('client-portal/standalone.html',location.href);url.searchParams.set('client',project.client_id);url.searchParams.set('project',project.id);window.open(url,'_blank','noopener');return;}
    if(name==='save-phase')return void S.setPhase(project.id,el.querySelector('[data-phase]').value,el.querySelector('[data-next-step]').value);
    if(name==='jump'){const target=el.querySelector(`#portal-${button.dataset.id}`),scroll=el.querySelector('.portal-scroll');if(target&&scroll){target.open=true;scroll.scrollTo({top:scroll.scrollTop+target.getBoundingClientRect().top-scroll.getBoundingClientRect().top-12,behavior:'smooth'});}return;}
    if(name==='toggle-sections'){const sections=[...el.querySelectorAll('[data-portal-section]')],expand=sections.some(section=>!section.open);sections.forEach(section=>section.open=expand);button.dataset.expand=String(!expand);button.title=button.ariaLabel=expand?'Collapse all sections':'Expand all sections';return;}
    if(name==='add-timeline')return void dialog('Add timeline event',`<label>Title<input name="title" required></label><label>Date<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Details<textarea name="detail"></textarea></label>`,fields=>S.addTimeline(project.id,fields),'Add event');
    if(name==='add-chat'){const clientMode=el.dataset.portalHostMode==='client',client=state.clients.find(x=>x.id===project.client_id);return void dialog(clientMode?'Ask a question':'Add Project Chat message',`<label>Type<select name="kind"><option value="question">Question</option><option value="message">Message</option><option value="request">Request</option><option value="update">Update</option></select></label><label>Message<textarea name="body" required></textarea></label>`,fields=>S.addMessage(project.id,{sender_type:clientMode?'client':'owner',sender_name:clientMode?(client?.name||'Client'):'Project Team',kind:fields.kind,body:fields.body}),'Post message');}
    if(name==='mark-chat-read')return void S.markMessagesRead(project.id);
    if(name==='add-decision')return void dialog('Request a selection',`<label>Selection title<input name="title" required></label><label>Description<textarea name="description"></textarea></label><label>Options<textarea name="options" required placeholder="One option per line"></textarea></label><label>Decision due<input name="due_on" type="date" required></label>`,fields=>S.addDecision(project.id,fields),'Request selection');
    if(name==='complete-project')return void S.completeProject(project.id);
    if(name==='archive-project')return void S.setArchived(project.id,true);
    if(name==='restore-project')return void S.setArchived(project.id,false);
    if(name==='acknowledge-closeout')return void S.acknowledgeCloseout(project.id);
    if(name==='view-pdf'){const document=state.documents.find(x=>x.id===button.dataset.id);if(document)showPDF(el,document);return;}
    if(name==='approve'){const document=state.documents.find(x=>x.id===button.dataset.id),client=state.clients.find(x=>x.id===project.client_id);return void dialog(document.kind==='estimate'?'Approve estimate':'Approve change order',`<p>Approve ${esc(document.title)}, version ${document.version}, checksum ${esc(document.content_checksum)}.</p><label>Type your full name<input name="signed_name" required value="${esc(client?.name||'')}"></label><label class="ops-check"><input type="checkbox" name="accepted" value="yes" required> I approve this exact document version and electronic signature.</label>`,fields=>S.approve(document.id,{client_id:project.client_id,signed_name:fields.signed_name,accepted:fields.accepted==='yes',approval_text:'I approve this exact document version and electronic signature.'}),'Approve and sign');}
    if(name==='create-change')return void S.addChangeOrder(project.id,{title:el.querySelector('[data-change-title]').value,scope:el.querySelector('[data-change-scope]').value,amount_cents:D.moneyToCents(el.querySelector('[data-change-amount]').value)});
    if(name==='issue-invoice')return void S.issueInvoice(project.id);
    if(name==='record-payment'){const invoice=state.invoices.find(x=>x.id===button.dataset.id);return void dialog('Record manual payment',`<label>Method<select name="method">${D.PAYMENT_METHODS.map(x=>option(x,x,false)).join('')}</select></label><label>Amount<input name="amount" type="number" step="0.01" value="${(invoice.balance_cents/100).toFixed(2)}" required></label><label>Received date<input name="received_on" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Reference<input name="reference" value="manual-${Date.now()}" required></label>`,fields=>S.recordPayment(invoice.id,{method:fields.method,amount_cents:D.moneyToCents(fields.amount),received_on:fields.received_on,reference:fields.reference,receipt_number:`REC-${String(state.receipts.length+1).padStart(4,'0')}`}),'Record and create receipt');}
  }
  function saveNotes(el,field){const status=el.querySelector('[data-notes-status]');try{S.saveProjectNotes(selectedProject(el,S.snapshot()).id,field.value);if(status)status.textContent='Saved '+new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});}catch(error){if(status)status.textContent='Could not save';report(el,error.message,true);}}
  function mount(options={}){const el=document.createElement('div');el.className='client-portal-host hub-data-widget';el.dataset.portalHostMode=options.mode||'owner';if(options.clientId)el.dataset.clientId=options.clientId;if(options.projectId)el.dataset.projectId=options.projectId;mounts.add(el);el.oninput=event=>{if(event.target.matches('[data-project-notes]')){const status=el.querySelector('[data-notes-status]');if(status)status.textContent='Saving…';clearTimeout(el._notesTimer);el._notesTimer=setTimeout(()=>saveNotes(el,event.target),450);}};el.onfocusout=event=>{if(event.target.matches('[data-project-notes]')){clearTimeout(el._notesTimer);saveNotes(el,event.target);}};el.onchange=event=>{try{if(event.target.matches('[data-portal-project]')){el.dataset.projectId=event.target.value;render(el);}if(event.target.matches('[data-portal-phase]')){const project=selectedProject(el,S.snapshot()),index=D.PHASES.indexOf(event.target.value),next=D.PHASES[index+1];S.setPhase(project.id,event.target.value,next?`Next: ${next}`:'Project complete');}if(event.target.matches('[data-showroom-photo]'))S.setShowroom(selectedProject(el,S.snapshot()).id,event.target.dataset.showroomPhoto,event.target.checked);if(event.target.matches('[data-document-status]'))S.setDocumentStatus(event.target.dataset.documentStatus,event.target.value);if(event.target.matches('[data-contact-access]'))S.setContactAccess(event.target.dataset.contactAccess,event.target.checked);if(event.target.matches('[data-decision-choice]')&&event.target.value)S.chooseDecision(event.target.dataset.decisionChoice,event.target.value);}catch(error){report(el,error.message,true);}};el.onclick=event=>{const target=event.target.closest('[data-portal-action]');if(target){event.preventDefault();try{action(el,target);}catch(error){report(el,error.message,true);}}};render(el);return el;}
  S.on(()=>{for(const el of mounts)el.isConnected?render(el):mounts.delete(el);});root.ClientPortal={mount,render};
})(globalThis);
