const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const names=['sandbox-storage','shell','layout','widgets','telemetry','interactions','background'];
fs.writeFileSync(path.join(root,'hub.js'),'// Generated by tools/build.cjs; edit src files.\n(()=>{\n'+names.map(n=>fs.readFileSync(path.join(root,'src',n+'.js'),'utf8')).join('\n')+'\n})();\n');
