(() => {
  const S=window.OpsStore,D=window.OpsDomain;
  const labels={opsApps:'Apps Launcher',opsProjects:'Choose project',opsContact:'Contact & team',opsNotes:'Walkthrough',opsField:'Field plan',opsUpload:'Add photos',opsPhotos:'Photo Inbox',opsGallery:'Gallery',opsPublish:'Publish',opsEstimate:'Draft estimate',opsReview:'Review'};
  const roots=new Set();let selected=localStorage.getItem('tagims-ops-project'),busy=false;
  Object.assign(labels,{opsCRM:'Business Center',opsPhotoCenter:'Photo Center',opsEstimates:'Estimates',opsLeads:'LEADS',opsPipeline:'Pipeline',opsClients:'Clients',opsInvoices:'Invoices',opsCrew:'Crew',opsTimesheet:'Timesheet',opsFinancials:'Financials',opsProjectWorkspace:'Projects'});
  const flows={opsCRM:['opsLeads','opsClients','opsNotes','opsEstimates','opsPipeline','opsPhotoCenter','opsProjectWorkspace','opsInvoices','opsTimesheet','opsCrew','opsFinancials'],opsProjectWorkspace:['opsProjects','opsContact','opsNotes','opsField'],opsPhotoCenter:['opsUpload','opsPhotos','opsGallery','opsPublish'],opsEstimates:['opsProjects','opsNotes','opsUpload','opsEstimate','opsReview']};
  let uploadDestination='',galleryView='inbox';
  labels.opsProcessing='Client Processing';labels.opsTimesheet='Time Sheet';
  labels.opsCalendar='Calendar';labels.opsChangeOrders='Change Orders';labels.opsGallery='Photo Gallery';
  flows.opsCRM=['opsProcessing','opsProjectWorkspace','opsPhotoCenter','opsCalendar','opsTimesheet','opsFinancials'];
  labels.opsPayments='Payments';labels.opsReceipts='Receipts';
  flows.opsProcessing=['opsLeads','opsClients','opsProjectWorkspace','opsNotes','opsEstimates','opsInvoices','opsChangeOrders','opsPayments','opsReceipts'];
  labels.opsAlbums='Albums';labels.opsTrash='Trash';
  flows.opsPhotoCenter=['opsPhotos','opsGallery','opsAlbums','opsTrash'];
  delete flows.opsProjectWorkspace;
  let expandedProject=null,expandedClient=null;
  const clientOrderKey=()=>`tagims:client-order:v1:${S.mode}:${S.user?.id||'demo'}`;
  function orderedClients(){let ids=[];try{const saved=JSON.parse(localStorage.getItem(clientOrderKey())||'[]');if(Array.isArray(saved))ids=saved;}catch{}const rank=id=>ids.includes(id)?ids.indexOf(id):Infinity;return [...S.data.clients].sort((a,b)=>rank(a.id)-rank(b.id));}
  const selectedPhotos=new Set();
  const widgetGroups=[['Launcher',['opsApps','opsCRM']],['Client Processing',['opsProcessing','opsLeads','opsClients','opsProjects','opsNotes','opsEstimates','opsInvoices','opsChangeOrders','opsPayments','opsReceipts','opsEstimate','opsReview']],['Projects',['opsProjectWorkspace','opsContact','opsField','opsCrew']],['Photo Center',['opsPhotoCenter','opsPhotos','opsGallery','opsAlbums','opsTrash','opsUpload','opsPublish']],['Calendar',['opsCalendar']],['Time Sheet',['opsTimesheet']],['Financials',['opsFinancials']]];
  labels.opsProjects='Projects';
  let thumbnailSize=160;
  try{const saved=Number(localStorage.getItem('tagims-ops-thumbnail-size'));if(Number.isFinite(saved)&&saved>=80&&saved<=320)thumbnailSize=saved;}catch{}
  document.documentElement.style.setProperty('--ops-thumbnail-size',`${thumbnailSize}px`);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const project=()=>S.data.projects.find(p=>p.id===selected);
  const rows=t=>S.data[t].filter(r=>r.project_id===selected&&(t!=='photos'||!r.deleted_at));
  const estimate=()=>rows('estimates').sort((a,b)=>b.version-a.version)[0];
  const button=(label,action,id='')=>`<button type="button" data-action="${action}" data-id="${esc(id)}">${label}</button>`;
  const input=(name,label,value='',type='text',required=false)=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`;
  const area=(name,label,value='')=>`<label>${label}<textarea name="${name}" rows="4">${esc(value)}</textarea></label>`;
  const options=(values,current)=>values.map(([v,l])=>`<option value="${v}" ${v===current?'selected':''}>${esc(l)}</option>`).join('');
  let statusTimer;
  function status(message,error=false){const el=document.getElementById('ops-status');if(el){clearTimeout(statusTimer);el.textContent=message;el.dataset.error=error;el.hidden=!message;statusTimer=setTimeout(()=>{el.textContent='';el.hidden=true;},error?12000:3500);} }
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
  function dialog(title,fields,submit,label='Save'){
    const el=document.createElement('dialog');el.className='ops-dialog';el.innerHTML=`<form><h2>${esc(title)}</h2>${fields}<p class="ops-form-error" role="alert"></p><footer><button type="button" data-cancel>Cancel</button><button type="submit">${esc(label)}</button></footer></form>`;
    document.body.append(el);el.querySelector('[data-cancel]').onclick=()=>el.close();el.onclose=()=>el.remove();
    el.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=el.querySelector('[type=submit]');b.disabled=true;el.querySelector('[data-cancel]').disabled=true;try{await submit(Object.fromEntries(new FormData(e.target)));el.close();status('Saved. Your workspace is up to date.');refresh();}catch(err){el.querySelector('[role=alert]').textContent=err.message;}finally{b.disabled=false;el.querySelector('[data-cancel]').disabled=false;}};
    el.showModal();return el;
  }
  function account(){dialog('Shared workspace',`<p>Sign in once on this browser. Your workspace stays signed in until you sign out. The local demo keeps its own records on this browser.</p>${input('email','Email','','email',true)}${input('password','Password','','password',true)}${button('Use local demo','demo')}${S.mode==='demo'?button('Import PHR photo backup','importPrototype'):''}${S.mode!=='signed-out'?button('Sign out','signout'):''}`,async f=>{await S.signIn(f.email,f.password);status('Signed in. Shared records loaded.');},'Sign in');}
  function choose(id){selected=id;localStorage.setItem('tagims-ops-project',id);refresh();}
  function clientForm(existing){const c=existing||{};dialog(c.id?'Edit client':'Add client',input('name','Client name',c.name,'text',true)+input('phone','Phone',c.phone,'tel')+input('email','Email',c.email,'email'),f=>S.save('clients',{...c,...f,name:D.required(f.name,'Client name')}));}
  // A nested workspace keeps the exact same module renderers and shared store.
  // Retain each section's position across data refreshes without duplicating records.
  function dispose(el){if(!el)return;el._menuObserver?.disconnect();photoWorkspace.dispose(el);el._generation=(el._generation||0)+1;el._urls?.forEach(URL.revokeObjectURL);el._urls=[];dispose(el._child);roots.delete(el);}
  function remember(el){if(!el)return;el._memory??={};if(el._child){remember(el._child);el._memory[el._child.dataset.opsType]={step:el._child._step,memory:el._child._memory};}}
  function refresh(){
    if(uploadDestination&&!S.data.projects.some(p=>p.id===uploadDestination))uploadDestination='';
    if(!['inbox','all'].includes(galleryView)&&!S.data.projects.some(p=>p.id===galleryView))galleryView='inbox';
    if(!project()&&S.data.projects.length)selected=S.data.projects[0].id;
    const b=document.getElementById('ops-account');if(b){const label=S.mode==='cloud'?'Account':S.mode==='demo'?'Account — local demo':'Account — sign in';b.title=label;b.setAttribute('aria-label',label);}
    for(const el of roots){if(!el.isConnected){dispose(el);continue;}render(el);}
  }
  function newProject(){dialog('Create project',`<label>Existing client<select name="client_id"><option value="">Create a new client</option>${S.data.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label>${input('client','New client name')}${input('name','Project name','','text',true)}${input('address','Property address')}${input('phone','Client phone','','tel')}${input('email','Client email','','email')}`,async f=>{let clientId=f.client_id;if(!clientId)clientId=(await S.save('clients',{name:D.required(f.client,'Client name'),phone:f.phone,email:f.email})).id;const p=await S.save('projects',{client_id:clientId,name:f.name,address:f.address,status:'walkthrough'});choose(p.id);});}
  function newNote(){const projectId=selected;dialog('Walkthrough note',area('notes','Scope, observations, measurements, and decisions'),f=>S.save('walkthroughs',{project_id:projectId,notes:D.required(f.notes,'Note')}));}
  function fieldForm(existing){const x=existing||{},projectId=x.project_id||selected;dialog(x.id?'Edit field item':'Add field item',`<label>Type<select name="kind">${options(['material','punch','tool','supply','timeline','document'].map(x=>[x,x[0].toUpperCase()+x.slice(1)]),x.kind)}</select></label>${input('title','Item',x.title,'text',true)}${area('details','Details or HTTPS document link',x.details)}${input('due_date','Due date',x.due_date,'date')}`,f=>{if(f.kind==='document')f.details=D.safeLink(f.details);return S.save('field_items',{...x,...f,project_id:projectId,due_date:f.due_date||null,status:x.status||'open'});});}
  function newEstimate(id=selected){if(!S.data.projects.some(p=>p.id===id))throw new Error('Choose a project first.');dialog('Create estimate draft',area('notes','Shared scope and qualifications'),async f=>{const version=Math.max(0,...S.data.estimates.filter(e=>e.project_id===id).map(e=>Number(e.version)||0))+1;await S.save('estimates',{project_id:id,version,status:'draft',notes:f.notes,scope_confirmed:false});});}
  function clientProcess(c){
    document.querySelector('.ops-process-mini')?.close();
    const el=document.createElement('dialog');el.className='ops-dialog ops-process-mini';el.setAttribute('aria-label','Process '+c.name);
    let jobId=selected;const identity=S.mode+':'+(S.user?.id||'');
    function paint(){
      if(identity!==S.mode+':'+(S.user?.id||'')||!S.data.clients.some(x=>x.id===c.id)){el.close();return;}
      const jobs=S.data.projects.filter(p=>p.client_id===c.id);const p=jobs.find(p=>p.id===jobId)||jobs.find(p=>!['complete','archived'].includes(p.status))||jobs[0];jobId=p?.id;
      const latest=S.data.estimates.filter(e=>e.project_id===jobId).sort((a,b)=>b.version-a.version)[0];
      const notes=S.data.walkthroughs.some(n=>n.project_id===jobId),scheduled=notes||!!(p?.next_action_due&&p.next_action==='Walkthrough scheduled');
      const steps=[['Capture Lead',true,'Client recorded'],['Schedule Walkthrough',scheduled,notes?'Walkthrough notes recorded':scheduled?'Scheduled '+p.next_action_due:'Not recorded'],['Create Estimate',!!latest,latest?'Version '+latest.version:'Not started'],['Finalize & Send Estimate',false,latest?.status==='client_ready'?'Finalized · sending not connected':'Review and sending pending'],['Approve Estimate',false,'Client approval not connected'],['Create Project',!!p&&['active','complete','archived'].includes(p.status),p&&['active','complete','archived'].includes(p.status)?'Existing project':'Automatic after approval']];
      let current=steps.findIndex(s=>!s[1]),label,run,hint='';
      if(!p){current=1;label='Add walkthrough details';run=()=>actions.clientProject(c.id);hint='Start the job record for this client; activation comes after approval.';}
      else if(!scheduled&&!latest){label='Schedule walkthrough';run=()=>scheduleWalkthrough(p.id);}
      else if(!latest){current=2;label=notes?'Create estimate':'Capture walkthrough';run=()=>notes?newEstimate(p.id):actions.clientStage('opsNotes:'+p.id);hint=notes?'':'Capture the scope and photos before estimating.';}
      else{current=3;label=latest.status==='client_ready'?'Open finalized estimate':latest.status==='draft'?'Continue estimate':'Finalize estimate';run=()=>actions.clientStage((latest.status==='draft'?'opsEstimates':'opsReview')+':'+p.id);hint=latest.status==='client_ready'?'Sending and client approval are not connected yet. Finalized is not the same as sent.':'Complete the scope and review checks. Sending and client approval are not connected yet.';}
      if(p?.status==='archived'){current=-1;label='View archived project';run=()=>actions.openProject(p.id);hint='Archived job. Historical sending and approval are not inferred.';}
      el.innerHTML=`<header><div><small>CLIENT PROCESS</small><h2>${esc(c.name)}</h2></div><button type="button" data-process-close aria-label="Close process">×</button></header>${jobs.length>1?`<label>Job<select data-process-job>${options(jobs.map(p=>[p.id,p.name]),jobId)}</select></label>`:p?`<p class="ops-process-job-name">${esc(p.name)}</p>`:''}<ol class="ops-process-list">${steps.map(([name,done,note],i)=>`<li data-done="${done}" ${i===current?'aria-current="step"':''}><span class="ops-process-mark" aria-label="${done?'Complete':i===current?'Current':'Pending'}">${done?'✓':i+1}</span><div><strong>${esc(name)}</strong><small>${esc(note)}</small></div></li>`).join('')}</ol>${hint?`<p class="ops-process-hint">${esc(hint)}</p>`:''}<button type="button" class="ops-process-next">${esc(label)} →</button>`;
      el.querySelector('[data-process-close]').onclick=()=>el.close();el.querySelector('[data-process-job]')?.addEventListener('change',e=>{jobId=e.target.value;paint();});
      el.querySelector('.ops-process-next').onclick=()=>{el.close();try{run();}catch(e){status(e.message,true);}};
    }
    document.body.append(el);const off=S.on(paint);el.onclose=()=>{off();el.remove();};paint();el.showModal();
  }
  function scheduleWalkthrough(id){const p=S.data.projects.find(p=>p.id===id);if(!p)return;dialog('Schedule walkthrough',input('date','Walkthrough date',p.next_action_due||'','date',true)+'<p>This records the agreed date. It does not send an invitation or create a calendar event.</p>',async f=>{const current=S.data.projects.find(p=>p.id===id);if(!current)throw new Error('Project no longer available.');await S.save('projects',{...current,next_action:'Walkthrough scheduled',next_action_due:f.date});},'Save walkthrough date');}
  function estimateItem(existing){const e=estimate(),x=existing||{};if(!e||e.status!=='draft')throw new Error('Return this estimate to a new draft revision before changing it.');dialog(x.id?'Edit scope item':'Add scope item',`${input('description','Scope item',x.description,'text',true)}${input('quantity','Quantity (blank = TBD)',x.quantity??'')}${input('unit','Unit',x.unit||'job')}${input('unit_price','Unit price (blank = TBD)',x.unit_price??'')}`,f=>{if(f.quantity!=='')D.money(f.quantity);if(f.unit_price!=='')D.money(f.unit_price);return S.save('estimate_items',{...x,...f,estimate_id:e.id,quantity:f.quantity===''?null:Number(f.quantity),unit_price:f.unit_price===''?null:Number(f.unit_price)});});}
  function review(action){const e=estimate();const names={submit:'Submit for Inspector',inspector:'Complete Inspector review',reviewer:'Complete final Reviewer pass',revise:'Create revision'};dialog(names[action],action==='revise'?'<p>Create a new draft version. The reviewed version remains unchanged.</p>':`<p>This records your manual review; it does not run an AI review or send anything to the client.</p><label class="ops-check"><input name="confirmed" type="checkbox" required> ${action==='inspector'?'I inspected both copies, reconciled the scope and totals, and applied only Alex-approved corrections.':action==='reviewer'?'I inspected the final client copy, checked for private information and unresolved issues, and applied approved corrections.':'Proposed scope, quantities, client details, and assumptions are confirmed for inspection.'}</label>`,()=>S.review(e.id,action),names[action]);}
  function photoEdit(p){dialog('Photo details',`${input('caption','Caption',p.caption)}${input('room','Room / work area',p.room)}<label>Stage<select name="stage">${options(['unsorted','before','during','after'].map(s=>[s,s[0].toUpperCase()+s.slice(1)]),p.stage)}</select></label>`,f=>S.save('photos',{...p,...f}));}
  async function exportGallery(){const photos=rows('photos').filter(p=>p.website_public);if(!photos.length)throw new Error('Approve at least one photo first.');dialog('Export approved website gallery',`${input('title','Public project title (no client name)','','text',true)}${input('city','Public city (no street address)','','text',true)}<p>Exports only approved photos as resized JPEGs with source metadata removed. This creates a website-ready file; it does not publish to PColaHome.com.</p>`,async f=>{let figures='';for(const p of photos){const url=await S.image(p);try{const img=new Image();img.crossOrigin='anonymous';img.src=url;await img.decode();const scale=Math.min(1,1600/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);figures+=`<figure><img alt="${esc(p.caption||p.stage)}" src="${canvas.toDataURL('image/jpeg',0.85)}"><figcaption>${esc(p.caption||p.stage)}</figcaption></figure>`;}finally{if(url.startsWith('blob:'))URL.revokeObjectURL(url);}}download(new Blob([`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(f.title)}</title><style>body{font:16px system-ui;margin:40px auto;padding:20px;max-width:1000px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}figure{margin:0}img{width:100%;border-radius:12px}</style><h1>${esc(f.title)}</h1><p>${esc(f.city)}</p><main>${figures}</main></html>`],{type:'text/html'}),'approved-project-gallery.html');status('Website gallery exported. Publishing and revoking exported copies are manual.');},'Export gallery');}
  async function contactRender(el,p,generation){try{const c=await S.contact(p);if(el._generation!==generation)return;const target=el.querySelector('.ops-contact');target.innerHTML=c?`<h3>${esc(c.name)}</h3><p>${esc(p.address||'Address pending')}</p><p>${esc(c.phone||'Phone pending')}<br>${esc(c.email||'Email pending')}</p>${c.phone?`<a href="tel:${esc(c.phone.replace(/[^+\d]/g,''))}">Call client</a>`:''} ${c.email?`<a href="mailto:${esc(c.email)}">Email client</a>`:''}`:'Contact not available.';}catch(e){if(el._generation===generation)el.querySelector('.ops-contact').textContent=e.message;}}
  const pipeline=OpsPipelineUI({S,D,esc,button,input,options,dialog,status,refresh});
  const ledger=OpsProjectLedger({S,D,esc,button,input,area,options,dialog,status});
  const photoWorkspace=OpsPhotoWorkspace({S,esc,dialog,input,options,button,status,projectId:()=>selected});
  function render(el){
    const identityKey=S.mode+':'+(S.user?.id||'');
    if(el._draftIdentity!==identityKey){el._drafts=new Map();el._sections=new Map();el._draftIdentity=identityKey;}
    for(const f of el.querySelectorAll('form[data-record-form]')){const key=f.dataset.recordId+':'+f.dataset.formKey;if(f.dataset.dirty)el._drafts.set(key,{id:f.dataset.recordId,key:f.dataset.formKey,values:Object.fromEntries(new FormData(f))});else el._drafts.delete(key);}
    for(const d of el.querySelectorAll('[data-section-key]'))el._sections.set(d.dataset.sectionKey,d.open);
    const drafts=[...el._drafts.values()];
    const focused=el.contains(document.activeElement)?document.activeElement:null;
    const focusForm=focused?.closest('[data-record-form]'),focusState=focusForm?{id:focusForm.dataset.recordId,key:focusForm.dataset.formKey,name:focused.name,start:focused.selectionStart,end:focused.selectionEnd}:null;
    const scroll=el.scrollTop;
    const identity=S.mode+':'+(S.user?.id||'');
    if(el._photoIdentity!==identity){photoWorkspace.dispose(el);el._photoIdentity=identity;document.querySelectorAll('.ops-lightbox').forEach(d=>d.close());}
    renderContent(el);
    if(el.dataset.opsType==='opsApps')el.querySelectorAll('.ops-launch-tile small').forEach(s=>{if(s.textContent==='Integration pending'){s.className='ops-pending-label';s.textContent='Coming later';}else s.remove();});
    refineRecords(el);
    hydrateDetailPhotos(el);
    if(el.dataset.opsType==='opsClients'){const records=[...el.querySelectorAll('.ops-record-accordion')];for(const c of orderedClients()){const record=records.find(r=>r.querySelector('summary').dataset.clientExpand===c.id);if(record)el.append(record);}}
    if(el.dataset.opsType==='opsLeads')el.querySelectorAll('.ops-pipeline>section').forEach((section,i)=>{section.dataset.leadStage=['lead','walkthrough','estimating','review','active','complete'][i];section.querySelectorAll('[data-action=openProject]').forEach(b=>{b.dataset.leadDrag=b.dataset.id;b.title='Drag to a stage, or open project';b.insertAdjacentHTML('afterbegin','<span class="ops-four-dots" aria-hidden="true"></span>');});});
    if(el.dataset.opsType==='opsClients')for(const record of el.querySelectorAll('.ops-record-accordion')){const summary=record.querySelector('summary'),id=summary.dataset.clientExpand,c=S.data.clients.find(c=>c.id===id),addresses=clientAddresses(c);record.dataset.clientRecord=id;record.classList.add('ops-client-directory-row');summary.innerHTML=`<button type="button" data-client-grab="${esc(id)}" aria-label="Reorder client; drag or use arrow keys"><span class="ops-four-dots" aria-hidden="true"></span></button><strong>${esc(c.name)}</strong><span class="ops-directory-contact">${esc(c.phone||'No phone')}<small>${esc(c.email||'No email')}</small></span><span class="ops-directory-address">${esc(addresses[0]||'No address')}${addresses.length>1?`<small>+ ${addresses.length-1} other address${addresses.length>2?'es':''}</small>`:''}</span><div class="ops-directory-actions">${button(record.open?'Close':'Open','toggleClient',id)}${button('✎ Edit','focusClient',id)}</div>`;}

    if(['opsProjects','opsProjectWorkspace'].includes(el.dataset.opsType)){
      let slot=0;for(const record of el.querySelectorAll('.ops-record-accordion')){const summary=record.querySelector('[data-project-expand]');if(!summary)continue;const id=summary.dataset.projectExpand,p=S.data.projects.find(p=>p.id===id);if(!record.querySelector('.ops-project-metrics'))summary.insertAdjacentHTML('beforeend',ledger.metrics(id));if(!['complete','archived'].includes(p.status)){slot++;record.dataset.queueProject=id;const wrap=document.createElement('div');wrap.className='ops-project-slot-row';wrap.dataset.queueProject=id;record.before(wrap);wrap.innerHTML=`<div class="ops-project-slot"><strong>${slot}</strong><button type="button" data-project-grab="${id}" aria-label="Reorder project; drag or use arrow keys" title="Drag to reorder"><span class="ops-four-dots" aria-hidden="true"></span></button></div>`;wrap.append(record);}const body=record.querySelector('.ops-record-detail');if(body&&!body.classList.contains('ops-command')&&!body.querySelector('.ops-project-ledger'))body.insertAdjacentHTML('afterbegin',ledger.details(id));}
    }
    if(['opsProjects','opsProjectWorkspace'].includes(el.dataset.opsType)){const list=document.createElement('section');list.className='ops-project-list-window';list.setAttribute('aria-label','Project queue');const entries=[...el.children].filter(c=>c.matches('.ops-project-slot-row,.ops-record-accordion'));if(entries.length){entries[0].before(list);entries.forEach(c=>list.append(c));}}
    if(flows[el.dataset.opsType]){const tools=el.querySelector(':scope > .ops-step-tools');if(tools){tools.classList.add('ops-section-header');tools.querySelector('span').textContent=labels[el._child.dataset.opsType];}const child=el._child;if(child){child.classList.add('ops-attached-section');if(flows[child.dataset.opsType])child.classList.add('ops-attached-menu');else child.querySelector(':scope > .ops-heading h2')?.setAttribute('hidden','');}}
    if(el.dataset.opsType==='opsApps')el.querySelectorAll('.ops-pending-label').forEach(s=>{s.closest('button').title='Connection pending';s.remove();});
    for(const draft of drafts){const f=el.querySelector(`form[data-record-id="${draft.id}"][data-form-key="${draft.key}"]`);if(f){for(const [name,value] of Object.entries(draft.values))if(f.elements.namedItem(name))f.elements.namedItem(name).value=value;f.dataset.dirty='true';}}
    for(const d of el.querySelectorAll('[data-section-key]'))if(el._sections.has(d.dataset.sectionKey))d.open=el._sections.get(d.dataset.sectionKey);
    el.scrollTop=scroll;
    if(focusState){const f=[...el.querySelectorAll('form[data-record-form]')].find(f=>f.dataset.recordId===focusState.id&&f.dataset.formKey===focusState.key),control=f?.elements.namedItem(focusState.name);if(control){control.focus({preventScroll:true});if(focusState.start!=null&&control.setSelectionRange)try{control.setSelectionRange(focusState.start,focusState.end);}catch{}}}
    syncStickyMenus(el);
    const sections={opsClients:['.ops-records','Client directory'],opsProjects:['.ops-records','Projects'],opsNotes:['.ops-records','Walkthrough notes'],opsCrew:['.ops-records','Assigned crew'],opsEstimate:['table','Scope items'],opsReview:['ol','Review checkpoints']};
    const entry=sections[el.dataset.opsType];if(entry){const target=el.querySelector(entry[0]);if(target&&!target.previousElementSibling?.classList.contains('ops-section-title')){const h=document.createElement('h3');h.className='ops-section-title';h.textContent=entry[1];target.before(h);}}
  }
  // Detail views are projections of canonical records; no additional business store.
  const isPast=p=>['complete','archived'].includes(p.status);
  const related=(table,jobs)=>S.data[table].filter(r=>jobs.some(p=>p.id===r.project_id));
  const quiet=text=>`<p class="ops-muted">${esc(text)}</p>`;
  const disclosure=(key,title,body,open=false)=>`<details class="ops-work-section" data-section-key="${esc(key)}" ${open?'open':''}><summary>${esc(title)}</summary><div class="ops-section-content">${body}</div></details>`;
  const recordForm=(table,id,key,fields)=>`<form data-record-form="${table}" data-record-id="${esc(id)}" data-form-key="${esc(key)}"><div class="ops-form-grid">${fields}</div><p class="ops-form-error" role="alert"></p><div class="ops-save-bar"><span>Changes save to this record</span><button type="submit">Save changes</button></div></form>`;
  const contactLinks=c=>(c?.phone?`<a href="tel:${esc(c.phone.replace(/[^+\d]/g,''))}">Call</a>`:'')+(c?.email?`<a href="mailto:${esc(c.email)}">Email</a>`:'');
  function nextForm(p){return recordForm('project',p.id,'next',input('next_action','Next action',p.next_action)+input('next_action_due','Due',p.next_action_due,'date'));}
  function fieldRows(items){return items.map(x=>`<article class="ops-work-item" data-project-context-id="${esc(x.project_id)}"><label class="ops-check"><input type="checkbox" data-complete="${esc(x.id)}" ${x.status==='done'?'checked':''}><strong>${esc(x.title)}</strong></label><span class="ops-item-meta">${esc(x.status)}${x.due_date?' · Due '+esc(x.due_date):''}</span>${x.kind==='document'&&/^https:\/\//.test(x.details||'')?`<a href="${esc(x.details)}" target="_blank" rel="noopener noreferrer">Open document ↗</a>`:`<p class="ops-pre">${esc(x.details)}</p>`}${disclosure('edit-'+x.id,'Edit item',recordForm('field',x.id,'item',input('title','Item',x.title,'text',true)+input('due_date','Due',x.due_date,'date')+area('details',x.kind==='document'?'HTTPS document link':'Details / dependencies',x.details)))}</article>`).join('');}
  function notesView(jobs){const notes=related('walkthroughs',jobs).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));return notes.map(n=>`<article class="ops-work-item" data-project-context-id="${esc(n.project_id)}"><small>${esc(jobs.find(p=>p.id===n.project_id)?.name)} · ${esc(n.created_at?.slice(0,10)||'Date not recorded')}</small><p class="ops-pre">${esc(n.notes)}</p>${disclosure('note-'+n.id,'Edit note',recordForm('note',n.id,'note',area('notes','Note',n.notes)))}</article>`).join('')||quiet('No notes recorded. Add observations, conversations, and decisions to the relevant project.');}
  function activityView(jobs){const events=[...related('walkthroughs',jobs).map(n=>({date:n.created_at,text:'Note recorded',id:n.project_id})),...related('estimates',jobs).map(e=>({date:e.created_at,text:`Estimate v${e.version} · ${e.status.replaceAll('_',' ')}`,id:e.project_id})),...related('payments',jobs).map(p=>({date:p.date,text:`Payment recorded · ${D.display(p.amount_cents)}`,id:p.project_id})),...related('photos',jobs).filter(p=>!p.deleted_at).map(p=>({date:p.created_at,text:'Photo added · '+(p.name||'Photo'),id:p.project_id}))].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));return events.slice(0,12).map(e=>`<div class="ops-activity-row"><time>${esc(e.date?.slice(0,10)||'Undated')}</time><div><strong>${esc(e.text)}</strong><small>${esc(jobs.find(p=>p.id===e.id)?.name)}</small></div></div>`).join('')||quiet('No recorded activity yet.');}
  const clientAddresses=c=>[...new Set(S.data.projects.filter(p=>p.client_id===c.id).map(p=>p.address?.trim()).filter(Boolean))];
  const navigationLink=address=>/iPhone|iPad|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)?'https://maps.apple.com/?daddr='+encodeURIComponent(address)+'&dirflg=d':'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(address)+'&dir_action=navigate';
  const mapLinks=address=>address?`<a href="${esc(navigationLink(address))}" target="_blank" rel="noopener noreferrer">Navigate ↗</a><a href="https://www.google.com/maps/search/?api=1&amp;query=${encodeURIComponent(address)}" target="_blank" rel="noopener noreferrer" title="Open this property in Maps, then choose Street View where available">Maps / Street View ↗</a>`:'';
  function clientStageLabel(p){
    if(p.status==='archived')return 'Archived project';
    if(p.status==='complete')return 'Project complete';
    if(p.status==='active')return '6 · Create Project — active';
    const latest=S.data.estimates.filter(e=>e.project_id===p.id).sort((a,b)=>b.version-a.version)[0];
    if(latest?.status==='client_ready')return '4 · Finalize & Send Estimate — finalized; sending unconfirmed';
    if(latest&&latest.status!=='draft')return '4 · Finalize & Send Estimate — in review';
    if(latest||p.status==='estimating')return '3 · Create Estimate';
    if(S.data.walkthroughs.some(n=>n.project_id===p.id))return '3 · Create Estimate — walkthrough recorded';
    if(p.next_action_due&&p.next_action==='Walkthrough scheduled')return '2 · Schedule Walkthrough — '+p.next_action_due;
    return '2 · Schedule Walkthrough — lead captured';
  }
  function contactFile(c){
    const v=value=>String(value||'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
    const lines=['BEGIN:VCARD','VERSION:3.0','FN:'+v(c.name),'N:'+v(c.name)+';;;;',...(c.phone?['TEL;TYPE=VOICE:'+v(c.phone)]:[]),...(c.email?['EMAIL;TYPE=INTERNET:'+v(c.email)]:[]),...clientAddresses(c).map(a=>'ADR;TYPE=OTHER:;;'+v(a)+';;;;'),'END:VCARD'];
    return new File([lines.join('\r\n')+'\r\n'],(c.name||'Contact').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_')+'.vcf',{type:'text/vcard;charset=utf-8'});
  }
  async function shareContact(id){const c=S.data.clients.find(c=>c.id===id);if(!c)throw new Error('Client unavailable.');const file=contactFile(c);try{if(navigator.share){if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:c.name});else await navigator.share({title:c.name,text:[c.name,...clientAddresses(c),c.phone,c.email].filter(Boolean).join('\n')});}else{download(file,file.name);status('Contact downloaded. Open it to save or share from your contacts app.');}}catch(e){if(e.name!=='AbortError')throw e;}}
  function photoStrip(id){const photos=S.data.photos.filter(x=>x.project_id===id&&!x.deleted_at).slice(0,3);return photos.length?`<div class="ops-client-photo-strip">${photos.map(p=>`<button type="button" data-action="projectPhotos" data-id="${esc(id)}" aria-label="Open project photos"><img data-project-thumbnail="${esc(p.id)}" alt="${esc(p.caption||p.name||'Project photo')}"><small>${esc(p.stage)}</small></button>`).join('')}</div>`:quiet('No project photos yet.');}
  function hydrateDetailPhotos(el){const generation=el._generation;for(const img of el.querySelectorAll('[data-project-thumbnail]')){if(img.closest('.ops-root')!==el)continue;const p=S.data.photos.find(p=>p.id===img.dataset.projectThumbnail);if(!p)continue;S.thumbnail(p).then(url=>{if(!img.isConnected||el._generation!==generation){if(url.startsWith('blob:'))URL.revokeObjectURL(url);return;}el._urls.push(url);img.src=url;}).catch(()=>{if(img.isConnected)img.alt='Photo unavailable — open gallery to retry';});}}
  function projectPhotoUpload(id){
    const p=S.data.projects.find(p=>p.id===id);if(!p)throw new Error('Choose a project.');const uploaded=new Map(),done=new Set();
    const el=dialog('Add photos · '+p.name,`<p>Saved directly to <strong>${esc(p.name)}</strong>.</p><label>Project stage<select name="stage">${options([['before','Walkthrough / before'],['during','Active work / during'],['after','Completed / after']],p.status==='active'?'during':p.status==='complete'?'after':'before')}</select></label><label>Choose photos<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><label>Take a photo<input name="camera" type="file" accept="image/*" capture="environment"></label><p class="ops-muted">JPEG, PNG, WebP · up to 20 MB each. Convert HEIC to JPEG first.</p>`,async f=>{
      const files=[...el.querySelector('[name=photos]').files,...el.querySelector('[name=camera]').files];if(!files.length)throw new Error('Choose photos or take a photo first.');
      for(const file of files){if(done.has(file))continue;let photo=uploaded.get(file);if(!photo){photo=await S.upload(id,file);uploaded.set(file,photo);}await S.save('photos',{...S.data.photos.find(x=>x.id===photo.id),stage:f.stage});done.add(file);}
    },'Save project photos');
  }

  function clientDetail(c){
    const jobs=S.data.projects.filter(p=>p.client_id===c.id),active=jobs.filter(p=>!isPast(p)),past=jobs.filter(isPast),addresses=clientAddresses(c);
    const jobCards=list=>list.map(p=>`<article class="ops-client-job" data-project-context-id="${esc(p.id)}">${button(esc(p.name)+' ↗','openProject',p.id)}<p class="ops-client-stage">${esc(clientStageLabel(p))}</p><p>${esc(p.address||'Address not recorded')}</p><div class="ops-contact-actions">${button('Upload photos','projectUpload',p.id)}${button('View photos','projectPhotos',p.id)}${button('Process','clientProcess',c.id)}</div>${disclosure(p.id+'-client-next','Next action',nextForm(p))}</article>`).join('')||quiet('No projects in this group.');
    const contact=recordForm('client',c.id,'contact',input('name','Client name',c.name,'text',true)+input('phone','Phone',c.phone,'tel')+input('email','Email',c.email,'email'));
    const addressRows=addresses.map(a=>`<div class="ops-client-address"><a class="ops-address-link" href="${esc(navigationLink(a))}" target="_blank" rel="noopener noreferrer" aria-label="Navigate to ${esc(a)}">${esc(a)} ↗</a><small>${esc(jobs.filter(p=>p.address?.trim()===a).map(p=>p.name).join(' · '))}</small><div class="ops-contact-actions">${mapLinks(a)}</div></div>`).join('');
    return `<div class="ops-record-detail ops-command ops-client-window"><div class="ops-client-primary">${contact}<div class="ops-contact-actions">${contactLinks(c)}${button('Save to phone','saveContact',c.id)}${button('Share contact','shareContact',c.id)}</div></div><section class="ops-client-level" data-client-level="address"><h3>Address</h3>${addressRows||quiet('No address recorded yet. Add an address to the relevant project.')}${disclosure(c.id+'-addresses','Edit project addresses',jobs.map(p=>`<div><strong>${esc(p.name)}</strong>${recordForm('project',p.id,'address',input('address','Project address',p.address))}</div>`).join('')||quiet('Create a project to add its property address.'))}</section><section class="ops-client-level" data-client-level="projects"><div class="ops-heading"><h3>Projects <small>${jobs.length}</small></h3>${button('New project','clientProject',c.id)}</div>${jobCards(active)}${past.length?disclosure(c.id+'-past',`Past projects · ${past.length}`,jobCards(past)):''}</section><section class="ops-client-level" data-client-level="photos"><h3>Photos</h3>${jobs.map(p=>`<article class="ops-client-project-photos"><strong>${esc(p.name)}</strong><small>${p.status==='active'?'Active project':'Walkthrough / project photos'}</small>${photoStrip(p.id)}<div class="ops-contact-actions">${button('Upload / take photos','projectUpload',p.id)}${button('Open gallery','projectPhotos',p.id)}</div></article>`).join('')||quiet('Add a project to organize its photos.')}</section><details class="ops-work-section" data-section-key="${c.id}-additional"><summary>Additional information</summary><div class="ops-command-columns"><div>${disclosure(c.id+'-notes','Notes & communications',jobs.length?`<label>Record a note on<select data-client-note-project><option value="">Choose project…</option>${options(jobs.map(p=>[p.id,p.name]))}</select></label>${button('Add note / conversation','clientNote',c.id)}`+notesView(jobs):quiet('Add a project to record its notes.'))}${disclosure(c.id+'-activity','Recent activity',activityView(jobs))}</div><div>${disclosure(c.id+'-finance','Financial context',jobs.map(p=>`<div class="ops-work-item"><strong>${esc(p.name)}</strong>${ledger.metrics(p.id)}</div>`).join('')+quiet('Project ledger totals. Shared individual payments and the finance bridge remain pending.')+button('Open Financial Dashboard','hubFinancials'))}${disclosure(c.id+'-documents','Documents',fieldRows(related('field_items',jobs).filter(x=>x.kind==='document'))||quiet('No linked project documents.'))}</div></div></details></div>`;
  }
  function syncStickyMenus(el){
    if(!roots.has(el)){const owner=[...roots].find(root=>root.contains(el));if(!owner)return;el=owner;}
    const menus=[...el.querySelectorAll('.ops-main-menu,.ops-root>.ops-steps')].filter(n=>!n.closest('.ops-main-menu')||n.classList.contains('ops-main-menu'));
    const update=()=>{for(const menu of menus){let top=0,depth=0;for(let parent=menu.parentElement?.closest('.ops-root');parent&&el.contains(parent);parent=parent.parentElement?.closest('.ops-root')){const own=parent.querySelector(':scope > .ops-main-menu,:scope > .ops-steps');if(own&&own!==menu&&!own.contains(menu)){top+=own.getBoundingClientRect().height;depth++;}}menu.style.setProperty('--ops-nav-top',top+'px');menu.style.setProperty('--ops-nav-layer',String(30-depth));}};
    el._menuObserver?.disconnect();el._menuObserver=new ResizeObserver(update);menus.forEach(n=>el._menuObserver.observe(n));update();
  }

  function refineLegacyProjects(el){
    if(!['opsProjects','opsProjectWorkspace','opsClients'].includes(el.dataset.opsType))return;
    for(const detail of el.querySelectorAll('.ops-record-accordion')){
      const summary=detail.querySelector('summary');summary.setAttribute('aria-expanded',String(detail.open));
      const isProject=!!summary.dataset.projectExpand,id=summary.dataset.projectExpand||summary.dataset.clientExpand;
      const jobs=isProject?S.data.projects.filter(p=>p.id===id):S.data.projects.filter(p=>p.client_id===id);
      const client=S.data.clients.find(c=>c.id===(isProject?jobs[0]?.client_id:id));
      summary.querySelector('span').textContent=isProject?[client?.name,jobs[0]?.status,jobs[0]?.next_action||'Next action not set'].filter(Boolean).join(' · '):[client?.phone||'Phone not added',`${jobs.length} project${jobs.length===1?'':'s'}`].join(' · ');
      if(!detail.open)continue;
      const body=document.createElement('div');body.className='ops-record-detail';if(isProject)body.dataset.projectContextId=id;
      while(summary.nextSibling)body.append(summary.nextSibling);detail.append(body);
      const form=body.querySelector('form');if(form)body.append(form);
      const contactLinks=(client?.phone?`<a href="tel:${esc(client.phone.replace(/[^+\d]/g,''))}">Call ${esc(client.name)}</a>`:'')+(client?.email?`<a href="mailto:${esc(client.email)}">Email</a>`:'');
      const overview=document.createElement('section');overview.className='ops-record-overview';
      const entries=S.data.pipeline_entries.filter(e=>jobs.some(p=>p.id===e.project_id)),totalKnown=entries.length&&entries.every(e=>e.project_total!=null);
      const due=totalKnown?D.display(entries.reduce((sum,e)=>sum+ledger.totals(e.project_id).total-ledger.totals(e.project_id).received,0)):null;
      overview.innerHTML=`<h3>${isProject?'Job at a glance':'Client at a glance'}</h3><div class="ops-contact-actions">${contactLinks||'<span class="ops-muted">Add a phone or email to make contact easier.</span>'}</div>${jobs.map(p=>`<div class="ops-job-brief"><strong>${esc(p.name)}</strong><span>${esc(p.address||'Property address not added')}</span><span><b>Next:</b> ${esc(p.next_action||'Not set')}${p.next_action_due?' · Due '+esc(p.next_action_due):''}</span><span><b>Status:</b> ${esc(p.status)} · ${S.data.photos.filter(x=>x.project_id===p.id&&!x.deleted_at).length} photos · ${S.data.estimates.filter(x=>x.project_id===p.id).length} estimate versions</span></div>`).join('')||'<p>No project history yet.</p>'}${entries.length?`<p class="ops-muted">Approved-project balance: ${due||'Total not recorded'} · manually recorded, not bank-synced</p>`:''}`;
      body.prepend(overview);
      for(const row of body.querySelectorAll('.ops-field-row')){const item=S.data.field_items.find(i=>i.id===row.querySelector('[data-action="editField"]')?.dataset.id);if(item?.due_date)row.insertAdjacentHTML('beforeend',`<p class="ops-muted">Due ${esc(item.due_date)}</p>`);if(item?.kind==='document'&&/^https:\/\/\S+$/.test(item.details||''))row.insertAdjacentHTML('beforeend',`<a href="${esc(item.details)}" target="_blank" rel="noopener noreferrer">Open document</a>`);}
      if(isProject){const latest=S.data.estimates.filter(e=>e.project_id===id).sort((a,b)=>b.version-a.version)[0];if(latest)overview.insertAdjacentHTML('beforeend',`<p><strong>Latest estimate:</strong> Version ${esc(latest.version)} · ${esc(latest.status.replaceAll('_',' '))}</p>`);}
      if(isProject&&form){const grid=form.querySelector('.ops-form-grid');grid.insertAdjacentHTML('beforeend',input('next_action_due','Next action due',jobs[0].next_action_due,'date'));}
      const rows=[...body.querySelectorAll('.ops-field-row')];if(rows.length){const anchor=document.createComment('field groups');rows[0].before(anchor);for(const kind of ['material','punch','tool','supply','timeline','document']){const matching=rows.filter(r=>r.querySelector('small')?.textContent.startsWith(kind+' · '));if(!matching.length)continue;const section=document.createElement('section');section.className='ops-field-group';section.innerHTML=`<h4>${{material:'Materials',punch:'Punch list',tool:'Tools',supply:'Supplies',timeline:'Timeline',document:'Documents'}[kind]}</h4>`;anchor.before(section);matching.forEach(r=>section.append(r));}anchor.remove();}
    }
    if(!S.data[el.dataset.opsType==='opsClients'?'clients':'projects'].length)el.insertAdjacentHTML('beforeend','<p class="ops-empty">No records yet. Use the add action above to get started.</p>');
  }
  function refineRecords(el){
    if(['opsProjects','opsProjectWorkspace'].includes(el.dataset.opsType)){refineLegacyProjects(el);el.querySelectorAll('form[data-record-form]').forEach(f=>f.dataset.formKey='identity');for(const body of el.querySelectorAll('.ops-record-detail')){const p=S.data.projects.find(p=>p.id===body.dataset.projectContextId);if(p?.client_id)body.insertAdjacentHTML('afterbegin',button('← Back to client','openClient',p.client_id));}return;}
    if(!['opsProjects','opsProjectWorkspace','opsClients'].includes(el.dataset.opsType))return;
    for(const detail of el.querySelectorAll('.ops-record-accordion')){const summary=detail.querySelector('summary'),id=summary.dataset.projectExpand||summary.dataset.clientExpand;summary.setAttribute('aria-expanded',String(detail.open));if(!detail.open)continue;while(summary.nextSibling)summary.nextSibling.remove();detail.insertAdjacentHTML('beforeend',summary.dataset.projectExpand?projectDetail(S.data.projects.find(p=>p.id===id)):clientDetail(S.data.clients.find(c=>c.id===id)));}
    if(!S.data[el.dataset.opsType==='opsClients'?'clients':'projects'].length)el.insertAdjacentHTML('beforeend',quiet('No records yet. Use the add action above to get started.'));
  }

  function renderContent(el){
    if(flows[el.dataset.opsType]){
      remember(el);
      const isCenter=el.dataset.opsType==='opsCRM',steps=flows[el.dataset.opsType],index=Math.max(0,Math.min(el._step??(isCenter?1:el.dataset.opsType==='opsEstimates'&&(OpsSources.pendingNote||OpsSources.pendingError)?1:0),steps.length-1)),type=steps[index];
      el._step=index;
      if(el._child?.dataset.opsType===type&&el._renderIdentity===S.mode+':'+(S.user?.id||'')&&el._renderProject===selected){render(el._child);return;}
      el._renderIdentity=S.mode+':'+(S.user?.id||'');el._renderProject=selected;
      dispose(el._child);
      el.innerHTML=`${isCenter?'<div class="ops-heading"><h2>Business Center</h2><span>One project. Everything connected.</span></div>':''}<nav class="ops-steps" aria-label="${isCenter?'Business Center sections':'App steps'}">${steps.map((t,i)=>`<button type="button" data-step="${i}" ${i===index?'aria-current="step"':''}>${isCenter?'':i+1+'. '}${esc(labels[t])}</button>`).join('')}</nav><div class="ops-step-tools"><span>${isCenter?'Workspace':`Step ${index+1} of ${steps.length}`}</span><button type="button" data-popout="${type}">Pop out this section ↗</button></div><div class="ops-step-body"></div>${isCenter?'':`<footer class="ops-step-footer"><button type="button" data-step="${index-1}" ${index===0?'disabled':''}>← Back</button><button type="button" data-step="${index+1}" ${index===steps.length-1?'disabled':''}>Next →</button></footer>`}`;
      if(isCenter){el.querySelector('.ops-heading').remove();el.classList.add('ops-business-center');}
      const popout=el.querySelector('.ops-step-tools [data-popout]');popout.textContent='↗';popout.title='Open this section in its own window';popout.setAttribute('aria-label','Pop out this section');
      el.querySelectorAll('.ops-steps button').forEach((b,i)=>b.insertAdjacentHTML('afterbegin',OpsIcon(steps[i])));
      if(isCenter){const nav=el.querySelector('.ops-steps');const bar=document.createElement('div');bar.className='ops-main-menu';nav.before(bar);bar.append(nav);bar.insertAdjacentHTML('beforeend',`<button type="button" class="ops-crew-login" data-action="crewLogin">${OpsIcon('opsCrew')}<span>Crew Login</span></button>`);}
      if(isCenter){el.querySelector('.ops-crew-login').setAttribute('aria-label','Crew Login');el.querySelector('.ops-crew-login').title='Crew Login';}
      if(el.dataset.opsType==='opsPhotoCenter'){el.classList.add('ops-processing');el.querySelector('.ops-step-footer')?.remove();el.querySelectorAll('.ops-steps button').forEach((b,i)=>{b.innerHTML=OpsIcon(steps[i])+esc(i===0?'Inbox':labels[steps[i]]);});el.querySelector('.ops-step-tools>span').textContent=labels[type];}
      if(el.dataset.opsType==='opsProcessing'){el.classList.add('ops-processing');el.querySelector('.ops-step-footer')?.remove();el.querySelector('.ops-steps').setAttribute('aria-label','Client Processing sections');el.querySelectorAll('.ops-steps button').forEach((b,i)=>{b.innerHTML=OpsIcon(steps[i])+esc(steps[i]==='opsLeads'?'Leads':labels[steps[i]]);});el.querySelector('.ops-step-tools>span').textContent='Client Processing / '+labels[type];}
      if(isCenter)el.querySelector('.ops-step-tools>span').textContent=labels[type];
      const nav=el.querySelector('.ops-steps');requestAnimationFrame(()=>{const active=nav.querySelector('[aria-current]');if(active&&nav.scrollWidth>nav.clientWidth)nav.scrollLeft=Math.max(0,active.offsetLeft-nav.offsetLeft-16);});
      const child=el.querySelector('.ops-step-body');child.dataset.opsType=type;child.classList.add('ops-root');child._step=el._memory?.[type]?.step;child._memory=el._memory?.[type]?.memory;el._child=child;render(child);return;
    }
    const type=el.dataset.opsType,p=project(),gen=(el._generation||0)+1;el._generation=gen;el._urls?.forEach(URL.revokeObjectURL);el._urls=[];
    const head=`<div class="ops-heading"><h2>${labels[type]}</h2><span>${esc(p?.name||'Choose a project')}</span></div>`+(p&&['opsProjects','opsContact'].includes(type)?`<p><strong>Next action:</strong> ${esc(p.next_action||'Schedule walkthrough')}${p.next_action_due?' · '+esc(p.next_action_due):''}</p>`:'');
    if(type==='opsApps'){const groups=widgetGroups.map(([title,types])=>[title,types.filter(t=>t!=='opsApps')]);el.innerHTML=`<div class="ops-heading"><h2>Apps Launcher</h2></div>${groups.map(([title,types])=>`${title==='Launcher'?'':'<h3>'+title+'</h3>'}<div class="ops-launch-grid">${types.map(t=>`<button type="button" class="ops-launch-tile" data-action="launchWidget" data-id="${t}"><span class="ops-launch-icon">${OpsIcon(t)}</span><strong>${esc(labels[t])}</strong><small>${['opsInvoices','opsTimesheet','opsFinancials','opsCalendar'].includes(t)?'Integration pending':'Open widget ↗'}</small></button>`).join('')}</div>`).join('')}`;return;}
    if(S.mode==='signed-out'){el.innerHTML=head+'<p>Sign in to load your shared projects, or try the local demo.</p>'+button('Open workspace','account');return;}
    if(['opsPhotos','opsGallery','opsAlbums','opsTrash','opsPublish'].includes(type)){photoWorkspace.render(el);return;}
    if(type==='opsProjectWorkspace'||type==='opsProjects'){
      el.innerHTML='<div class="ops-heading"><h2>Projects</h2>'+button('＋ New project','newProject')+'</div>'+ledger.ordered().map(x=>{const c=S.data.clients.find(c=>c.id===x.client_id),open=expandedProject===x.id;return `<details class="ops-record-accordion" ${open?'open':''}><summary data-project-expand="${x.id}"><strong>${esc(x.name)}</strong><span>${esc(c?.name||'Client pending')} · ${esc(x.status)}</span></summary>${open?`<form data-record-form="project" data-record-id="${x.id}"><h3>Project details</h3><div class="ops-form-grid">${input('name','Project name',x.name,'text',true)}${input('address','Property address',x.address)}<label>Status<select name="status">${options(['lead','walkthrough','estimating','review','active','complete','archived'].map(s=>[s,s]),x.status)}</select></label>${input('next_action','Next action',x.next_action)}</div><p role="alert" class="ops-form-error"></p><button type="submit">Save project</button></form><h3>Client & contact</h3><p>${esc(c?.name||'Contact unavailable')} · ${esc(c?.phone||'No phone')} · ${esc(c?.email||'No email')}</p>${button('Edit contact','editClient',c?.id||'')}${button('Team access','team')}<h3>Walkthrough notes</h3>${S.data.walkthroughs.filter(n=>n.project_id===x.id).map(n=>`<p class="ops-pre">${esc(n.notes)}</p>`).join('')||'<p class="ops-muted">No notes yet.</p>'}${button('＋ Add note','newNote')}<h3>Field plan</h3>${S.data.field_items.filter(i=>i.project_id===x.id).map(i=>`<div class="ops-field-row"><strong>${esc(i.title)}</strong><small>${esc(i.kind)} · ${esc(i.status)}</small><p>${esc(i.details)}</p>${button('Edit','editField',i.id)}</div>`).join('')||'<p class="ops-muted">No materials, punch items, or dates added yet.</p>'}${button('＋ Add field item','field')}`:''}</details>`;}).join('');return;
    }
    if(type==='opsClients'){
      const opened=S.data.clients.find(c=>c.id===expandedClient);el.classList.toggle('ops-client-detail-view',!!opened);
      el.innerHTML='<div class="ops-heading">'+(opened?button('← All clients','clientDirectory'):'<h2>Clients</h2>'+button('＋ Add client','newClient'))+'</div>'+(opened?[opened]:S.data.clients).map(c=>`<details class="ops-record-accordion" ${opened?'open':''}><summary data-client-expand="${esc(c.id)}"><strong>${esc(c.name)}</strong><span>${S.data.projects.filter(p=>p.client_id===c.id).length} projects</span></summary></details>`).join('');return;
    }
    if(type==='opsPipeline'){pipeline.render(el);return;}
    if(type==='opsChangeOrders'){ledger.render(el);return;}
    if(type==='opsPayments'||type==='opsReceipts'){ledger.renderPayments(el,type==='opsReceipts');return;}
    if(type==='opsCalendar'){el.innerHTML='<div class="ops-heading"><h2>Calendar</h2></div><p class="ops-muted">Hub calendar connection pending.</p>';return;}
    if(type==='opsFinancials'){el.innerHTML='<div class="ops-heading"><h2>Financials</h2></div>'+button('Open Financial Dashboard','hubFinancials')+'<p class="ops-muted">Opens the existing Hub dashboard. Business Center estimates and payments are not automatically reconciled with its financial records.</p>';return;}
    if(type==='opsLeads'){
      const stages=['lead','walkthrough','estimating','review','active','complete'];
      el.innerHTML=head+button('New project','newProject')+`<div class="ops-pipeline">${stages.map(stage=>{const jobs=S.data.projects.filter(x=>x.status===stage&&!S.data.pipeline_entries.some(e=>e.project_id===x.id));return `<section><h3>${esc(stage[0].toUpperCase()+stage.slice(1))} <small>${jobs.length}</small></h3>${jobs.map(x=>`<button class="ops-project" data-action="openProject" data-id="${x.id}"><strong>${esc(x.name)}</strong><span>${esc(S.data.clients.find(c=>c.id===x.client_id)?.name||'Assigned project')}</span><small>${esc(x.next_action||'Choose next action')}${x.next_action_due?' · '+esc(x.next_action_due):''}</small></button>`).join('')||'<p class="ops-muted">No projects here yet.</p>'}</section>`;}).join('')}</div>`;return;
    }
    if(type==='opsClients'){el.innerHTML=head+button('Add client','newClient')+`<div class="ops-records">${S.data.clients.map(c=>`<article><h3>${esc(c.name)}</h3><p>${esc(c.phone||'No phone yet')} · ${esc(c.email||'No email yet')}</p>${button('Edit client','editClient',c.id)}${S.data.projects.filter(x=>x.client_id===c.id).map(x=>button(esc(x.name),'openProject',x.id)).join('')}</article>`).join('')||'<p>Add a client before their first project, or create both together from Projects.</p>'}</div>`;return;}
    if(['opsInvoices','opsTimesheet','opsFinancials'].includes(type)){const copy={opsInvoices:'Invoice creation is not connected yet. Reviewed estimates remain in Estimates; no invoice is created or sent automatically.',opsTimesheet:'Time tracking is not connected yet. Crew assignments and project work plans are available under Crew.',opsFinancials:'The existing Financial Dashboard remains the financial authority. Its integration is pending; estimate subtotals are not booked revenue or collected payments.'};el.innerHTML=head+`<div class="ops-empty"><h3>Integration pending</h3><p>${copy[type]}</p><p class="ops-muted">This section does not create a separate data set.</p></div>`;return;}
    if(type==='opsCrew'){el.innerHTML=head+(p?button('Assign employee access','team')+`<div class="ops-records">${S.data.project_members.filter(x=>x.project_id===selected).map(x=>`<article><strong>${esc(x.email||x.user_id||'Assigned employee')}</strong><p>${esc(x.role)}</p></article>`).join('')||'<p>No employee assignments recorded for this project.</p>'}</div>`:'<p>Choose a project to manage its crew.</p>')+button('Open project & field plan','openProject',selected||'');return;}
    if(type==='opsProjects'){el.innerHTML=head+`<div class="ops-toolbar">${button('New project','newProject')}${button('Refresh','reload')}${S.mode==='demo'?button('Export local backup','backup'):''}</div><label>Project<select data-project><option value="">Choose a project</option>${S.data.projects.map(x=>`<option value="${x.id}" ${selected===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><div class="ops-records">${S.data.projects.map(x=>`<button class="ops-project ${x.id===selected?'selected':''}" data-action="selectProject" data-id="${x.id}"><strong>${esc(x.name)}</strong><span>${esc(x.address||'Address pending')}</span><small>${esc(x.status)}</small></button>`).join('')||'<p>No projects yet. Create your first project.</p>'}</div>`;return;}
    if(!p&&!['opsUpload','opsPhotos'].includes(type)){el.innerHTML=head+'<p>Choose a project to continue, or create one now.</p>'+button('New project','newProject')+(type==='opsNotes'?button('Apple Notes connection','appleSetup')+(OpsSources.pendingNote?'<p>Your shared Apple Note is waiting here until you choose a project.</p>':''):'');return;}
    if(type==='opsContact'){el.innerHTML=head+'<div class="ops-contact">Loading contact…</div><hr>'+button('Edit project / contact','contact')+button('Assign employee access','team')+'<p class="ops-muted">Staff see only assigned projects. Owner controls team access and website approval.</p>';contactRender(el,p,gen);return;}
    if(type==='opsNotes'){el.innerHTML=head+button('Add walkthrough note','newNote')+button(OpsSources.pendingNote?'Review shared Apple Note':'Choose / import a note','noteImport')+button('Apple Notes connection','appleSetup')+`<div class="ops-records">${rows('walkthroughs').sort((a,b)=>String(b.occurred_at||b.created_at).localeCompare(String(a.occurred_at||a.created_at))).map(n=>`<article><time>${esc(new Date(n.occurred_at||n.created_at).toLocaleString())}</time><p class="ops-pre">${esc(n.notes)}</p></article>`).join('')||'<p>No notes yet. Record scope, measurements, selections, and unresolved questions here.</p>'}</div>`;return;}
    if(type==='opsField'){el.innerHTML=head+button('Add field item','field')+['material','punch','tool','supply','timeline','document'].map(kind=>`<h3>${{material:'Materials',punch:'Punch list',tool:'Tools',supply:'Supplies',timeline:'Timeline',document:'Documents'}[kind]}</h3>${rows('field_items').filter(x=>x.kind===kind).map(x=>`<article class="ops-field-row"><label class="ops-check"><input type="checkbox" data-complete="${x.id}" ${x.status==='done'?'checked':''}><span>${esc(x.title)}</span></label><p>${esc(x.details)}</p>${x.due_date?`<small>Due ${esc(x.due_date)}</small>`:''}${kind==='document'&&/^https:\/\//.test(x.details||'')?` <a href="${esc(x.details)}" target="_blank" rel="noopener noreferrer">Open document</a>`:''}${button('Edit','editField',x.id)}</article>`).join('')||'<p class="ops-muted">No items added.</p>'}`).join('');return;}
    if(type==='opsUpload'){el.innerHTML=`<div class="ops-heading"><h2>Add photos</h2><span>Private originals</span></div><h3 class="ops-section-title">Destination</h3><label>Save to<select data-upload-destination>${options([['','Photo Inbox'],...S.data.projects.map(x=>[x.id,x.name])],uploadDestination)}</select></label><h3 class="ops-section-title">Choose a source</h3><div class="ops-upload-sources"><label class="ops-upload-choice">${OpsIcon('opsPhotos')}<span>Photo Library</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple data-upload aria-label="Choose photos"></label><label class="ops-upload-choice">${OpsIcon('opsUpload')}<span>Camera</span><input type="file" accept="image/*" capture="environment" data-upload aria-label="Take a photo"></label>${button(OpsIcon('opsGallery')+'Google Photos','googlePhotos')}</div><p class="ops-muted">JPEG, PNG, WebP · up to 20 MB each. Convert HEIC first. Assign Inbox photos to a project whenever you’re ready.</p>`;return;}
    const e=estimate();
    if(!e){el.innerHTML=head+'<p>No estimate draft yet.</p>'+button('Create estimate','newEstimate');return;}
    const items=S.data.estimate_items.filter(x=>x.estimate_id===e.id);let total;try{total=D.display(D.total(items));}catch{total='TBD — unresolved quantities / prices';}
    if(type==='opsEstimate'){el.innerHTML=head+`<p><strong>Version ${e.version}</strong> · ${esc(e.status.replaceAll('_',' '))}</p><p class="ops-pre">${esc(e.notes)}</p><table><thead><tr><th>Scope</th><th>Qty</th><th>Unit price</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.description)}</td><td>${esc(x.quantity??'TBD')} ${esc(x.unit)}</td><td>${x.unit_price===null?'TBD':esc(D.display(D.money(x.unit_price)))}</td><td>${e.status==='draft'?button('Edit','editItem',x.id):''}</td></tr>`).join('')}</tbody></table><p><strong>Scope subtotal: ${total}</strong></p><p class="ops-muted">Draft scope pricing only. Payment schedule, agreement, and contractor/client PDF production remain separate review deliverables.</p>${e.status==='draft'?button('Add scope item','item')+button('Edit scope / confirmation','scope'):''}`;return;}
    if(type==='opsReview'){el.innerHTML=head+`<p><strong>Version ${e.version} · ${esc(e.status.replaceAll('_',' '))}</strong></p><ol><li>Author prepares contractor and matching client drafts.</li><li>Inspector checks both copies. Alex approves exact corrections.</li><li>Reviewer inspects the final client copy and approved corrections.</li></ol><p>Scope confirmed: <strong>${e.scope_confirmed?'Yes':'No'}</strong><br>Scope subtotal: <strong>${esc(total)}</strong></p>${e.status==='draft'?button('Submit for Inspector','submit'):e.status==='internal_review'?button('Record Inspector clearance','inspector'):e.status==='final_review'?button('Record final Reviewer clearance','reviewer'):button('Create new revision','revise')}<p class="ops-muted">These are manual workflow records. No AI review, client sending, or signature request runs automatically.</p>`;}
  }
  function bulkPhoto(assign){
    const photos=S.data.photos.filter(p=>selectedPhotos.has(p.id)&&(galleryView==='all'||(galleryView==='inbox'?!p.project_id:p.project_id===galleryView)));
    if(!photos.length)throw new Error('Select photos first.');
    if(assign&&photos.some(p=>p.project_id))throw new Error('Only inbox photos can be assigned.');
    dialog(`${assign?'Assign':'Edit'} ${photos.length} photos`,assign?`<p>Selected originals will become accessible to this project’s team. Website approval stays unchanged.</p><label>Destination project<select name="project" required><option value="">Choose project</option>${options(S.data.projects.map(p=>[p.id,p.name]))}</select></label>`:`<label>Stage<select name="stage">${options([['','Keep current stage'],...['unsorted','before','during','after'].map(s=>[s,s])])}</select></label><label class="ops-check"><input type="checkbox" name="set_room"> Replace room / work area</label>${input('room','New room / work area')}<label class="ops-check"><input type="checkbox" name="set_caption"> Replace caption</label>${input('caption','New caption')}<p>Only the fields you choose are changed. A checked blank field clears its existing value.</p>`,async f=>{
      if(!assign&&!f.stage&&!f.set_room&&!f.set_caption)throw new Error('Choose at least one field to change.');
      let done=0;const failed=[];
      for(const p of photos.filter(p=>selectedPhotos.has(p.id))){try{if(assign)await S.assignPhoto(p.id,f.project);else{const latest=S.data.photos.find(x=>x.id===p.id);if(!latest)throw new Error('Photo no longer available');await S.save('photos',{...latest,...(f.stage?{stage:f.stage}:{}),...(f.set_room?{room:f.room}:{}),...(f.set_caption?{caption:f.caption}:{})});}selectedPhotos.delete(p.id);done++;}catch(e){failed.push(`${p.name||'Photo'}: ${e.message}`);}}
      refresh();if(failed.length)throw new Error(`${done} saved; ${failed.length} failed. Successful photos are deselected. Close this dialog and retry the remaining selection. ${failed.join('; ')}`);
    },'Apply to selected');
  }
  const actions={account,newProject,newNote,field:()=>fieldForm(),newEstimate,item:()=>estimateItem(),exportGallery,newClient:()=>clientForm(),editClient:id=>clientForm(S.data.clients.find(c=>c.id===id)),bulkPhotoEdit:()=>bulkPhoto(false),bulkPhotoAssign:()=>bulkPhoto(true),clearPhotoSelection:()=>{selectedPhotos.clear();refresh();},
    ...pipeline.actions,
    ...ledger.actions,
    hubFinancials:()=>window.OpenHubFinancials?.(),
    newEstimate:()=>newEstimate(),
    clientProcess:id=>{const c=S.data.clients.find(c=>c.id===id);if(c)clientProcess(c);},
    clientEstimate:id=>newEstimate(id),
    clientProject:id=>{newProject();document.querySelector('.ops-dialog [name=client_id]').value=id;},
    clientStage:key=>{const [type,id]=key.split(':');if(!flows.opsProcessing.includes(type)||!S.data.projects.some(p=>p.id===id))return;choose(id);if(type==='opsClients'){expandedClient=project().client_id;refresh();return;}if(type==='opsProjectWorkspace'){actions.openProject(id);return;}const widget=window.OpsPopOut?.(type),target=widget?.querySelector('.ops-root');if(target&&type==='opsEstimates'){target._step=3;render(target);}},
    addKind:kind=>fieldForm({kind}),
    clientDirectory:()=>{expandedClient=null;refresh();},
    toggleClient:id=>{expandedClient=expandedClient===id?null:id;refresh();},
    focusClient:id=>{expandedClient=id;refresh();requestAnimationFrame(()=>{const form=document.querySelector(`.ops-client-window form[data-record-id="${id}"]`);form?.querySelector('[name=name]')?.focus();});},
    openClient:id=>{expandedClient=id;const center=[...roots].find(el=>el.isConnected&&el.dataset.opsType==='opsCRM');if(center){center._step=0;render(center);center._child._step=1;render(center._child);return;}const existing=[...roots].find(el=>el.isConnected&&el.dataset.opsType==='opsClients');if(existing){render(existing);return;}window.OpsPopOut?.('opsClients');},
    projectPhotos:id=>{choose(id);galleryView=id;window.OpsPopOut?.('opsGallery');},
    projectUpload:projectPhotoUpload,
    shareContact,saveContact:id=>{const c=S.data.clients.find(c=>c.id===id);if(!c)throw new Error('Client unavailable.');const file=contactFile(c);download(file,file.name);status('Open the downloaded contact to add it to your phone or contacts app.');},
    clientNote:(id,button)=>{const c=S.data.clients.find(c=>c.id===id);if(!c)throw new Error('Client unavailable.');const jobId=button.closest('.ops-command').querySelector('[data-client-note-project]')?.value;if(!S.data.projects.some(p=>p.id===jobId&&p.client_id===id))throw new Error('Choose a project for this note.');selected=jobId;newNote();},
    crewLogin:()=>{account();const heading=document.querySelector('.ops-dialog h2');if(heading)heading.textContent='Crew Login';},
    launchWidget:type=>window.OpsPopOut?.(type),
    openProject:id=>{expandedProject=id||null;if(id)choose(id);const centers=[...roots].filter(el=>el.dataset.opsType==='opsCRM'&&el.isConnected);if(centers.length){for(const el of centers){el._step=flows.opsCRM.indexOf('opsProjectWorkspace');render(el);}}else window.OpsPopOut?.('opsProjectWorkspace');},
    ...OpsSourceUI({S,dialog,esc,options,input,area,status,projectId:()=>selected,uploadDestination:()=>uploadDestination,refresh}),
    uploadCurrentProject:()=>{if(project()){uploadDestination=selected;refresh();}},
    assignPhoto:id=>dialog('Assign photo to project',`<p>This moves the photo out of your inbox and makes it available to the selected project’s team. It does not approve website publishing.</p><label>Destination project<select name="project" required><option value="">Choose a project</option>${options(S.data.projects.map(x=>[x.id,x.name]))}</select></label>`,async f=>{await S.assignPhoto(id,f.project);galleryView=f.project;status('Photo assigned to project.');},'Confirm assignment'),
    importPrototype:()=>{document.querySelector('.ops-dialog')?.close();dialog('Import Photo Management backup','<p>Import the original prototype backup into the local demo. Existing IDs are preserved. Public approval must be reviewed again. Duplicate IDs cancel the entire import without replacing your work.</p><label>PHR backup<input type="file" name="backup" accept=".json" required></label>',async f=>{const count=await OpsImportPrototype(f.backup);status(`Imported ${count.projects} projects and ${count.photos} photos locally.`);},'Import');},
    async demo(){await S.demo();document.querySelector('.ops-dialog')?.close();status('Local demo · saved in this browser only. Export backups before clearing browser data.');},
    async signout(){await S.signOut();document.querySelector('.ops-dialog')?.close();status('Signed out.');},reload:()=>S.reload(),selectProject:choose,
    editField:id=>fieldForm(S.data.field_items.find(x=>x.id===id)),editItem:id=>estimateItem(S.data.estimate_items.find(x=>x.id===id)),editPhoto:id=>photoEdit(S.data.photos.find(x=>x.id===id)),
    approvePhoto:id=>{const p=S.data.photos.find(x=>x.id===id);dialog(p.website_public?'Revoke website approval':'Approve for website','<p>Confirm this photo has permission for public use and contains no private information.</p>',()=>S.publication(p,!p.website_public),'Confirm');},
    scope:()=>{const e=estimate();dialog('Scope and assumptions',area('notes','Shared scope, exclusions, and qualifications',e.notes)+`<label class="ops-check"><input name="confirmed" type="checkbox" ${e.scope_confirmed?'checked':''}> Alex has confirmed the proposed scope and material assumptions.</label>`,f=>S.save('estimates',{...e,notes:f.notes,scope_confirmed:f.confirmed==='on'}));},
    contact:()=>{const p=project(),c=S.data.clients.find(x=>x.id===p.client_id);if(!c)throw new Error('Only the project owner can edit client records.');dialog('Project and client details',input('name','Project name',p.name,'text',true)+input('address','Property address',p.address)+input('client_name','Client name',c.name,'text',true)+input('phone','Phone',c.phone,'tel')+input('email','Email',c.email,'email')+`<label>Stage<select name="status">${options(['lead','walkthrough','estimating','review','active','complete','archived'].map(x=>[x,x]),p.status)}</select></label>`+input('next_action','Next action',p.next_action||'Schedule walkthrough','text',true)+input('next_action_due','Next action due',p.next_action_due,'date'),async f=>{await S.save('clients',{...c,name:f.client_name,phone:f.phone,email:f.email});await S.save('projects',{...p,name:f.name,address:f.address,status:f.status,next_action:f.next_action,next_action_due:f.next_action_due||null});});},
    team:()=>dialog('Assign registered employee',input('email','Employee account email','','email',true)+`<label>Access<select name="role">${options([['field','Field — notes, photos, work plan'],['viewer','Viewer — read assigned project'],['estimator','Estimator — estimates and field records'],['manager','Manager — field records and estimates']])}</select></label><p>The employee must already have a registered account. Assignment does not send an invitation.</p>`,f=>S.members(selected,f.email,f.role)),
    backup:async()=>download(new Blob([JSON.stringify(await S.exportBackup())],{type:'application/json'}),'tagims-local-backup.json'),
    submit:()=>review('submit'),inspector:()=>review('inspector'),reviewer:()=>review('reviewer'),revise:()=>review('revise')
  };
  document.addEventListener('input',ev=>{if(!ev.target.matches('[data-thumbnail-size]'))return;thumbnailSize=Math.max(80,Math.min(320,Number(ev.target.value)||160));document.documentElement.style.setProperty('--ops-thumbnail-size',`${thumbnailSize}px`);document.querySelectorAll('[data-thumbnail-size]').forEach(input=>input.value=thumbnailSize);document.querySelectorAll('[data-thumbnail-value]').forEach(output=>output.textContent=`${thumbnailSize}px`);});
  document.addEventListener('click',ev=>{if(ev.target.closest('summary [data-action],summary [data-client-grab]')){ev.preventDefault();return;}const p=ev.target.closest('[data-project-expand]'),c=ev.target.closest('[data-client-expand]');if(p){ev.preventDefault();expandedProject=expandedProject===p.dataset.projectExpand?null:p.dataset.projectExpand;choose(p.dataset.projectExpand);}if(c){ev.preventDefault();expandedClient=expandedClient===c.dataset.clientExpand?null:c.dataset.clientExpand;refresh();}});
  document.addEventListener('input',ev=>{const f=ev.target.closest('form[data-record-form]');if(f)f.dataset.dirty='true';});
  document.addEventListener('submit',async ev=>{const f=ev.target;if(!f.matches('[data-record-form]'))return;ev.preventDefault();const b=f.querySelector('[type=submit]');if(b.disabled)return;b.disabled=true;try{
    const types={project:['projects',['name','address','status','next_action','next_action_due']],client:['clients',['name','phone','email']],field:['field_items',['title','details','due_date']],note:['walkthroughs',['notes']]};
    const [table,allowed]=types[f.dataset.recordForm]||[];if(!table)throw new Error('Unknown form.');const record=S.data[table].find(r=>r.id===f.dataset.recordId);if(!record)throw new Error('Record no longer available.');const fields=Object.fromEntries([...new FormData(f)].filter(([k])=>allowed.includes(k)));
    for(const name of ['name','title','notes'])if(name in fields)fields[name]=D.required(fields[name],name);
    for(const name of ['next_action_due','due_date'])if(name in fields)fields[name]=fields[name]||null;
    if(table==='field_items'&&record.kind==='document')fields.details=D.safeLink(fields.details);
    await S.save(table,{...record,...fields});
    const key=f.dataset.recordId+':'+f.dataset.formKey;for(const root of roots){root._drafts?.delete(key);for(const form of root.querySelectorAll('form[data-record-form]'))if(form.dataset.recordId+':'+form.dataset.formKey===key)delete form.dataset.dirty;}
    refresh();status('Record saved.');
  }catch(e){const form=[...document.querySelectorAll('form[data-record-form]')].find(x=>x.dataset.recordId===f.dataset.recordId&&x.dataset.formKey===f.dataset.formKey)||f;form.dataset.dirty='true';form.querySelector('[role=alert]').textContent=e.message;}finally{b.disabled=false;}});

  document.addEventListener('change',ev=>{if(ev.target.matches('[data-thumbnail-size]')){try{localStorage.setItem('tagims-ops-thumbnail-size',String(thumbnailSize));}catch{}}});
  document.addEventListener('click',ev=>{document.querySelectorAll('.ops-photo-settings[open]').forEach(menu=>{if(!menu.contains(ev.target)||ev.target.closest('[data-action]'))menu.open=false;});});
  document.addEventListener('keydown',ev=>{if(ev.key==='Escape'){document.querySelectorAll('.ops-photo-settings[open]').forEach(menu=>{menu.open=false;menu.querySelector('summary').focus();});}});
  document.addEventListener('click',async ev=>{const b=ev.target.closest('[data-action]');if(!b||!b.closest('.ops-root,.ops-dialog'))return;try{const context=b.closest('[data-project-context-id]');if(context){selected=context.dataset.projectContextId;localStorage.setItem('tagims-ops-project',selected);}await actions[b.dataset.action]?.(b.dataset.id,b);}catch(e){status(e.message,true);}});
  document.addEventListener('click',ev=>{const b=ev.target.closest('[data-step],[data-popout]');if(!b||!b.closest('.ops-root'))return;const root=b.closest('.ops-root');if(b.dataset.popout){remember(root);const widget=window.OpsPopOut?.(b.dataset.popout),target=widget?.querySelector('.ops-root');if(target&&root._child){target._step=root._child._step;target._memory=structuredClone(root._child._memory||{});render(target);}return;}root._step=Number(b.dataset.step);render(root);});
  document.addEventListener('change',ev=>{const t=ev.target;if(t.matches('[data-photo-select]')){t.checked?selectedPhotos.add(t.dataset.photoSelect):selectedPhotos.delete(t.dataset.photoSelect);refresh();}if(t.matches('[data-photo-all]')){t.closest('.ops-root').querySelectorAll('[data-photo-select]').forEach(c=>t.checked?selectedPhotos.add(c.dataset.photoSelect):selectedPhotos.delete(c.dataset.photoSelect));refresh();}if(t.matches('[data-upload-destination]'))uploadDestination=t.value;if(t.matches('[data-gallery-view]')){selectedPhotos.clear();galleryView=t.value;refresh();}});
  document.addEventListener('change',async ev=>{const t=ev.target;try{if(t.matches('[data-project]'))choose(t.value);if(t.matches('[data-complete]')){const x=S.data.field_items.find(x=>x.id===t.dataset.complete);await S.save('field_items',{...x,status:t.checked?'done':'open'});}if(t.matches('[data-upload]')){if(busy)throw new Error('Wait for the current upload to finish.');busy=true;const id=uploadDestination||null,files=Array.from(t.files);let saved=0;const failures=[];for(const file of files){status(`Saving ${file.name}…`);try{await S.upload(id,file);saved++;}catch(e){failures.push(file.name+': '+e.message);}}status(`${saved} photo(s) saved ${S.mode==='cloud'?'to shared storage':'on this browser'}.${failures.length?' Failed: '+failures.join('; '):''}`,failures.length>0);if(!failures.length)t.value='';busy=false;}}catch(e){busy=false;status(e.message,true);refresh();}});
  const renderers=Object.fromEntries(Object.keys(labels).map(type=>[type,()=>{const el=document.createElement('div');el.className='ops-root hub-data-widget';el.dataset.opsType=type;roots.add(el);render(el);return el;}]));
  window.addEventListener('ops-note-received',()=>{for(const el of roots)if(el.dataset.opsType==='opsEstimates')el._step=1;refresh();});
  window.addEventListener('ops-project-order',refresh);
  function reorderClient(id,target){const ids=orderedClients().map(c=>c.id),from=ids.indexOf(id),to=ids.indexOf(target);if(from<0||to<0||from===to)return;ids.splice(to,0,...ids.splice(from,1));localStorage.setItem(clientOrderKey(),JSON.stringify(ids));refresh();status('Client order saved on this browser.');}
  let leadMoving=false;
  async function moveLead(id,stage){
    if(leadMoving)return;const p=S.data.projects.find(p=>p.id===id);if(!p||p.status===stage)return;
    if(!['lead','walkthrough','estimating','review'].includes(stage)){status('Use the project approval / completion flow for this stage. Dragging cannot record client approval.',true);return;}
    leadMoving=true;try{await S.save('projects',{...p,status:stage});choose(id);
      if(stage==='estimating'||stage==='review'){const latest=estimate();actions.clientStage((stage==='review'&&latest?'opsReview':'opsEstimates')+':'+id);if(!latest)newEstimate(id);}
      else if(stage==='walkthrough')scheduleWalkthrough(id);
      status('Stage updated. Continue the client process.');
    }catch(e){status(e.message,true);}finally{leadMoving=false;}
  }
  function recordDrag(sourceAttr,targetAttr,commit){let drag=null,suppressClick=false;
    const clear=()=>{document.querySelectorAll('.ops-record-drop-target').forEach(e=>e.classList.remove('ops-record-drop-target'));drag=null;};
    document.addEventListener('pointerdown',e=>{const b=e.target.closest('['+sourceAttr+']');if(!b||e.button!==0)return;e.stopPropagation();b.setPointerCapture(e.pointerId);drag={id:b.getAttribute(sourceAttr),pointer:e.pointerId,root:b.closest('.ops-root'),x:e.clientX,y:e.clientY,moved:false,target:null};},true);
    document.addEventListener('pointermove',e=>{if(!drag||drag.pointer!==e.pointerId)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<5&&!drag.moved)return;drag.moved=true;e.preventDefault();e.stopPropagation();const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('['+targetAttr+']');document.querySelectorAll('.ops-record-drop-target').forEach(e=>e.classList.remove('ops-record-drop-target'));drag.target=target?.closest('.ops-root')===drag.root?target.getAttribute(targetAttr):null;if(drag.target)target.classList.add('ops-record-drop-target');let scroller=drag.root;while(scroller.parentElement&&getComputedStyle(scroller).overflowY==='visible')scroller=scroller.parentElement;const box=scroller.getBoundingClientRect();if(e.clientY>box.bottom-40)scroller.scrollTop+=18;if(e.clientY<box.top+40)scroller.scrollTop-=18;},{capture:true,passive:false});
    document.addEventListener('pointerup',e=>{if(!drag||drag.pointer!==e.pointerId)return;const d=drag;clear();if(d.moved){suppressClick=true;setTimeout(()=>suppressClick=false,0);e.preventDefault();e.stopPropagation();if(d.target)Promise.resolve().then(()=>commit(d.id,d.target)).catch(err=>status(err.message,true));}},true);
    document.addEventListener('click',e=>{if(suppressClick){suppressClick=false;e.preventDefault();e.stopImmediatePropagation();}},true);
    document.addEventListener('pointercancel',clear);document.addEventListener('keydown',e=>{if(e.key==='Escape')clear();});
  }
  recordDrag('data-client-grab','data-client-record',reorderClient);
  recordDrag('data-lead-drag','data-lead-stage',moveLead);
  // One visual layer for every record drag. It never handles writes or drop decisions.
  (()=>{
    let drag=null;const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
    function finish(event,cancelled=false){if(!drag)return;const d=drag;drag=null;d.source.classList.remove('ops-drag-source');document.body.classList.remove('ops-dragging');if(!d.ghost)return;
      let target=!cancelled&&event?document.elementFromPoint(event.clientX,event.clientY)?.closest(d.target):null;
      if(target?.closest('.ops-root')!==d.source.closest('.ops-root'))target=null;
      const landing=target?.querySelector('summary')||target;
      const box=landing?.getBoundingClientRect()||d.source.getBoundingClientRect();
      if(reduced()||!box.width){d.ghost.remove();return;}
      const animation=d.ghost.animate([{transform:d.ghost.style.transform,opacity:1},{transform:`translate3d(${box.left}px,${box.top}px,0) scale(1)`,opacity:0}],{duration:180,easing:'cubic-bezier(.22,.8,.3,1)',fill:'forwards'});
      animation.finished.catch(()=>{}).finally(()=>d.ghost.remove());
    }
    addEventListener('pointerdown',e=>{const handle=e.target.closest('[data-project-grab],[data-client-grab],[data-lead-drag],[data-pipeline-grab]');if(!handle||e.button!==0)return;finish(null,true);
      let source,target;
      if(handle.hasAttribute('data-project-grab')){source=handle.closest('.ops-project-slot-row').querySelector('summary');target='.ops-project-slot-row';}
      else if(handle.hasAttribute('data-client-grab')){source=handle.closest('summary');target='[data-client-record]';}
      else if(handle.hasAttribute('data-lead-drag')){source=handle;target='[data-lead-stage]';}
      else{source=handle.closest('tr');target='[data-pipeline-row]';}
      if(source)drag={source,target,pointer:e.pointerId,x:e.clientX,y:e.clientY,box:source.getBoundingClientRect(),ghost:null};
    },true);
    addEventListener('pointermove',e=>{const d=drag;if(!d||d.pointer!==e.pointerId)return;if(!d.source.isConnected){finish(null,true);return;}if(!d.ghost&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<5)return;
      if(!d.ghost){const clone=d.source.cloneNode(true),originals=[d.source,...d.source.querySelectorAll('*')],copies=[clone,...clone.querySelectorAll('*')];
        originals.forEach((original,i)=>{const copy=copies[i],style=getComputedStyle(original);for(const name of style)copy.style.setProperty(name,style.getPropertyValue(name));for(const attribute of [...copy.attributes])if(attribute.name!=='style'&&attribute.name!=='class')copy.removeAttribute(attribute.name);copy.style.pointerEvents='none';copy.style.animation='none';copy.style.transition='none';});
        clone.style.margin='0';clone.style.width=d.box.width+'px';clone.style.height=d.box.height+'px';clone.style.transform='none';
        const ghost=document.createElement('div');ghost.className='ops-drag-preview';ghost.setAttribute('aria-hidden','true');ghost.inert=true;ghost.style.width=d.box.width+'px';ghost.style.height=d.box.height+'px';ghost.append(clone);document.body.append(ghost);d.ghost=ghost;d.source.classList.add('ops-drag-source');document.body.classList.add('ops-dragging');
      }
      d.ghost.style.transform=`translate3d(${d.box.left+e.clientX-d.x}px,${d.box.top+e.clientY-d.y}px,0) scale(${reduced()?1:1.008})`;
    },true);
    addEventListener('pointerup',e=>{if(drag?.pointer===e.pointerId)finish(e);},true);
    addEventListener('pointercancel',()=>finish(null,true),true);addEventListener('blur',()=>finish(null,true));addEventListener('keydown',e=>{if(e.key==='Escape')finish(null,true);},true);
  })();
  document.addEventListener('keydown',e=>{const b=e.target.closest('[data-client-grab]');if(b&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const ids=orderedClients().map(c=>c.id),index=ids.indexOf(b.dataset.clientGrab),target=ids[index+(e.key==='ArrowUp'?-1:1)];if(target)try{reorderClient(b.dataset.clientGrab,target);}catch(err){status(err.message,true);}}});
  const widgetPriority=widgetGroups.flatMap(([,types])=>types);
  window.OpsWidgets={groups:widgetGroups,labels:{...Object.fromEntries(widgetPriority.map(t=>[t,labels[t]])),opsPipeline:labels.opsPipeline},renderers,account,start(){S.on(refresh);S.restore().catch(e=>status(e.message,true));}};
})();

