/* One approved project per row. Slot numbers are derived positions, never IDs. */
(function(root){
  const ordered=rows=>rows.filter(x=>x.status!=='complete').sort((a,b)=>(a.position-b.position)||String(a.created_at).localeCompare(String(b.created_at))||a.id.localeCompare(b.id));
  const day=s=>{const d=new Date(s+'T12:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==s)throw new Error('Use a valid date.');return d;};
  const next=d=>{const n=new Date(d);n.setUTCDate(n.getUTCDate()+1);return n;};
  const work=d=>{while([0,6].includes(d.getUTCDay()))d=next(d);return d;};
  function availability(rows,today){let cursor=work(day(today));for(const r of ordered(rows)){if(r.remaining_workdays===null||r.remaining_workdays===undefined||(r.status==='delayed'&&!r.not_before))return null;if(r.not_before){const earliest=work(day(r.not_before));if(earliest>cursor)cursor=earliest;}for(let i=0;i<r.remaining_workdays;i++)cursor=work(next(cursor));}return cursor.toISOString().slice(0,10);}
  root.OpsPipelineDomain={ordered,availability};
  if(typeof module!=='undefined')module.exports=root.OpsPipelineDomain;
  root.OpsPipelineUI=function({S,D,esc,button,input,options,dialog,status,refresh}){
    let moving=false,drag=null;
    const rows=()=>ordered(S.data.pipeline_entries);
    const canEdit=()=>S.mode==='demo'||S.data.projects.some(p=>p.owner_id===S.user?.id);
    function edit(id){
      const x=S.data.pipeline_entries.find(r=>r.id===id),eligible=S.data.projects.filter(p=>(S.mode==='demo'||p.owner_id===S.user?.id)&&!S.data.pipeline_entries.some(r=>r.project_id===p.id));
      if(!x&&!eligible.length)throw new Error('Create a project first, or edit a project already in the pipeline.');
      dialog(x?'Edit pipeline project':'Add approved project',(!x?`<label>Approved project<select name="project_id" required>${options(eligible.map(p=>[p.id,p.name]))}</select></label><label class="ops-check"><input type="checkbox" required> I confirm this project is approved to proceed.</label>`:'')+input('project_total','Project total',x?.project_total??'')+input('payments_received','Payments received',x?.payments_received??0)+`<label>Status<select name="status">${options([['queued','Queued'],['active','Active'],['delayed','Delayed'],['complete','Complete']],x?.status||'queued')}</select></label>`+input('next_action','Next action',x?.next_action||'Schedule project','text',true)+`<details><summary>Scheduling & availability</summary>${input('remaining_workdays','Remaining workdays',x?.remaining_workdays??'','number')}${input('not_before','Not before',x?.not_before||'','date')}<p>One crew, Monday–Friday. Leave unknown durations blank. Delayed projects need a restart date before availability can be calculated.</p></details><p class="ops-muted">Record confirmed totals only. This does not send an invoice, charge a client, or update bank records. Negative remaining due means a credit.</p>`,async f=>{
        if(f.not_before)day(f.not_before);
        await S.save('pipeline_entries',{...(x||{}),project_id:x?.project_id||f.project_id,position:x?.position??Math.max(0,...rows().map(r=>r.position))+1,project_total:f.project_total===''?null:D.money(f.project_total)/100,payments_received:D.money(f.payments_received)/100,status:f.status,next_action:D.required(f.next_action,'Next action'),remaining_workdays:f.remaining_workdays===''?null:Number(f.remaining_workdays),not_before:f.not_before||null});
      },x?'Save':'Add to pipeline');
    }
    async function move(id,to,rootEl){if(moving)return;const list=rows(),from=list.findIndex(x=>x.id===id);if(from<0||to<0||to>=list.length||from===to)return;const [row]=list.splice(from,1);list.splice(to,0,row);moving=true;try{await S.reorderPipeline(list.map(x=>x.id));status(`Project moved to slot ${to+1}.`);rootEl?.querySelector(`[data-pipeline-grab="${id}"]`)?.focus();}catch(e){status(e.message,true);}finally{moving=false;}}
    function render(el){
      const list=rows(),today=new Date(),date=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;let available;try{available=availability(list,date);}catch{available=null;}
      el.innerHTML=`<div class="ops-toolbar">${canEdit()?button('Add approved project','pipelineAdd'):''}${button('Refresh','reload')}</div><p class="ops-pipeline-summary"><strong>${list.length} occupied slots</strong><span>Next slot: ${list.length+1} · ${available?esc(available):'date pending'}</span></p><p class="ops-muted">Drag the handle to change priority. Slot 1 is your first project. Use ↑ / ↓ for one-step moves.</p><div class="ops-pipeline-scroll" tabindex="0" role="region" aria-label="Approved project pipeline"><table class="ops-pipeline-table"><thead><tr>${['Slot #','Client','Project','Project total','Payments received','Remaining due','Status','Next action',''].map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${list.map((x,i)=>{const p=S.data.projects.find(p=>p.id===x.project_id),c=S.data.clients.find(c=>c.id===p?.client_id);return `<tr data-pipeline-row="${x.id}"><td><div class="ops-slot-controls"><strong>${i+1}</strong><button type="button" data-pipeline-grab="${x.id}" aria-label="Move ${esc(p?.name||'project')}; drag or use arrow keys">⠿</button><button type="button" data-pipeline-shift="-1" data-entry="${x.id}" aria-label="Move ${esc(p?.name||'project')} up" ${i===0?'disabled':''}>↑</button><button type="button" data-pipeline-shift="1" data-entry="${x.id}" aria-label="Move ${esc(p?.name||'project')} down" ${i===list.length-1?'disabled':''}>↓</button></div></td><td>${esc(c?.name||'Client unavailable')}</td><td>${button(esc(p?.name||'Project unavailable'),'openProject',x.project_id)}</td><td>${x.project_total===null?'TBD':D.display(D.money(x.project_total))}</td><td>${D.display(D.money(x.payments_received))}</td><td>${x.project_total===null?'TBD':D.display(D.money(x.project_total)-D.money(x.payments_received))}</td><td><span class="ops-pipeline-status" data-status="${x.status}">${esc(x.status)}</span></td><td>${esc(x.next_action)}</td><td>${button('Edit','pipelineEdit',x.id)}</td></tr>`;}).join('')||'<tr><td colspan="9">No approved projects yet. Add a confirmed job when it is ready to enter the work queue.</td></tr>'}</tbody></table></div><details class="ops-pipeline-help"><summary>How availability is calculated</summary><p>Forecast only: one crew working Monday–Friday, starting today, in row order. Uses remaining workdays and “not before” dates. Weekends are excluded; holidays and trade waits must be included in your inputs. Unknown duration or an undated delay makes the next opening unknown. This does not reserve a date.</p></details>`;
    }
    const renderTable=render;
    render=function(el){renderTable(el);const list=rows(),known=list.every(x=>x.project_total!==null),total=list.reduce((s,x)=>s+(x.project_total===null?0:D.money(x.project_total)),0),paid=list.reduce((s,x)=>s+D.money(x.payments_received),0);el.insertAdjacentHTML('afterbegin',`<dl class="ops-metrics">${[['opsPipeline','Approved jobs',String(list.length)],['opsEstimates','Project totals',known?D.display(total):'TBD'],['opsFinancials','Received (recorded)',D.display(paid)],['opsInvoices','Remaining due',known?D.display(total-paid):'TBD']].map(([icon,label,value])=>`<div>${OpsIcon(icon)}<dt>${label}</dt><dd>${value}</dd></div>`).join('')}</dl>`);const complete=S.data.pipeline_entries.filter(x=>x.status==='complete');if(complete.length)el.insertAdjacentHTML('beforeend',`<details class="ops-pipeline-help"><summary>Completed projects (${complete.length})</summary>${complete.map(x=>button(esc(S.data.projects.find(p=>p.id===x.project_id)?.name||'Project'),'pipelineEdit',x.id)).join('')}</details>`);};
    document.addEventListener('click',e=>{const b=e.target.closest('[data-pipeline-shift]');if(b)move(b.dataset.entry,rows().findIndex(x=>x.id===b.dataset.entry)+Number(b.dataset.pipelineShift),b.closest('.ops-root'));});
    document.addEventListener('keydown',e=>{const b=e.target.closest('[data-pipeline-grab]');if(b&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();move(b.dataset.pipelineGrab,rows().findIndex(x=>x.id===b.dataset.pipelineGrab)+(e.key==='ArrowUp'?-1:1),b.closest('.ops-root'));}if(e.key==='Escape')cancel();});
    function cancel(){if(drag)drag.root.querySelectorAll('.ops-drop-target').forEach(e=>e.classList.remove('ops-drop-target'));drag=null;}
    document.addEventListener('pointerdown',e=>{const h=e.target.closest('[data-pipeline-grab]');if(!h||moving||e.button!==0)return;e.preventDefault();drag={id:h.dataset.pipelineGrab,pointer:e.pointerId,root:h.closest('.ops-root'),to:null};h.setPointerCapture(e.pointerId);});
    document.addEventListener('pointermove',e=>{if(!drag||drag.pointer!==e.pointerId)return;e.preventDefault();const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-pipeline-row]');drag.root.querySelectorAll('.ops-drop-target').forEach(e=>e.classList.remove('ops-drop-target'));drag.to=null;if(target&&target.closest('.ops-root')===drag.root){target.classList.add('ops-drop-target');drag.to=rows().findIndex(x=>x.id===target.dataset.pipelineRow);}const scroll=drag.root.closest('.widget-content')?.querySelector('.ops-root'),box=scroll?.getBoundingClientRect();if(box){if(e.clientY>box.bottom-50)scroll.scrollTop+=16;if(e.clientY<box.top+50)scroll.scrollTop-=16;}},{passive:false});
    document.addEventListener('pointerup',e=>{if(!drag||drag.pointer!==e.pointerId)return;const d=drag;cancel();if(d.to!==null)move(d.id,d.to,d.root);});
    document.addEventListener('pointercancel',cancel);
    return {render,actions:{pipelineAdd:()=>edit(),pipelineEdit:edit}};
  };
})(globalThis);
