/* Local append-only events. No writes to estimates or estimate_items. */
window.OpsProjectLedger=({S,D,esc,button,input,area,options,dialog,status})=>{
  const money=D.display;
  const entry=id=>S.data.pipeline_entries.find(e=>e.project_id===id);
  const orders=id=>S.data.change_orders.filter(c=>c.project_id===id);
  const state=c=>S.data.change_events.find(e=>e.change_id===c.id)?.decision||'draft';
  function totals(id){const e=entry(id),approved=orders(id).filter(c=>state(c)==='approved');const delta=approved.reduce((n,c)=>n+c.amount_cents,0),received=D.money(e?.payments_received||0)+S.data.payments.filter(p=>p.project_id===id).reduce((n,p)=>n+p.amount_cents,0);return {base:e?.project_total==null?null:D.money(e.project_total),total:e?.project_total==null?null:D.money(e.project_total)+delta,received,delta,deposit:e?.deposit_cents||0,days:e?.remaining_workdays==null?null:e.remaining_workdays+approved.reduce((n,c)=>n+c.days_delta,0)};}
  const orderKey=()=>`tagims:project-order:v1:${S.user?.id||'signed-out'}`;
  function ordered(){let personal=[];if(S.mode==='cloud'&&S.user?.id)try{const saved=JSON.parse(localStorage.getItem(orderKey())||'[]');if(Array.isArray(saved))personal=saved;}catch{}const rank=p=>personal.includes(p.id)?personal.indexOf(p.id):(p.queue_position??entry(p.id)?.position??(p.status==='active'?1e8:1e9));return [...S.data.projects].sort((a,b)=>Number(['complete','archived'].includes(a.status))-Number(['complete','archived'].includes(b.status))||rank(a)-rank(b)||String(a.created_at).localeCompare(String(b.created_at))||a.id.localeCompare(b.id));}
  const timeline=d=>d==null?'Not set':d>=10?`${+(d/5).toFixed(1)} weeks`:`${d} workdays`;
  function metrics(id){const t=totals(id);return `<dl class="ops-project-metrics">${[['Project total',t.total==null?'Not set':money(t.total)],['Received',money(t.received)],['Remaining',t.total==null?'Not set':money(t.total-t.received)],['Timeline',timeline(t.days)]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`;}
  function edit(id){const e=entry(id);dialog('Project budget & timeline',input('project_total','Original project total',e?.project_total??'')+input('deposit','Deposit requested',((e?.deposit_cents||0)/100))+input('days','Remaining workdays (5 per week)',e?.remaining_workdays??'','number')+'<p class="ops-muted">Deposit requested is not a payment. Record money received separately. Approved change orders are added automatically.</p>',f=>S.projectBudget(id,{project_total:f.project_total===''?null:D.money(f.project_total)/100,deposit_cents:D.money(f.deposit||0),remaining_workdays:f.days===''?null:Number(f.days)}));}
  function payment(id){if(!S.data.projects.length)throw new Error('Create a project first.');dialog('Record payment',(!id?`<label>Project<select name="project_id" required><option value="">Choose project</option>${options(S.data.projects.map(p=>[p.id,p.name]))}</select></label>`:'')+input('amount','Amount received','','text',true)+`<label>Type<select name="kind">${options([['payment','Progress payment'],['deposit','Deposit'],['final','Final payment']])}</select></label>`+input('date','Received date',new Date().toISOString().slice(0,10),'date',true)+input('reference','Reference / method','','text',true)+'<p class="ops-muted">Records a payment already received. Does not charge the client.</p>',f=>S.appendProjectRecord('payment',{project_id:id||f.project_id,amount_cents:D.money(f.amount),kind:f.kind,date:f.date,reference:f.reference}));}
  function newChange(id){if(!S.data.projects.length)throw new Error('Create a project first.');dialog('New change order',`<label>Project<select name="project_id">${options(S.data.projects.map(p=>[p.id,p.name]),id)}</select></label><label>Original estimate (optional)<select name="estimate_id"><option value="">No estimate linked</option>${options(S.data.estimates.map(e=>[e.id,(S.data.projects.find(p=>p.id===e.project_id)?.name||'Project')+' · Version '+e.version]))}</select></label>`+input('invoice_ref','Invoice reference (optional)')+input('title','Change title','','text',true)+area('scope','Added / removed scope')+`<label>Cost change<select name="direction">${options([['add','Add to project'],['credit','Credit to client']])}</select></label>`+input('amount','Amount',0)+input('days','Workday change (negative to shorten)',0,'number')+'<p class="ops-muted">Saved as a separate draft. Original estimate data is never changed.</p>',f=>S.appendProjectRecord('change',{project_id:f.project_id,estimate_id:f.estimate_id||null,invoice_ref:f.invoice_ref,title:f.title,scope:f.scope,amount_cents:D.money(f.amount)*(f.direction==='credit'?-1:1),days_delta:Number(f.days)}),'Create draft');}
  function decide(id,decision){dialog(decision==='approved'?'Record client approval':'Close change order',input('by','Client / approver name','','text',true)+input('date','Decision date',new Date().toISOString().slice(0,10),'date',true)+area('reference','Approval reference / notes')+`<label class="ops-check"><input type="checkbox" required> ${decision==='approved'?'The client approved this exact scope, cost and schedule change.':'Close this draft without changing the project total.'}</label>`,f=>S.appendProjectRecord('decision',{change_id:id,decision,by:f.by,date:f.date,reference:f.reference}),decision==='approved'?'Record approval':'Close draft');}
  function details(id){const t=totals(id),e=entry(id);return `<section class="ops-project-ledger"><h3>Budget & payments</h3>${metrics(id)}<p>Deposit requested: <strong>${money(t.deposit)}</strong>${t.delta?' · Approved changes: '+money(t.delta):''}</p>${button('Edit budget / timeline','budget',id)}${button('＋ Record payment','payment',id)}${e?.payments_received?`<p>Previously recorded received: ${money(D.money(e.payments_received))}</p>`:''}<div class="ops-payment-list">${S.data.payments.filter(p=>p.project_id===id).map(p=>`<p><strong>${money(p.amount_cents)}</strong> · ${esc(p.kind)} · ${esc(p.date)}<br><small>${esc(p.reference)}</small></p>`).join('')}</div><h3>Change orders</h3>${button('＋ New change order','newChange',id)}${orderCards(orders(id))}</section>`;}
  function orderCards(list){return list.map(c=>`<article class="ops-change-card"><header><strong>${esc(c.title)}</strong><span>${esc(state(c))}</span></header><p class="ops-pre">${esc(c.scope)}</p><p>${money(c.amount_cents)} · ${c.days_delta>=0?'+':''}${c.days_delta} workdays</p>${c.estimate_id?'<p>Estimate version '+esc(S.data.estimates.find(e=>e.id===c.estimate_id)?.version||'linked')+'</p>':''}${c.invoice_ref?'<p>Invoice: '+esc(c.invoice_ref)+'</p>':''}${state(c)==='draft'?button('Record client approval','approveChange',c.id)+button('Close draft','closeChange',c.id):S.data.change_events.filter(e=>e.change_id===c.id).map(e=>`<p>${esc(e.decision)} · ${esc(e.by)} · ${esc(e.date)}<br>${esc(e.reference)}</p>`).join('')}</article>`).join('')||'<p class="ops-muted">No change orders.</p>';}
  function render(el){el.innerHTML='<div class="ops-heading"><h2>Change Orders</h2>'+button('＋ New change order','newChange')+'</div>'+S.data.projects.filter(p=>orders(p.id).length).map(p=>'<section><h3>'+esc(p.name)+'</h3>'+orderCards(orders(p.id))+'</section>').join('');}
  function renderPayments(el,receipts=false){
    const list=[...S.data.payments].sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.created_at).localeCompare(String(a.created_at)));
    const title=receipts?'Receipts':'Payments';
    el.innerHTML='<div class="ops-heading"><h2>'+title+'</h2>'+(!receipts?button('＋ Record payment','payment'):'')+'</div>';
    if(S.mode!=='demo'){el.insertAdjacentHTML('beforeend','<p class="ops-muted">Payment records are available in the local workspace only for now.</p>');return;}
    if(!list.length){el.insertAdjacentHTML('beforeend','<p class="ops-muted">'+(receipts?'Receipt details appear when individual payments are recorded.':'No individual payments recorded yet.')+'</p>');}
    else el.insertAdjacentHTML('beforeend',receipts?list.map(p=>{
      const job=S.data.projects.find(x=>x.id===p.project_id),client=S.data.clients.find(x=>x.id===job?.client_id);
      return `<details class="ops-record-accordion ops-receipt"><summary><strong>${money(p.amount_cents)} · ${esc(job?.name||'Project unavailable')}</strong><span>${esc(p.date)} · ${esc(client?.name||'Client unavailable')}</span></summary><div class="ops-record-detail"><h3>Payment receipt details</h3><dl class="ops-form-grid"><div><dt>Client</dt><dd>${esc(client?.name||'Not available')}</dd></div><div><dt>Project</dt><dd>${esc(job?.name||'Not available')}</dd></div><div><dt>Payment type</dt><dd>${esc(p.kind)}</dd></div><div><dt>Reference / method</dt><dd>${esc(p.reference)}</dd></div></dl><p class="ops-muted">Local record · not sent to the client.</p><small>Payment ID: ${esc(p.id)}</small></div></details>`;
    }).join(''):`<table aria-label="Recorded payments"><thead><tr>${['Date','Client / project','Type','Received','Reference'].map(h=>'<th scope="col">'+h+'</th>').join('')}</tr></thead><tbody>${list.map(p=>{const job=S.data.projects.find(x=>x.id===p.project_id),client=S.data.clients.find(x=>x.id===job?.client_id);return `<tr><td>${esc(p.date)}</td><td><strong>${esc(client?.name||'Client unavailable')}</strong><br>${button(esc(job?.name||'Project unavailable'),'openProject',p.project_id)}</td><td>${esc(p.kind)}</td><td>${money(p.amount_cents)}</td><td>${esc(p.reference)}</td></tr>`;}).join('')}</tbody></table>`);
    const legacy=S.data.pipeline_entries.filter(e=>Number(e.payments_received)>0);
    if(legacy.length)el.insertAdjacentHTML('beforeend','<p class="ops-muted">Earlier received totals remain in Projects. Individual receipt details are unavailable for those summary balances.</p>');
  }
  let dragging=null,moving=false;
  async function move(id,delta,target){if(moving)return;const list=ordered().filter(p=>!['complete','archived'].includes(p.status)),from=list.findIndex(p=>p.id===id),to=target?list.findIndex(p=>p.id===target):from+delta;if(from<0||to<0||to>=list.length||from===to)return;const [p]=list.splice(from,1);list.splice(to,0,p);moving=true;try{if(S.mode==='cloud'&&S.user?.id){localStorage.setItem(orderKey(),JSON.stringify(list.map(p=>p.id)));window.dispatchEvent(new Event('ops-project-order'));status(`Moved to slot ${to+1}. Order saved on this browser only.`);}else{await S.reorderProjects(list.map(p=>p.id));status(`Moved to slot ${to+1}.`);}}catch(e){status(e.message,true);}finally{moving=false;}}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-project-shift]');if(b)move(b.dataset.projectId,Number(b.dataset.projectShift));});
  document.addEventListener('keydown',e=>{const b=e.target.closest('[data-project-grab]');if(b&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();move(b.dataset.projectGrab,e.key==='ArrowUp'?-1:1);}});
  document.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-project-grab]');if(!b||e.button!==0)return;e.preventDefault();e.stopPropagation();b.setPointerCapture(e.pointerId);dragging={id:b.dataset.projectGrab,pointer:e.pointerId,root:b.closest('.ops-root'),to:null};},true);
  const cancel=()=>{document.querySelectorAll('.ops-drop-target').forEach(e=>e.classList.remove('ops-drop-target'));dragging=null;};
  document.addEventListener('pointermove',e=>{if(!dragging||e.pointerId!==dragging.pointer)return;e.preventDefault();e.stopPropagation();const row=document.elementFromPoint(e.clientX,e.clientY)?.closest('.ops-project-slot-row[data-queue-project]');document.querySelectorAll('.ops-drop-target').forEach(e=>e.classList.remove('ops-drop-target'));dragging.to=row?.closest('.ops-root')===dragging.root?row.dataset.queueProject:null;if(dragging.to)row.classList.add('ops-drop-target');let scroll=dragging.root;while(scroll.parentElement&&getComputedStyle(scroll).overflowY==='visible')scroll=scroll.parentElement;const box=scroll.getBoundingClientRect();if(e.clientY>box.bottom-40)scroll.scrollTop+=18;if(e.clientY<box.top+40)scroll.scrollTop-=18;},{capture:true,passive:false});
  document.addEventListener('pointerup',e=>{if(!dragging||e.pointerId!==dragging.pointer)return;e.preventDefault();e.stopPropagation();const d=dragging;cancel();if(d.to)move(d.id,0,d.to);},true);document.addEventListener('pointercancel',cancel);document.addEventListener('keydown',e=>{if(e.key==='Escape')cancel();});
  return {ordered,metrics,details,render,renderPayments,totals,actions:{budget:edit,payment,newChange,approveChange:id=>decide(id,'approved'),closeChange:id=>decide(id,'closed')}};
};
