/* Shared owner session, atomic snapshots, and commands for every native widget.
   Preview is memory-only and never calls the database. */
(function(){'use strict';
const E=HubFinanceEngine,C=FINANCE_CONFIG,KEY='hub-finance-owner-session';
const empty=()=>({accounts:[],items:[],projects:[],payments:[],allocations:[],assets:[],scenarios:[]});
let db=empty(),mode='signedout',status='Sign in to your finances',session=null,refreshing=null,loading=null,epoch=0;
const listeners=new Set();const emit=()=>listeners.forEach(fn=>fn());
function saved(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function save(s){session=s?{...s,expires_at:s.expires_at||Math.floor(Date.now()/1000)+s.expires_in}:null;if(session)localStorage.setItem(KEY,JSON.stringify(session));else localStorage.removeItem(KEY)}
async function request(url,options){let r;try{r=await fetch(url,{...options,signal:AbortSignal.timeout(20000)})}catch{throw Error('Connection interrupted. A save may have reached the server; retry this same form to check safely.')}const text=await r.text();let data;try{data=text?JSON.parse(text):null}catch{throw Error('Unexpected server response')};if(!r.ok)throw Error(data?.msg||data?.error_description||data?.message||'Request failed');return data}
const auth=(path,body)=>request(C.url+'/auth/v1/'+path,{method:'POST',headers:{apikey:C.key,'Content-Type':'application/json'},body:JSON.stringify(body)});
async function token(){if(!session)throw Error('Sign in to continue');if(session.expires_at*1000>Date.now()+60000)return session.access_token;
 if(!refreshing)refreshing=(async()=>{const refresh=async()=>{const s=saved();if(s&&s.expires_at*1000>Date.now()+60000){session=s;return s.access_token}const ticket=epoch;const next=await auth('token?grant_type=refresh_token',{refresh_token:session.refresh_token});if(ticket!==epoch)throw Error('Session changed');save(next);return session.access_token};return navigator.locks? navigator.locks.request('hub-finance-refresh',refresh):refresh()})().finally(()=>refreshing=null);return refreshing}
async function api(path,method='GET',body){return request(C.url+'/rest/v1/'+path,{method,headers:{apikey:C.key,Authorization:'Bearer '+await token(),'Content-Type':'application/json',Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body)})}
async function reload(){if(mode==='preview')return;if(!session){mode='signedout';db=empty();emit();return}if(loading)return loading;const ticket=epoch;loading=(async()=>{try{const data=await api('rpc/fin_native_snapshot','POST',{});if(ticket!==epoch)return;if(!data.authorized)throw Error('This verified account is not authorized for these finances.');db=data;mode='live';status='Synced '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});emit()}catch(e){if(ticket===epoch){status=e.message;emit()}throw e}finally{loading=null}})();return loading}
function recompute(){db.accounts.forEach(a=>{a.balance=E.money(E.cents(a.opening_balance)+db.payments.filter(p=>p.account_id===a.id).reduce((s,p)=>s+E.cents(p.amount),0));a.reserved=E.sum(db.allocations.filter(r=>r.account_id===a.id),'amount')});db.items.forEach(i=>{i.paid=E.sum(db.payments.filter(p=>p.item_id===i.id&&!p.voided_at&&!p.reversal_of).map(p=>({amount:Math.abs(p.amount)})),'amount');i.remaining=E.money(E.cents(i.amount)-E.cents(i.paid));i.allocated=E.sum(db.allocations.filter(r=>r.item_id===i.id),'amount')})}
function sample(){const d=E.today(),id=()=>crypto.randomUUID(),a=id(),b=id(),p=id(),q=id();const data=empty();data.accounts=[{id:a,name:'Sample business checking',scope:'business',opening_balance:8200,opening_date:E.addDays(d,-90),active:true},{id:b,name:'Sample personal checking',scope:'personal',opening_balance:850,opening_date:E.addDays(d,-90),active:true}];data.projects=[{id:p,name:'Sample kitchen remodel',client:'Sample client A',contract_total:24000,labor_budget:6500,materials_budget:5500,status:'active'},{id:q,name:'Sample bath renovation',client:'Sample client B',contract_total:12000,labor_budget:3200,materials_budget:2600,status:'scheduled'}];
function item(name,amount,days,bucket,project_id=null,recurrence='once'){const row={id:id(),name,amount,due_date:E.addDays(d,days),direction:bucket==='income'?'in':'out',bucket,project_id,certainty:'confirmed',recurrence,cancelled:false};row.recurrence_anchor=Number(row.due_date.slice(8));data.items.push(row);return row.id}
item('Sample progress check',7200,5,'income',p);item('Sample deposit',4000,12,'income',q);item('Sample final check',9600,30,'income',p);
item('Sample crew lead · 5 days',1100,4,'payroll',p,'weekly');item('Sample helper · 5 days',900,4,'payroll',p,'weekly');item('Sample software subscription',95,-2,'business_bills',null,'monthly');item('Sample workshop rent',450,8,'business_bills',null,'monthly');item('Sample cabinet materials',1800,2,'materials',p);item('Sample next-job supplies',600,10,'materials',q);item('Sample home bills',1550,7,'personal_bills',null,'monthly');item('Sample living budget',350,6,'living',null,'weekly');
const vehicle=item('Sample truck installment',420,10,'business_bills',null,'monthly'),policy=item('Sample liability premium',185,9,'business_bills',null,'monthly'),card=item('Sample card minimum',95,13,'business_bills',null,'monthly');data.assets=[{id:id(),name:'Sample work truck',kind:'vehicle',principal:24000,balance:14500,as_of:d,item_id:vehicle,notes:'Statement balance; update after statement',renewal_date:E.addDays(d,180)},{id:id(),name:'Sample liability policy',kind:'insurance',balance:null,as_of:d,item_id:policy,notes:'Sample carrier · annual coverage',renewal_date:E.addDays(d,23)},{id:id(),name:'Sample business card',kind:'credit',balance:2800,credit_limit:10000,apr:21.9,as_of:d,item_id:card,statement_date:E.addDays(d,8),notes:'Sample only'}];
for(let n=5;n>=0;n--){const date=E.addDays(d,-n*12-2),inc=item('Sample collected milestone',900+250*n,-n*12-2,'income',p),cost=item('Sample paid job cost',460+120*n,-n*12-2,'materials',p);data.payments.push({id:id(),account_id:a,item_id:inc,project_id:p,amount:900+250*n,payment_date:date,memo:'Sample milestone received',command_id:id()},{id:id(),account_id:a,item_id:cost,project_id:p,amount:-(460+120*n),payment_date:date,memo:'Sample paid materials',command_id:id()})}
return data}
async function preview(){epoch++;mode='preview';db=sample();recompute();status='SAMPLE DATA · changes stay in this preview';emit()}
async function leavePreview(){epoch++;db=empty();session=saved();mode=session?'loading':'signedout';status='Preview closed';emit();if(session)await reload()}
async function login(email,password){const s=await auth('token?grant_type=password',{email,password});epoch++;save(s);mode='loading';await reload()}
async function signup(email,password){await auth('signup',{email,password});status='Check your email to confirm access, then return and sign in.';emit()}
async function signout(){const old=session;epoch++;save(null);db=empty();mode='signedout';status='Signed out';emit();if(old)try{await request(C.url+'/auth/v1/logout',{method:'POST',headers:{apikey:C.key,Authorization:'Bearer '+old.access_token}})}catch{/* Local session is already cleared. */}}
const collections={fin_accounts:'accounts',fin_projects:'projects',fin_items:'items',fin_assets:'assets',fin_scenarios:'scenarios'};
async function write(table,record,id){if(mode==='preview'){const rows=db[collections[table]];if(!rows)throw Error('Unknown record');const old=id?rows.find(r=>r.id===id):null;if(id&&!old)throw Error('Record missing');if(table==='fin_items'&&old){if(record.cancelled&&old.allocated>0)throw Error('Release the allocation before cancelling');if((record.amount??old.amount)<old.paid+old.allocated)throw Error('Amount is below payments and reservations');if(old.paid&&(('bucket' in record&&record.bucket!==old.bucket)||('project_id' in record&&record.project_id!==old.project_id)||('direction' in record&&record.direction!==old.direction)))throw Error('Paid classification is locked')}
const row={...(old||{id:record.id||crypto.randomUUID(),active:true,cancelled:false,recurrence:'once'}),...record};if(table==='fin_items'&&!row.recurrence_anchor)row.recurrence_anchor=Number(row.due_date.slice(8));old?Object.assign(old,row):rows.push(row);recompute();emit();return row}
if(mode!=='live')throw Error('Sign in to save');
if(!id&&record.id){const found=await api(table+'?id=eq.'+encodeURIComponent(record.id));if(found?.length){if(!Object.entries(record).every(([k,v])=>String(found[0][k]??'')===String(v??'')))throw Error('This record was already saved with different values. Refresh and edit it.');await reload().catch(()=>{});return found[0]}}
const rows=await api(table+(id?'?id=eq.'+encodeURIComponent(id):''),id?'PATCH':'POST',record);if(!rows?.length)throw Error('Record was not saved');await reload().catch(()=>{status='Saved, but refresh failed. Use Refresh to retrieve updated totals.';emit()});return rows[0]}
async function command(name,values){if(mode!=='preview'){if(mode!=='live')throw Error('Sign in to save');const result=await api('rpc/'+name,'POST',values);await reload().catch(()=>{status='Saved, but refresh failed. Use Refresh to retrieve updated totals.';emit()});return result}
const v=values;if(name==='fin_native_save_asset'){
 const before=JSON.stringify(db);try{let linked=v.p_asset.item_id;if(v.p_bill){linked=v.p_bill.id;const r=db.items.find(i=>i.id===linked);if(r)Object.assign(r,v.p_bill);else db.items.push({...v.p_bill,direction:'out',certainty:'confirmed',cancelled:false,recurrence_anchor:Number(v.p_bill.due_date.slice(8))})}const old=db.assets.find(a=>a.id===v.p_asset.id),asset={...v.p_asset,item_id:linked};if(old)Object.assign(old,asset);else db.assets.push(asset);recompute();emit();return asset}catch(e){db=JSON.parse(before);throw e}}
if(name==='fin_record_payment'){const i=db.items.find(i=>i.id===v.p_item),a=db.accounts.find(a=>a.id===v.p_account);if(!i||!a)throw Error('Account or item missing');if(v.p_amount<=0||v.p_amount>i.remaining||v.p_date>E.today()||v.p_date<a.opening_date)throw Error('Invalid payment amount or date');if(db.payments.some(p=>p.command_id===v.p_command))return;db.payments.push({id:crypto.randomUUID(),account_id:a.id,item_id:i.id,project_id:i.project_id,amount:(i.direction==='in'?1:-1)*v.p_amount,payment_date:v.p_date,memo:i.name,command_id:v.p_command});db.allocations=db.allocations.map(r=>r.item_id===i.id?{...r,amount:Math.max(0,r.amount-v.p_amount)}:r).filter(r=>r.amount>0);if(v.p_amount===i.remaining&&i.recurrence!=='once'&&!db.items.some(r=>r.parent_item_id===i.id))db.items.push({...i,id:crypto.randomUUID(),parent_item_id:i.id,due_date:E.nextDate(i.due_date,i.recurrence,i.recurrence_anchor),paid:0,allocated:0})}
else if(name==='fin_transfer'){if(v.p_from===v.p_to||v.p_amount<=0||v.p_date>E.today())throw Error('Choose different accounts, a positive amount, and a valid date');if(db.payments.some(p=>p.command_id===v.p_command))return;for(const [id,sign]of[[v.p_from,-1],[v.p_to,1]]){const a=db.accounts.find(a=>a.id===id);if(!a||v.p_date<a.opening_date)throw Error('Invalid account or date')}for(const[id,sign]of[[v.p_from,-1],[v.p_to,1]])db.payments.push({id:crypto.randomUUID(),account_id:id,amount:sign*v.p_amount,payment_date:v.p_date,memo:'Transfer between owned accounts',command_id:v.p_command})}
else if(name==='fin_reserve'){const a=db.accounts.find(a=>a.id===v.p_account);if(!a||E.sum(v.p_rows,'amount')>a.balance)throw Error('Reservation exceeds cleared cash');db.allocations=db.allocations.filter(r=>r.account_id!==a.id);for(const r of v.p_rows){if(db.allocations.some(x=>x.item_id===r.item_id))throw Error('Already reserved elsewhere');db.allocations.push({...r,id:crypto.randomUUID(),account_id:a.id})}}
else if(name==='fin_void_payment'){const p=db.payments.find(p=>p.id===v.p_id);if(!p||p.voided_at||p.reversal_of)throw Error('Payment cannot be voided');const set=p.item_id?[p]:db.payments.filter(x=>x.command_id===p.command_id);for(const x of set){x.voided_at=new Date().toISOString();db.payments.push({...x,id:crypto.randomUUID(),amount:-x.amount,item_id:null,project_id:null,reversal_of:x.id,voided_at:null,command_id:v.p_command,memo:'Reversal: '+x.memo})}}
else throw Error('Unsupported preview command');recompute();emit()}
window.HubFinanceStore={get data(){return db},get mode(){return mode},get status(){return status},subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)},reload,preview,leavePreview,login,signup,signout,write,command};
session=saved();if(session){mode='loading';reload().catch(()=>{})}
setInterval(()=>{if(mode==='live'&&document.visibilityState==='visible')reload().catch(()=>{})},30000);
window.addEventListener('focus',()=>{if(mode==='live')reload().catch(()=>{})});
window.addEventListener('storage',e=>{if(e.key===KEY&&mode!=='preview'){epoch++;session=saved();db=empty();mode=session?'loading':'signedout';emit();reload().catch(()=>{})}});
})();
