/* Native Hub renderer registration. Each financial view is a normal Hub widget.
   No iframe, embedded document, legacy financial storage, or second layout system. */
(function(){'use strict';
const E=HubFinanceEngine,S=HubFinanceStore;
const titles={financialoverview:'Financial Overview',cashflow:'Cash Flow',checkallocator:'Next Check',billcenter:'Bills & Subscriptions',payroll:'Payroll',projects:'Projects',financeaccounts:'Accounts & Transfers',creditaccounts:'Credit Planner',equipment:'Equipment',insurance:'Insurance',operatingcosts:'Operating Costs',latebills:'Late Bills',financialactionplan:'Financial Action Plan',financesandbox:'Forecast Sandbox'};
const aliases={financial:'financialoverview',bills:'billcenter',operations:'operatingcosts'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const short=n=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const date=d=>d?new Date(d+'T12:00:00').toLocaleDateString([],{month:'short',day:'numeric'}):'No date';
const btn=(label,action,id='',cls='')=>`<button type="button" class="nf-btn ${cls}" data-nf="${action}" data-id="${esc(id)}">${esc(label)}</button>`;
const go=(label,type)=>btn(label,'open',type);
const empty=(text,action='',label='Add record')=>`<div class="nf-empty"><p>${esc(text)}</p>${action?btn(label,action):''}</div>`;
let horizon=30,allocation=null,scenario={delay:0,extra:0,date:E.today(),transfer:0,confirmed:false},dialog,formContext={},lastFocus;
const table=(head,rows)=>`<div class="nf-table-wrap"><table><thead><tr>${head.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((cell,i)=>`<td data-label="${esc(head[i])}">${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const kpi=(label,value,detail,type,color='')=>`<button class="nf-kpi ${color}" data-nf="open" data-id="${type}"><span>${label}</span><strong>${value}</strong><small>${detail}</small></button>`;
function chart(f,compact=false){if(!f.known)return empty('Enter a business account balance to see the forecast.','account','Add account');let vals=f.days.map(d=>d.balance),min=Math.min(0,...vals),max=Math.max(1,...vals),range=max-min||1;let y=n=>150-(n-min)/range*122;const points=f.days.map((d,i)=>`${36+i/(f.days.length-1)*510},${y(d.balance)}`).join(' ');return `<div class="nf-chart"><svg viewBox="0 0 570 185" role="img" aria-label="Projected business cash: low point ${money(f.minimum)}, ${f.shortfall?'first shortfall '+f.shortfall:'no shortfall in this period'}"><line x1="36" y1="${y(0)}" x2="546" y2="${y(0)}" class="nf-zero"/><text x="3" y="18">${esc(short(max))}</text><text x="3" y="164">${esc(short(min))}</text><polygon points="36,155 ${points} 546,155" class="nf-area"/><polyline points="${points}" class="nf-line"/><text x="36" y="180">${date(f.days[0].date)}</text><text x="490" y="180">${date(f.days.at(-1).date)}</text></svg><div class="nf-chart-legend"><span>Business cash · dated checks and obligations</span><strong class="${f.minimum<0?'nf-bad':''}">Low ${short(f.minimum)}</strong></div></div>`}
function trend(){const db=S.data,d=E.today(),start=E.addDays(d,-41),weeks=Array.from({length:6},(_,n)=>({date:E.addDays(start,n*7),incoming:0,outgoing:0}));const ac=new Set(db.accounts.filter(a=>a.scope==='business').map(a=>a.id));for(const p of db.payments.filter(p=>ac.has(p.account_id)&&p.item_id&&!p.voided_at&&!p.reversal_of&&p.payment_date>=start&&p.payment_date<=d)){const n=Math.min(5,Math.floor((new Date(p.payment_date)-new Date(start))/86400000/7));if(n>=0)weeks[n][p.amount>0?'incoming':'outgoing']+=Math.abs(Number(p.amount))}if(!weeks.some(w=>w.incoming||w.outgoing))return empty('Recorded receipts and payments will build this cash-flow history.');const max=Math.max(...weeks.map(w=>Math.max(w.incoming,w.outgoing)),1);return `<div class="nf-bars">${weeks.map(w=>`<div class="nf-bar-group" title="${date(w.date)}: received ${money(w.incoming)}, paid ${money(w.outgoing)}"><div><i style="height:${w.incoming/max*90}px"></i><i style="height:${w.outgoing/max*90}px"></i></div><small>${date(w.date)}</small></div>`).join('')}</div><div class="nf-chart-legend"><span>● Received <b class="nf-purple">● Paid</b></span><span>6 weeks · cleared funds</span></div>`}
function attention(limit=6){const db=S.data,d=E.today(),end=E.addDays(d,14),items=E.open(db).filter(i=>i.due_date<=end).sort((a,b)=>a.due_date.localeCompare(b.due_date)||E.buckets.indexOf(a.bucket)-E.buckets.indexOf(b.bucket));const renew=db.assets.filter(a=>a.renewal_date&&a.renewal_date<=E.addDays(d,30));let rows=items.slice(0,limit).map(i=>`<div class="nf-attention"><i class="${i.due_date<d?'nf-bad':i.bucket==='payroll'?'nf-warn':'nf-good'}">${i.direction==='in'?'↙':'•'}</i><div><strong>${esc(i.name)}</strong><small>${esc(E.names[i.bucket])} · ${i.due_date<d?'Overdue · ':''}${date(i.due_date)}</small></div><div class="nf-right"><strong>${short(i.remaining)}</strong>${btn(i.direction==='in'?'Record check':'Record payment','pay',i.id)}</div></div>`).join('');if(limit>6)rows+=renew.map(a=>`<div class="nf-attention"><i class="nf-warn">↻</i><div><strong>${esc(a.name)}</strong><small>Review renewal · ${date(a.renewal_date)}</small></div>${btn('Review','edit-asset',a.id)}</div>`).join('');return rows||empty('No due items entered for the next 14 days. Add your obligations to make this useful.','expense','Add bill')}
function overview(){const o=E.overview(S.data,E.today(),horizon),f=o.forecast;const runway=!f.known?'—':f.shortfall?Math.max(0,Math.round((new Date(f.shortfall)-new Date(E.today()))/86400000))+' days':'90+ days';return `<div class="nf-kpis">${kpi('Business cash',short(o.cash),'Cleared funds only','financeaccounts','nf-green')}${kpi('Expected checks',short(o.incoming),`Next ${horizon} days · not cash yet`,'checkallocator','nf-blue')}${kpi('Business outflow',short(o.outgoing),`Next ${horizon} days + overdue`,'billcenter','nf-amber')}${kpi('Uncommitted cash',short(o.free),o.free===null?'Add business + personal balances':`After ${horizon}-day obligations & personal gap`,'checkallocator','nf-purple')}${kpi('Runway outlook',runway,f.shortfall?'Shortfall '+date(f.shortfall):'Entered business forecast · 90 days','financesandbox','nf-blue')}</div>
<div class="nf-dashboard"><section class="nf-section nf-wide"><div class="nf-heading"><h3>Cash outlook</h3>${go('Test a scenario','financesandbox')}</div>${chart(f)}<div class="nf-inline-stats"><span>Reserved <b>${short(o.reserved)}</b></span><span>Payroll <b>${short(o.payroll)}</b></span><span>Personal gap <b>${short(o.gap)}</b></span></div></section><section class="nf-section"><div class="nf-heading"><h3>Needs attention</h3>${go('View all','financialactionplan')}</div>${attention(4)}</section><section class="nf-section"><div class="nf-heading"><h3>Cash-flow history</h3>${go('Transactions','financeaccounts')}</div>${trend()}</section><section class="nf-section nf-wide"><div class="nf-heading"><h3>Put the next check to work</h3>${go('Allocate check','checkallocator')}</div>${priorityBars(o)}<p class="nf-note">Payroll → business bills → materials → personal bills → living expenses.</p></section></div>
<div class="nf-launchpad">${Object.entries(titles).filter(([t])=>!['financialoverview','cashflow','latebills','financesandbox'].includes(t)).map(([t,label])=>go(label+' ↗',t)).join('')}</div><p class="nf-note">Forecasts use entered records, including estimated checks. Personal transfers are separate; preview them in the sandbox. Missing expenses are not included.</p>`}
function priorityBars(o){const rows=E.buckets.slice(0,5).map(bucket=>({bucket,value:E.sum(o.due.filter(i=>i.bucket===bucket),'remaining')})),max=Math.max(1,...rows.map(r=>r.value));return `<div class="nf-priorities">${rows.map((r,n)=>`<div><span><b>${n+1}</b>${E.names[r.bucket]}</span><i><em style="width:${r.value/max*100}%"></em></i><strong>${short(r.value)}</strong></div>`).join('')}</div>`}
function itemList(rows){if(!rows.length)return empty('No matching obligations or checks.');return table(['Obligation','Due','Remaining','Action'],rows.sort((a,b)=>a.due_date.localeCompare(b.due_date)).map(i=>[`<strong>${esc(i.name)}</strong><small>${esc(E.names[i.bucket])}${i.project_id?' · '+esc(S.data.projects.find(p=>p.id===i.project_id)?.name||'Project'):''} · ${esc(i.recurrence)}${i.certainty==='estimated'?' · estimated':''}</small>`,`<span class="${i.due_date<E.today()?'nf-bad':''}">${date(i.due_date)}</span>`,money(i.remaining)+`<small>Paid ${money(i.paid)} · reserved ${money(i.allocated)}</small>`,`${btn(i.direction==='in'?'Record check':'Pay','pay',i.id)} ${btn('Edit','edit-item',i.id)}`]))}
function bills(type){let rows=E.open(S.data).filter(i=>i.direction==='out');if(type==='payroll')rows=rows.filter(i=>i.bucket==='payroll');else if(type==='latebills')rows=rows.filter(i=>i.due_date<E.today());else if(type==='operatingcosts')rows=rows.filter(i=>!E.personal(i));else rows=rows.filter(i=>i.bucket!=='payroll');const due=rows.filter(i=>i.due_date<=E.addDays(E.today(),horizon));return `<div class="nf-inline-stats"><span>Due / overdue in ${horizon} days <b>${money(E.sum(due,'remaining'))}</b></span><span>Open items <b>${rows.length}</b></span></div><div class="nf-toolbar">${btn(type==='payroll'?'Add payroll':'Add obligation',type==='payroll'?'payroll':'expense')}${type==='payroll'?'':btn('Add project cost','project-cost')}${go('Next-check plan','checkallocator')}</div>${itemList(rows)}${type==='payroll'?'<p class="nf-note">Payroll stores employee, whole workdays, daily rate, pay date, and project. These are payroll costs; tax withholding and payroll processing are not included.</p>':''}`}
function projects(){const db=S.data;return `<div class="nf-toolbar">${btn('Add project','project')}${btn('Schedule check','income')}${btn('Add project cost','project-cost')}</div>${db.projects.length?db.projects.map(p=>{const t=E.project(db,p);return `<section class="nf-section"><div class="nf-heading"><div><h3>${esc(p.name)}</h3><small>${esc(p.client)} · ${esc(p.status)}</small></div>${btn('Edit','edit-project',p.id)}</div><div class="nf-project-stats"><div><span>Contract</span><strong>${money(p.contract_total)}</strong></div><div><span>Collected</span><strong class="nf-good">${money(t.collected)}</strong></div><div><span>Remaining</span><strong>${money(t.remaining)}</strong></div><div><span>Paid costs</span><strong>${money(t.paid)}</strong></div><div><span>Projected costs</span><strong>${money(t.projectedCost)}</strong></div><div><span>Projected margin</span><strong class="${t.margin<0?'nf-bad':'nf-good'}">${money(t.margin)}</strong></div></div><div class="nf-progress"><i style="width:${Math.max(0,Math.min(100,p.contract_total?t.collected/p.contract_total*100:0))}%"></i></div><p class="nf-note">${money(t.scheduled)} scheduled collections · ${money(t.openCosts)} unpaid costs. Forecast uses scheduled checks, never the contract balance again.</p>${btn('Project details','project-detail',p.id)}</section>`}).join(''):empty('Add a project to connect its checks, labor, materials, and profitability.','project')}`}
function accounts(){const db=S.data;return `<div class="nf-toolbar">${btn('Add account','account')}${btn('Record transfer','transfer')}${btn('Export records','export')}</div>${db.accounts.length?table(['Account','Balance','Reserved','Action'],db.accounts.map(a=>[`<strong>${esc(a.name)}</strong><small>${esc(a.scope)} · opening ${date(a.opening_date)}</small>`,money(a.balance),money(a.reserved),btn('Edit','edit-account',a.id)])):empty('Enter each account separately with its starting balance.','account')}<div class="nf-heading"><h3>Payment history</h3><small>Cleared entries and corrections</small></div>${db.payments.length?table(['Date / description','Amount','Account','Action'],db.payments.slice().sort((a,b)=>b.payment_date.localeCompare(a.payment_date)).map(p=>[date(p.payment_date)+`<small>${esc(p.memo)}</small>`,`<strong class="${p.amount<0?'nf-bad':'nf-good'}">${money(p.amount)}</strong>`,esc(db.accounts.find(a=>a.id===p.account_id)?.name),p.voided_at?'Voided':p.reversal_of?'Reversal':btn('Void','void',p.id)])):empty('Record a check or payment to begin the history.')}<p class="nf-note">Recording a transfer updates both accounts; it does not initiate a bank transfer.</p>`}
function assetView(type){const db=S.data,kind=type==='creditaccounts'?'credit':type==='insurance'?'insurance':'equipment',rows=db.assets.filter(a=>kind==='equipment'?!['credit','insurance'].includes(a.kind):a.kind===kind);let result=`<div class="nf-toolbar">${btn(kind==='credit'?'Add credit account':kind==='insurance'?'Add policy':'Add equipment','asset-'+kind)}</div>`;result+=rows.length?rows.map(a=>{const i=E.linkedItem(db,a),util=a.credit_limit?Number(a.balance)/Number(a.credit_limit)*100:null;return `<section class="nf-section"><div class="nf-heading"><div><h3>${esc(a.name)}</h3><small>${esc(a.kind)} · snapshot ${date(a.as_of)}</small></div>${btn('Edit','edit-asset',a.id)}</div><div class="nf-project-stats">${kind==='credit'?`<div><span>Statement balance</span><strong>${money(a.balance)}</strong></div><div><span>Credit limit</span><strong>${money(a.credit_limit)}</strong></div><div><span>Utilization</span><strong>${util==null?'—':util.toFixed(1)+'%'}</strong></div><div><span>APR</span><strong>${a.apr??'—'}%</strong></div>`:kind==='equipment'?`<div><span>Original principal</span><strong>${money(a.principal)}</strong></div><div><span>Statement balance</span><strong>${money(a.balance)}</strong></div>`:''}<div><span>${kind==='insurance'?'Renewal':'Next payment'}</span><strong>${kind==='insurance'?date(a.renewal_date):i?date(i.due_date):'Link a bill'}</strong></div><div><span>Payment due</span><strong>${i?money(i.remaining):'—'}</strong></div></div>${kind==='credit'?`<div class="nf-progress"><i style="width:${Math.min(100,Math.max(0,util||0))}%"></i></div><small>Statement closes ${date(a.statement_date)}</small>`:''}<p class="nf-note">${esc(a.notes)}</p>${i?btn('Record payment','pay',i.id):btn('Link payment obligation','edit-asset',a.id)} ${kind==='credit'?btn('Plan payoff','credit-plan',a.id):''}</section>`}).join(''):empty('Add a record and link its payment to Bills. It will flow into the cash forecast automatically.');if(kind==='credit')result+='<p class="nf-note">Utilization uses entered statement balances. Payments update cash and bills; refresh the statement balance when a new statement arrives. Credit scores and automatic interest accrual are not connected.</p>';return result}
function checkView(){const db=S.data,o=E.overview(db,E.today(),14);return `<div class="nf-kpis nf-three">${kpi('Business cash',short(o.cash),'Cleared balance','financeaccounts')}${kpi('Payroll · 14 days',short(o.payroll),'First priority','payroll')}${kpi('Personal gap · 14 days',short(o.gap),'Personal bills less personal cash','financeaccounts')}</div><div class="nf-toolbar">${btn('Allocate next check','allocator')}${btn('Schedule check','income')}${btn('Record personal transfer','transfer')}</div>${allocation?allocationHTML():`<section class="nf-section"><h3>Where should the next check go?</h3><p>Select the funding account, check amount, and coverage date. See each obligation funded in your priority order.</p>${priorityBars(o)}</section>`}<h3>Expected checks</h3>${itemList(E.open(db).filter(i=>i.direction==='in'))}<h3>Reserved money</h3>${db.allocations.length?table(['Obligation','Reserved','Funding account'],db.allocations.map(r=>[esc(db.items.find(i=>i.id===r.item_id)?.name),money(r.amount),esc(db.accounts.find(a=>a.id===r.account_id)?.name)]))+btn('Release account reservations','release'):empty('No money reserved yet. Reservations earmark cash; they are not payments.')}`}
function allocationHTML(){const a=allocation,p=a.plan;return `<section class="nf-section"><div class="nf-heading"><h3>${a.expected?'Expected-check simulation':'Cleared-cash allocation'}</h3><strong>${money(a.available)}</strong></div>${table(['Priority / obligation','Fund','Unfunded'],p.rows.map(r=>[`<strong>${esc(r.name)}</strong><small>${esc(E.names[r.bucket])} · ${date(r.due_date)}${r.projected?' · future recurrence':''}</small>`,money(r.funded),`<span class="${r.short?'nf-bad':''}">${money(r.short)}</span>`]))}<div class="nf-inline-stats"><span>Personal transfer <b>${money(p.transfer)}</b></span><span>Unassigned <b>${money(p.left)}</b></span><span>Unfunded <b class="nf-bad">${money(p.short)}</b></span></div>${a.expected?'<p class="nf-note">Simulation only. Record the check after it clears, then allocate cleared funds.</p>':btn('Save current-item reservations','reserve')}<p class="nf-note">Future recurring occurrences are budget projections. Only existing obligations can be reserved. Existing reservations in this account are replaced; other accounts are respected.</p></section>`}
function sandbox(){const db=S.data,items=E.open(db),base=E.forecast(db.accounts,items),f=E.forecast(db.accounts,items,E.today(),90,scenario.delay,scenario.extra+scenario.transfer,scenario.date,'business',scenario.confirmed);return `<div class="nf-toolbar">${btn('Change scenario','scenario')}${btn('Save scenario','save-scenario')}${btn('Reset','reset-scenario')}</div><div class="nf-inline-stats"><span>Checks delayed <b>${scenario.delay} days</b></span><span>Extra cost <b>${money(scenario.extra)}</b></span><span>Owner transfer <b>${money(scenario.transfer)}</b></span></div>${chart(f)}<div class="nf-project-stats"><div><span>Baseline low</span><strong>${money(base.minimum)}</strong></div><div><span>Scenario low</span><strong class="${f.minimum<0?'nf-bad':''}">${money(f.minimum)}</strong></div><div><span>First shortfall</span><strong>${!f.known?'Unknown':f.shortfall?date(f.shortfall):'None in 90 days'}</strong></div></div><p class="nf-note">${scenario.confirmed?'Confirmed checks only.':'Includes estimated checks.'} Scenario changes never alter actual records. Transfer is a modeled business cash outflow, not a bank instruction.</p>${S.data.scenarios.length?'<h3>Saved scenarios</h3>'+table(['Name','Check delay','Extra outflow','Action'],S.data.scenarios.map(s=>[esc(s.name),s.delay_days+' days',money(s.extra_cost),btn('Load','load-scenario',s.id)])):''}`}
function content(type){if(type==='financialoverview')return overview();if(type==='cashflow')return `<div class="nf-toolbar">${go('Accounts','financeaccounts')}${go('Next check','checkallocator')}${go('Sandbox','financesandbox')}</div>${chart(E.forecast(S.data.accounts,E.open(S.data),E.today(),horizon))}${trend()}${itemList(E.open(S.data).filter(i=>i.due_date<=E.addDays(E.today(),horizon)))}`;if(type==='checkallocator')return checkView();if(['billcenter','payroll','latebills','operatingcosts'].includes(type))return bills(type);if(type==='projects')return projects();if(type==='financeaccounts')return accounts();if(['equipment','insurance','creditaccounts'].includes(type))return assetView(type);if(type==='financesandbox')return sandbox();if(type==='financialactionplan')return `<div class="nf-toolbar">${go('Allocate next check','checkallocator')}${go('Test delayed checks','financesandbox')}</div>${attention(100)}<p class="nf-note">Actions are derived from obligations and renewals. Recording a payment updates its state everywhere.</p>`;return ''}
function render(el,type){const active=['live','preview'].includes(S.mode);el.innerHTML=`<div class="nf-topbar"><span class="nf-status ${S.mode==='preview'?'nf-warn':''}">${esc(S.status)}</span><div>${active?`<select aria-label="Financial horizon" data-nf-horizon>${[14,30,60,90].map(n=>`<option value="${n}" ${n===horizon?'selected':''}>${n} days</option>`).join('')}</select>`:''}${S.mode==='preview'?btn('Exit preview','exit-preview'):active?btn('Refresh','refresh')+btn('Sign out','signout'):''}</div></div><div class="nf-scroll"><div class="nf-view">${active?content(type):`<div class="nf-welcome"><span class="nf-eyebrow">YOUR BUSINESS · ONE FINANCIAL SYSTEM</span><h2>Know where you stand.<br>Know what to do next.</h2><p>Checks, payroll, bills, projects, and forecasts—all connected inside your Hub.</p><div class="nf-toolbar">${btn('Sign in / set up access','auth','','nf-primary')}${btn('Preview sample data','preview')}</div><small>Preview is separate from your real finances. No sample records are uploaded.</small></div>`}</div></div>`}
function renderAll(){document.querySelectorAll('.nf-root').forEach(el=>{const scroll=el.querySelector('.nf-scroll')?.scrollTop||0;render(el,el.dataset.nfType);el.querySelector('.nf-scroll').scrollTop=scroll})}
for(const type of [...Object.keys(titles),...Object.keys(aliases)])contentRenderers[type]=()=>{const el=makeWidget('nf-root','');el.dataset.nfType=aliases[type]||type;render(el,el.dataset.nfType);return el};
S.subscribe(renderAll);
function openWidget(type){const existing=currentWidgets().find(w=>(aliases[w.dataset.contentType]||w.dataset.contentType)===type);if(existing){if(existing.hidden){existing.hidden=false;localStorage.removeItem(`hub-${existing.id}-minimized`)}bringWidgetToFront(existing);return existing}return createWidgetAt(type,innerWidth/2,innerHeight/2)}
function field(name,label,type='text',value='',options=null,required=true){return `<label><span>${esc(label)}</span>${options?`<select name="${name}" ${required?'required':''}>${options.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(l)}</option>`).join('')}</select>`:`<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='number'?'step="0.01"':''} ${type==='password'?'minlength="8" autocomplete="current-password"':''}>`}</label>`}
function ensureDialog(){if(dialog)return;dialog=document.createElement('dialog');dialog.className='nf-dialog';dialog.setAttribute('aria-labelledby','nf-form-title');dialog.innerHTML='<form id="nf-record"><div class="nf-heading"><h2 id="nf-form-title"></h2><button type="button" data-nf="close" aria-label="Close financial form">×</button></div><div class="nf-fields"></div><p class="nf-error" role="alert"></p><div class="nf-toolbar"><button type="submit" class="nf-btn nf-primary">Save</button><button type="button" class="nf-btn" data-nf="close">Cancel</button></div></form>';document.body.append(dialog);dialog.querySelector('form').addEventListener('submit',submit);dialog.addEventListener('close',()=>lastFocus?.isConnected&&lastFocus.focus());dialog.addEventListener('input',e=>{if(['units','unit_rate'].includes(e.target.name)){const f=dialog.querySelector('form');const u=f.elements.namedItem('units'),r=f.elements.namedItem('unit_rate'),a=f.elements.namedItem('amount');if(u&&r&&a)a.value=E.money(E.cents(Number(u.value)*Number(r.value)))}})}
function show(kind,id){ensureDialog();lastFocus=document.activeElement;formContext={kind,id,command:crypto.randomUUID(),billCommand:crypto.randomUUID()};let title='',html='',db=S.data;const projectOptions=[['','No project'],...db.projects.map(p=>[p.id,p.name])],accountOptions=db.accounts.filter(a=>a.active).map(a=>[a.id,a.name]);const input=(...a)=>field(...a);let record={};
if(kind.startsWith('edit-')){const k=kind.slice(5),collection={item:'items',account:'accounts',project:'projects',asset:'assets'}[k];record=db[collection].find(r=>r.id===id)||{};formContext.editId=id;kind=k==='item'?(record.direction==='in'?'income':record.bucket==='payroll'?'payroll':'expense'):k;formContext.kind=kind}
if(kind==='auth'){title='Your private financial access';html=input('email','Email','email','giese.alex@gmail.com')+input('password','App password','password')+'<p class="nf-note">Use your Hub app password. First time? Choose a password and select Set up my access, then confirm the email.</p>'+btn('Set up my access','signup')}
if(kind==='account'){title=formContext.editId?'Edit starting balance':'Add account';html=input('name','Account name')+input('scope','Purpose','text','business',[['business','Business'],['personal','Personal'],['reserve','Protected reserve']])+input('opening_balance','Starting balance','number','0')+input('opening_date','Balance as of','date',E.today())+'<p class="nf-note">Enter a dated opening balance. Subsequent movement belongs in checks, payments, or transfers.</p>'}
if(kind==='project'){title='Project';html=input('name','Project name')+input('client','Client')+input('contract_total','Contract total','number','0')+input('labor_budget','Total labor budget','number','0')+input('materials_budget','Total materials budget','number','0')+input('status','Status','text','active',['estimate','scheduled','active','completed','cancelled'].map(x=>[x,x]))}
if(['income','expense','project-cost','payroll'].includes(kind)){title=kind==='income'?'Schedule expected check':kind==='payroll'?'Payroll commitment':'Bill / project cost';html=input('name','Description / payee');if(kind==='payroll')html+=input('employee_name','Employee')+input('units','Workdays (whole days)','number','5')+input('unit_rate','Daily rate','number','0');html+=input('amount','Total amount','number','')+input('due_date','Expected / due date','date',E.today())+input('project_id','Project','text','',projectOptions)+input('certainty','Certainty','text','confirmed',[['confirmed','Confirmed'],['estimated','Estimated']])+input('recurrence','Repeat','text','once',['once','weekly','monthly','quarterly','yearly'].map(x=>[x,x]));if(!['income','payroll'].includes(kind))html+=input('bucket','Priority bucket','text',kind==='project-cost'?'materials':'business_bills',E.buckets.map(x=>[x,E.names[x]]));if(formContext.editId)html+='<p class="nf-note">To stop future payments, cancel this open occurrence. Paid history remains.</p>'+btn('Cancel this obligation','cancel-item',id)}
if(kind==='pay'){const i=db.items.find(i=>i.id===id);if(!i)return;if(!accountOptions.length){show('account');return}title=i.direction==='in'?'Record cleared check':'Record cleared payment';html=`<p>${esc(i.name)} · ${money(i.remaining)} outstanding</p>`+input('p_account','Account','text','',accountOptions)+input('p_amount','Amount cleared','number',i.remaining)+input('p_date','Cleared date','date',E.today())}
if(kind==='transfer'){title='Record completed bank transfer';html=input('p_from','From account','text','',accountOptions)+input('p_to','To account','text','',accountOptions)+input('p_amount','Amount','number')+input('p_date','Transfer date','date',E.today())+'<p class="nf-note">Updates both balances after you transfer at the bank. It does not send money.</p>'}
if(kind.startsWith('asset-')||kind==='asset'){const k=kind==='asset'?record.kind:kind.slice(6);formContext.kind='asset';title=k==='insurance'?'Insurance policy':k==='credit'?'Credit account':'Equipment / vehicle';const opts=k==='credit'?['credit']:k==='insurance'?['insurance']:['vehicle','trailer','equipment'];html=input('name','Name')+input('kind','Type','text',k,opts.map(x=>[x,x]));if(k!=='insurance')html+=input('balance','Statement balance','number','0')+input('principal','Original principal','number','0',null,false);if(k==='credit')html+=input('credit_limit','Credit limit','number')+input('apr','APR (%)','number','0')+input('statement_date','Statement closing date','date','',null,false);else html+=input('renewal_date','Renewal / review date','date','',null,false);html+=input('as_of','Statement / review as of','date',E.today())+input('notes',k==='insurance'?'Carrier, policy number, coverage notes':'Notes','text','',null,false);const i=E.linkedItem(db,record);html+=input('item_id','Linked payment obligation','text',i?.id||'',[['','None'],['new','Create linked recurring payment'],...E.open(db).filter(i=>i.direction==='out').map(i=>[i.id,i.name])],false)+input('payment_amount','New payment amount (only if creating)','number','',null,false)+input('payment_date','New payment due date','date',E.today(),null,false)+input('payment_bucket','New payment bucket','text','business_bills',[['business_bills','Business bills'],['personal_bills','Personal bills']])+input('payment_recurrence','New payment repeats','text','monthly',['once','weekly','monthly','quarterly','yearly'].map(x=>[x,x]));formContext.linked=i?.id}
if(kind==='allocator'){title='Allocate the next check';html=input('account','Business funding account','text','',db.accounts.filter(a=>a.active&&a.scope==='business').map(a=>[a.id,a.name]))+input('expected','Additional check · simulation only','number','0')+input('through','Cover obligations through','date',E.addDays(E.today(),14))+'<p class="nf-note">Cleared balance is included automatically. Enter 0 additional money to reserve actual cash. Personal account cash covers personal needs first.</p>'}
if(kind==='release'){title='Release account reservations';html=input('account','Account','text','',accountOptions)+'<p class="nf-note">Releases earmarked cash only. No payments are changed.</p>'}
if(kind==='scenario'){title='Forecast sandbox';html=input('delay','Delay expected checks (days)','number',scenario.delay)+input('extra','Extra business cost','number',scenario.extra)+input('transfer','Personal transfer to model','number',scenario.transfer)+input('date','Cost / transfer date','date',scenario.date)+input('confirmed','Include estimated checks?','text',scenario.confirmed?'true':'false',[['false','Include confirmed + estimated'],['true','Confirmed only']])}
if(kind==='save-scenario'){title='Save scenario';html=input('name','Scenario name')+'<p class="nf-note">Saves delay and combined extra business outflow. Does not save transactions.</p>'}
if(kind==='credit-plan'){const a=db.assets.find(a=>a.id===id);title='Credit payoff sandbox';html=`<p>${esc(a.name)} · ${money(a.balance)} at ${a.apr??'unknown'}% APR</p>`+input('payment','Monthly payment to model','number',Math.max(100,Number(E.linkedItem(db,a)?.amount||0)))+input('target','Target utilization (%)','number','10')+'<div class="nf-credit-result"></div><p class="nf-note">Assumes fixed APR, no new charges or fees, monthly interest and payment. This is a planning estimate, not a credit-score prediction.</p>'}
if(kind==='project-detail'){const p=db.projects.find(p=>p.id===id);title=p.name;html=itemList(E.open(db).filter(i=>i.project_id===id));}
dialog.querySelector('#nf-form-title').textContent=title;dialog.querySelector('.nf-fields').innerHTML=html;dialog.querySelector('.nf-error').textContent='';const save=dialog.querySelector('[type=submit]');save.textContent=kind==='auth'?'Sign in':kind==='allocator'||kind==='credit-plan'?'Calculate':kind==='scenario'?'Preview scenario':'Save';save.hidden=kind==='project-detail';save.disabled=false;for(const [key,value]of Object.entries(record)){const el=dialog.querySelector('form').elements.namedItem(key);if(el)el.value=value??''}if(formContext.linked)dialog.querySelector('[name=item_id]').value=formContext.linked;if(!dialog.open)dialog.showModal()}
function numeric(v,key,min=0){const n=Number(v[key]);if(v[key]===''||!Number.isFinite(n)||n<min)throw Error('Enter a valid '+key.replaceAll('_',' '));return n}
async function submit(e){e.preventDefault();const f=e.target,b=f.querySelector('[type=submit]'),v=Object.fromEntries(new FormData(f)),c=formContext,kind=c.kind;b.disabled=true;f.querySelector('.nf-error').textContent='';try{
if(kind==='auth'){await S.login(v.email,v.password)}
else if(kind==='allocator'){const a=S.data.accounts.find(a=>a.id===v.account);if(!a)throw Error('Add a business account first');if(!S.data.accounts.some(a=>a.active&&a.scope==='personal'))throw Error('Add your personal account balance first (zero is valid)');if(v.through<E.today())throw Error('Coverage date must be today or later');const expected=numeric(v,'expected');const occurrences=E.occurrences(E.open(S.data),E.today(),v.through),other=S.data.allocations.filter(r=>r.account_id!==a.id),personalCash=E.sum(S.data.accounts.filter(a=>a.active&&a.scope==='personal').map(a=>({amount:Math.max(0,a.balance-a.reserved)})),'amount');allocation={account:a.id,expected,available:Number(a.balance)+expected,plan:E.allocate(occurrences,Number(a.balance)+expected,v.through,other,personalCash)};openWidget('checkallocator');renderAll()}
else if(kind==='release'){await S.command('fin_reserve',{p_account:v.account,p_rows:[]});allocation=null;renderAll()}
else if(kind==='pay'){await S.command('fin_record_payment',{...v,p_amount:numeric(v,'p_amount',.01),p_item:c.id,p_command:c.command});allocation=null;renderAll()}
else if(kind==='transfer'){if(v.p_from===v.p_to)throw Error('Choose two different accounts');await S.command('fin_transfer',{...v,p_amount:numeric(v,'p_amount',.01),p_command:c.command});allocation=null;renderAll()}
else if(kind==='scenario'){const delay=numeric(v,'delay');if(!Number.isInteger(delay)||delay>365)throw Error('Use a whole delay from 0–365 days');scenario={delay,extra:numeric(v,'extra'),transfer:numeric(v,'transfer'),date:v.date,confirmed:v.confirmed==='true'};renderAll()}
else if(kind==='save-scenario'){await S.write('fin_scenarios',{name:v.name,delay_days:scenario.delay,extra_cost:scenario.extra+scenario.transfer,extra_cost_date:scenario.date})}
else if(kind==='credit-plan'){const a=S.data.assets.find(a=>a.id===c.id),payment=numeric(v,'payment',.01),target=numeric(v,'target');if(target>100)throw Error('Target must be between 0 and 100');const monthly=Number(a.apr)/1200,initial=Number(a.balance);let balance=initial,total=0,months=0;if(a.apr==null||a.balance==null)throw Error('Enter a balance and APR first');if(payment<=balance*monthly)throw Error('Payment does not cover the modeled monthly interest');while(balance>.005&&months<1200){const interest=balance*monthly;total+=interest;balance=Math.max(0,balance+interest-payment);months++}f.querySelector('.nf-credit-result').innerHTML=`<div class="nf-project-stats"><div><span>Estimated payoff</span><strong>${months>=1200?'Over 100 years':months+' months'}</strong></div><div><span>Estimated interest</span><strong>${money(total)}</strong></div><div><span>Pay down to ${target}%</span><strong>${money(Math.max(0,initial-Number(a.credit_limit)*target/100))}</strong></div></div>`;return}
else{let tableName,record={...v};if(kind==='account'){tableName='fin_accounts';record.opening_balance=numeric(v,'opening_balance',-999999999);if(v.opening_date>E.today())throw Error('Starting balance must be today or earlier')}
if(kind==='project'){tableName='fin_projects';for(const k of ['contract_total','labor_budget','materials_budget'])record[k]=numeric(v,k)}
if(['income','expense','project-cost','payroll'].includes(kind)){tableName='fin_items';record.amount=numeric(v,'amount',.01);record.direction=kind==='income'?'in':'out';record.bucket=kind==='income'?'income':kind==='payroll'?'payroll':v.bucket;record.project_id=v.project_id||null;record.recurrence_anchor=Number(v.due_date.slice(8));if(kind==='payroll'){record.units=numeric(v,'units',1);if(!Number.isInteger(record.units))throw Error('Use whole workdays');record.unit_rate=numeric(v,'unit_rate');if(E.cents(record.amount)!==E.cents(record.units*record.unit_rate))throw Error('Payroll total must equal workdays × daily rate')}}
if(kind==='asset'){c.bill=null;tableName='fin_assets';for(const k of ['balance','principal','credit_limit','apr'])if(k in record)record[k]=v[k]===''?null:numeric(v,k);for(const k of ['renewal_date','statement_date'])if(k in record)record[k]=v[k]||null;if(v.item_id==='new'){const amount=numeric(v,'payment_amount',.01);if(!v.payment_date)throw Error('Enter the linked payment due date');c.bill={id:c.billCommand,name:v.name+' payment',bucket:v.payment_bucket,amount,due_date:v.payment_date,recurrence:v.payment_recurrence};record.item_id=c.billCommand}else record.item_id=v.item_id||null;for(const k of ['payment_amount','payment_date','payment_bucket','payment_recurrence'])delete record[k]}
if(!tableName)throw Error('Unknown form');if(kind==='asset')await S.command('fin_native_save_asset',{p_asset:{...record,id:c.editId||c.command},p_bill:c.bill||null});else await S.write(tableName,{...record,...(c.editId?{}:{id:c.command})},c.editId);allocation=null;renderAll()}
dialog.close();}catch(err){f.querySelector('.nf-error').textContent=err.message}finally{b.disabled=false}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-nf]');if(!b)return;const action=b.dataset.nf,id=b.dataset.id;try{if(action==='open'){openWidget(id);return}if(action==='close'){dialog?.close();return}if(action==='preview'){await S.preview();return}if(action==='exit-preview'){allocation=null;await S.leavePreview();return}if(action==='refresh'){b.disabled=true;await S.reload();return}if(action==='signout'){allocation=null;await S.signout();return}if(action==='signup'){const f=dialog.querySelector('form');if(!f.reportValidity())return;b.disabled=true;const v=Object.fromEntries(new FormData(f));await S.signup(v.email,v.password);f.querySelector('.nf-error').textContent='Confirmation email requested. Check your email, then sign in here.';return}
if(action==='reserve'){if(!allocation||allocation.expected)throw Error('Calculate an allocation of cleared cash first');b.disabled=true;await S.command('fin_reserve',{p_account:allocation.account,p_rows:allocation.plan.rows.filter(r=>r.funded>0&&!r.projected).map(r=>({item_id:r.id,amount:r.funded}))});allocation=null;renderAll();return}
if(action==='cancel-item'){if(!confirm('Cancel this obligation and its future recurrence? Recorded payments stay in history. Release any reservations first.'))return;const i=S.data.items.find(i=>i.id===id);await S.write('fin_items',{cancelled:true},id);allocation=null;dialog.close();renderAll();return}
if(action==='void'){if(!confirm('Void this payment with a correcting entry? Transfer corrections affect both accounts.'))return;b.disabled=true;await S.command('fin_void_payment',{p_id:id,p_command:crypto.randomUUID()});allocation=null;renderAll();return}
if(action==='reset-scenario'){scenario={delay:0,extra:0,date:E.today(),transfer:0,confirmed:false};renderAll();return}if(action==='load-scenario'){const s=S.data.scenarios.find(s=>s.id===id);scenario={delay:s.delay_days,extra:Number(s.extra_cost),transfer:0,date:s.extra_cost_date,confirmed:false};renderAll();return}
if(action==='export'){const blob=new Blob([JSON.stringify({format:'hub-native-finances-v1',mode:S.mode,exported_at:new Date().toISOString(),data:S.data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='HUB_Financial_Records_'+E.today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);return}show(action,id)}catch(err){if(dialog?.open)dialog.querySelector('.nf-error').textContent=err.message;else{const root=b.closest('.nf-root');if(root)root.querySelector('.nf-status').textContent=err.message}}finally{if(b.isConnected)b.disabled=false}});
document.addEventListener('change',e=>{if(e.target.matches('[data-nf-horizon]')){horizon=Number(e.target.value);renderAll()}});
// Open one financial overview the first time this correction is used; never rearrange existing widgets.
window.addEventListener('DOMContentLoaded',()=>{if(window.HubAutoSeedFinance===true&&!localStorage.getItem('hub-native-finance-introduced-v1')){if(!currentWidgets().some(w=>titles[w.dataset.contentType]))openWidget('financialoverview');localStorage.setItem('hub-native-finance-introduced-v1','true')}});
})();
