import {clamp,sanitizeAudio,type AudioSettings,type Tone} from './state';
// All audio is synthesized locally: no streaming, subscriptions, or audio requests.
export function noiseData(length:number,random=Math.random){const data=new Float32Array(length);let brown=0;for(let i=0;i<length;i++){brown=(brown+(random()*2-1)*.025)/1.015;data[i]=brown*3;} // blend loop boundary to avoid repeated clicks
 const n=Math.min(2048,Math.floor(length/8));for(let i=0;i<n;i++){const t=.5-.5*Math.cos(Math.PI*i/(n-1));data[length-n+i]=data[length-n+i]*(1-t)+data[0]*t;}
 let mean=0;for(const v of data)mean+=v;mean/=length;let peak=0;for(let i=0;i<length;i++){data[i]-=mean;peak=Math.max(peak,Math.abs(data[i]));}const scale=peak>.7?.7/peak:1;for(let i=0;i<length;i++)data[i]*=scale;return data;}

type Voice={nodes:AudioNode[];sources:AudioScheduledSourceNode[];gain:GainNode;frequency?:AudioParam[];key:string;retire?:number};
export class Soundscape {
 context:AudioContext; private master:GainNode;private breath:GainNode;private bubbleBus:GainNode;private voices=new Map<string,Voice>();private noise:AudioBuffer;private rainNoise:AudioBuffer;private settings:AudioSettings;private running=false;private ticker:number;private started=0;private nextChime=0;private nextBubble=0;private transient=new Set<Voice>();private retired=new Set<Voice>();private pendingStop?:number;
 onStop?:()=>void;
 constructor(settings:AudioSettings){const Constructor=window.AudioContext||(window as any).webkitAudioContext;if(!Constructor)throw Error('Audio is unavailable in this browser.');this.context=new Constructor();const c=this.context;this.settings=sanitizeAudio(settings);this.master=c.createGain();this.master.gain.value=0;this.breath=c.createGain();this.breath.gain.value=1;this.bubbleBus=c.createGain();this.bubbleBus.gain.value=0;this.bubbleBus.connect(this.breath);const limiter=c.createDynamicsCompressor();limiter.threshold.value=-12;limiter.knee.value=15;limiter.ratio.value=8;limiter.attack.value=.01;limiter.release.value=.3;const highpass=c.createBiquadFilter();highpass.type='highpass';highpass.frequency.value=25;this.breath.connect(this.master).connect(highpass).connect(limiter).connect(c.destination);this.noise=c.createBuffer(1,c.sampleRate*8,c.sampleRate);this.noise.copyToChannel(noiseData(c.sampleRate*8),0);this.rainNoise=c.createBuffer(2,c.sampleRate*8,c.sampleRate);for(let channel=0;channel<2;channel++){const data=this.rainNoise.getChannelData(channel);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.18;}this.update(this.settings);this.ticker=window.setInterval(()=>this.tick(),100);}
 private ramp(p:AudioParam,v:number,time=.2){const now=this.context.currentTime;p.cancelScheduledValues(now);p.setTargetAtTime(v,now,time);}
 private voice(key:string):Voice{const gain=this.context.createGain();gain.gain.value=0;gain.connect(this.breath);return {key,gain,nodes:[gain],sources:[]};}
 private oscillator(v:Voice,frequency:number,volume:number,detune=0){const c=this.context,o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=frequency;o.detune.value=detune;g.gain.value=volume;o.connect(g).connect(v.gain);o.start();v.sources.push(o);v.nodes.push(o,g);return o.frequency;}
 private makeTone(t:Tone){const v=this.voice('tone-'+t.id);v.key=t.texture;v.frequency=[this.oscillator(v,t.frequency,.18)];if(t.texture==='Warm pad'){v.frequency.push(this.oscillator(v,t.frequency/2,.1),this.oscillator(v,t.frequency*1.5,.035));}if(t.texture==='Airy pad'){v.frequency.push(this.oscillator(v,t.frequency,.08,-5),this.oscillator(v,t.frequency*2,.025,5));}if(t.texture==='Singing bowl'){v.frequency.push(this.oscillator(v,t.frequency*2.01,.045),this.oscillator(v,t.frequency*2.76,.018));}return v;}
 private makeNoise(key:string){const c=this.context,v=this.voice(key),s=c.createBufferSource(),f=c.createBiquadFilter();s.buffer=key==='rain'?this.rainNoise:this.noise;s.loop=true;f.type=key==='rain'?'highpass':key==='water'?'bandpass':'lowpass';f.frequency.value=key==='rain'?700:key==='water'?650:380;f.Q.value=.35;const smoothing=c.createBiquadFilter();smoothing.type='lowpass';smoothing.frequency.value=key==='rain'?4200:2200;s.connect(f).connect(smoothing).connect(v.gain);v.nodes.push(smoothing);if(key==='water'){const lfo=c.createOscillator(),depth=c.createGain();lfo.frequency.value=.14;depth.gain.value=210;lfo.connect(depth).connect(f.frequency);lfo.start();v.sources.push(lfo);v.nodes.push(lfo,depth);}s.start(0,Math.random()*7);v.sources.push(s);v.nodes.push(s,f);return v;}
 private retire(v:Voice){this.ramp(v.gain.gain,0,.1);v.retire=this.context.currentTime+.8;this.retired.add(v);}
 private destroy(v:Voice){for(const s of v.sources){try{s.stop();}catch{}}for(const n of v.nodes)n.disconnect();}
 update(settings:AudioSettings){this.settings=sanitizeAudio(settings);const s=this.settings;this.ramp(this.bubbleBus.gain,s.bubbles/100,.04);for(const key of ['water','rain','ocean'] as const){if(!this.voices.has(key))this.voices.set(key,this.makeNoise(key));this.ramp(this.voices.get(key)!.gain.gain,s[key]/100*(key==='rain'?1.3:.5),.4);}
  const wanted=new Set(s.tones.map(t=>'tone-'+t.id));for(const [k,v] of this.voices)if(k.startsWith('tone-')&&!wanted.has(k)){this.retire(v);this.voices.delete(k);}
  for(const t of s.tones){const key='tone-'+t.id;let v=this.voices.get(key);if(!v||v.key!==t.texture){if(v)this.retire(v);v=this.makeTone(t);this.voices.set(key,v);}const multipliers=t.texture==='Warm pad'?[1,.5,1.5]:t.texture==='Airy pad'?[1,1,2]:t.texture==='Singing bowl'?[1,2.01,2.76]:[1];v.frequency!.forEach((p,i)=>this.ramp(p,t.frequency*multipliers[i],.25));this.ramp(v.gain.gain,t.volume/100,.35);}
  if(this.running)this.ramp(this.master.gain,s.master/100,.3);
 }
 async play(){if(this.pendingStop){clearTimeout(this.pendingStop);this.pendingStop=undefined;}await this.context.resume();if(this.context.state!=='running')throw Error('Tap Play again to enable audio.');this.running=true;this.started=this.context.currentTime;this.nextChime=this.started+2;this.nextBubble=this.started+.5;this.ramp(this.master.gain,this.settings.master/100,.7);}
 async pause(){this.running=false;this.ramp(this.master.gain,0,.12);this.pendingStop=window.setTimeout(()=>{if(!this.running)void this.context.suspend();},900);}
 private pluck(freq:number,level:number,duration:number,pan:number,bubble=false){const c=this.context,v=this.voice('transient'),p=c.createStereoPanner();v.gain.disconnect();v.gain.connect(p).connect(bubble?this.bubbleBus:this.breath);p.pan.value=pan;v.nodes.push(p);const f=this.oscillator(v,freq,.13);if(bubble)f.exponentialRampToValueAtTime(freq*1.6,c.currentTime+.09);else this.oscillator(v,freq*2.01,.028);v.gain.gain.setValueAtTime(0,c.currentTime);v.gain.gain.linearRampToValueAtTime(level,c.currentTime+.025);v.gain.gain.exponentialRampToValueAtTime(.0001,c.currentTime+duration);v.retire=c.currentTime+duration+.1;this.transient.add(v);}
 private tick(){const now=this.context.currentTime;for(const set of [this.retired,this.transient])for(const v of set)if(now>v.retire!){this.destroy(v);set.delete(v);}if(!this.running||this.context.state!=='running')return;const s=this.settings,elapsed=now-this.started;let level=s.master/100;if(s.timer>0){const remaining=s.timer*60-elapsed;level*=clamp(remaining/20,0,1);if(remaining<=0){void this.pause();this.onStop?.();return;}}this.ramp(this.master.gain,level,.3);this.ramp(this.breath.gain,s.breath?.78+.22*Math.sin(elapsed/s.breathSeconds*Math.PI*2-Math.PI/2):1,.25);
  this.ramp(this.voices.get('ocean')!.gain.gain,s.ocean/100*(.2+.3*(.5+.5*Math.sin(elapsed*.22))),.5);
  for(const t of s.tones)if(t.texture==='Singing bowl')this.ramp(this.voices.get('tone-'+t.id)!.gain.gain,t.volume/100*(.25+.75*Math.exp(-((elapsed+t.id*2)%10)*.45)),.25);
  if(s.chimes&&now>this.nextChime){const base=s.tones[0]?.frequency||432;const ratio=[1,1.125,1.25,1.5,1.667][Math.floor(Math.random()*5)];this.pluck(base*ratio,s.chimes/100*.35,7,(Math.random()-.5)*1.1);this.nextChime=now+6+Math.random()*8;}
  if(s.bubbles&&now>this.nextBubble){this.pluck(160+Math.random()*250,.9,.3,(Math.random()-.5)*.8,true);this.nextBubble=now+.12+Math.random()*.35;}
 }
 get breathLevel(){return this.settings.breath?.78+.22*Math.sin((this.context.currentTime-this.started)/this.settings.breathSeconds*Math.PI*2-Math.PI/2):1;}
 get playing(){return this.running&&this.context.state==='running';}
 dispose(){clearInterval(this.ticker);clearTimeout(this.pendingStop);this.running=false;for(const v of [...this.voices.values(),...this.transient,...this.retired])this.destroy(v);void this.context.close();}
}
