import {useEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import {X,Minus,Plus,Grip} from 'lucide-react';
type Rect={x:number;y:number;width:number;height:number};
const fit=(r:Rect):Rect=>{const width=Math.max(Math.min(360,innerWidth-16),Math.min(r.width,innerWidth-16)),height=Math.max(Math.min(260,innerHeight-16),Math.min(r.height,innerHeight-16));return {width,height,x:Math.max(8,Math.min(r.x,innerWidth-width-8)),y:Math.max(8,Math.min(r.y,innerHeight-height-8))};};
export default function FloatingPanel({children,onClose,onAnchor,collapsed,setCollapsed,style}:{children:ReactNode;onClose:()=>void;onAnchor:(p:{x:number;y:number}|null)=>void;collapsed:boolean;setCollapsed:(v:boolean)=>void;style?:CSSProperties}){const [rect,setRect]=useState<Rect>(()=>{try{return fit(JSON.parse(localStorage.getItem('tank-menu-v1')||'null')||{x:18,y:90,width:660,height:400});}catch{return fit({x:18,y:90,width:660,height:400});}});const element=useRef<HTMLElement>(null);const anchorCallback=useRef(onAnchor);anchorCallback.current=onAnchor;const drag=useRef<{x:number;y:number;rect:Rect;resize:boolean}|null>(null);
 useEffect(()=>{anchorCallback.current({x:rect.x+rect.width*.55,y:rect.y+(collapsed?44:rect.height)});},[rect,collapsed]);
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(!element.current?.contains(e.target as Node))setCollapsed(true);};document.addEventListener('pointerdown',outside,true);return()=>{document.removeEventListener('pointerdown',outside,true);anchorCallback.current(null);};},[]);
 useEffect(()=>{const resize=()=>setRect(r=>fit(r));window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize);},[]);
 useEffect(()=>{const timer=setTimeout(()=>{try{localStorage.setItem('tank-menu-v1',JSON.stringify(rect));}catch{}},250);return()=>clearTimeout(timer);},[rect]);
 function down(e:React.PointerEvent,resize=false){if(e.button!==0)return;e.preventDefault();drag.current={x:e.clientX,y:e.clientY,rect,resize};e.currentTarget.setPointerCapture(e.pointerId);}
 function move(e:React.PointerEvent){const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;setRect(fit(d.resize?{...d.rect,width:d.rect.width+dx,height:d.rect.height+dy}:{...d.rect,x:d.rect.x+dx,y:d.rect.y+dy}));}
 const end=()=>{drag.current=null;};
 return <aside ref={element} className={'studio floating-studio'+(collapsed?' collapsed':'')} aria-label="Aquarium menu" style={{...style,left:rect.x,top:rect.y,width:rect.width,height:collapsed?44:rect.height,'--panel-height':rect.height+'px'} as CSSProperties}><div className="floating-heading"><button className="panel-move" aria-label="Move menu" onPointerDown={e=>down(e)} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={end} onKeyDown={e=>{if(e.key.startsWith('Arrow')){e.preventDefault();setRect(r=>fit({...r,x:r.x+(e.key==='ArrowRight'?20:e.key==='ArrowLeft'?-20:0),y:r.y+(e.key==='ArrowDown'?20:e.key==='ArrowUp'?-20:0)}));}}}><Grip size={17}/>Tank menu</button><button className="icon-button" aria-label={collapsed?'Expand menu':'Minimize menu'} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<Plus size={16}/>:<Minus size={16}/>}</button><button className="icon-button" aria-label="Close menu" onClick={onClose}><X size={16}/></button></div>{!collapsed&&<>{children}<button className="panel-resize" aria-label="Resize menu" onPointerDown={e=>down(e,true)} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={end} onKeyDown={e=>{if(e.key.startsWith('Arrow')){e.preventDefault();setRect(r=>fit({...r,width:r.width+(e.key==='ArrowRight'?20:e.key==='ArrowLeft'?-20:0),height:r.height+(e.key==='ArrowDown'?20:e.key==='ArrowUp'?-20:0)}));}}}>◢</button></>}</aside>;
}
