import {useEffect,useRef,useState} from 'react';
import {Plus,Trash2,Copy,ChevronLeft,ChevronRight} from 'lucide-react';
import {projectPoint} from './perspective';
import Thumbnail from './Thumbnail';
import {DECOR,SPECIES,uid,type TankState,type Selection} from './state';
import {naturalDefaults,natureForm} from './nature';
import {UFO_KIND,GLASS_KIND,catalogDecor} from './decorLibrary';
import {Slider} from './components/ui/slider';
type Props={category?:string;type:'fish'|'decor';state:TankState;selected:Selection;onSelect:(s:Selection)=>void;onAdd:(kind:number)=>void;onRemove:(s:Selection)=>void;onChange:(patch:Partial<TankState>,record?:boolean)=>void;begin:()=>void;end:()=>void};
function Dial({label,value,min=0,max=100,unit='%',onChange,onBegin,onEnd}:{label:string;value:number;min?:number;max?:number;unit?:string;onChange:(v:number)=>void;onBegin:()=>void;onEnd:()=>void}){return <label className="inventory-slider"><span>{label}<b>{Math.round(value)}{unit}</b></span><Slider aria-label={label} min={min} max={max} value={[value]} onValueChange={v=>{onBegin();onChange(Array.isArray(v)?v[0]:v);}} onValueCommitted={onEnd}/></label>;}
export default function Inventory(p:Props){const {type,state}=p,isFish=type==='fish',items=isFish?state.fish:state.decor.filter(d=>!p.category||DECOR[d.kind].category===p.category),catalog=isFish?SPECIES:DECOR;const [page,setPage]=useState(0),[dropping,setDropping]=useState(false);const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(p.selected?.type===type)root.current?.querySelector(`[data-item="${p.selected.id}"]`)?.scrollIntoView({block:'nearest',behavior:'smooth'});},[p.selected?.id,type]);
 const filtered=catalog.map((spec,kind)=>({spec,kind})).filter(({spec,kind})=>(isFish||catalogDecor(kind)&&(!p.category||'category'in spec&&spec.category===p.category)));const totalPages=Math.max(1,Math.ceil(filtered.length/24)),shown=filtered.slice(Math.min(page,totalPages-1)*24,(Math.min(page,totalPages-1)+1)*24);
 const update=(id:number,patch:Record<string,unknown>)=>p.onChange(isFish?{fish:state.fish.map(f=>f.id===id?{...f,...patch}:f)}:{decor:state.decor.map(d=>d.id===id?{...d,...patch}:d)},false);
 function drop(e:React.DragEvent){e.preventDefault();setDropping(false);try{const v=JSON.parse(e.dataTransfer.getData('application/x-tank-item'));if(v.type===type&&Number.isInteger(v.kind)&&catalog[v.kind])p.onAdd(v.kind);}catch{}}
 return <div className="inventory-screen" ref={root}>
 <section className={'tank-inventory'+(dropping?' dropping':'')} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-tank-item')){e.preventDefault();e.dataTransfer.dropEffect='copy';setDropping(true);}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDropping(false);}} onDrop={drop} aria-label={'Your tank '+(isFish?'fish':'decorations')}>
 <div className="inventory-title"><h2>In your tank</h2><span>{items.length}</span></div>
 <div className="owned-grid">{!items.length&&<p className="drop-empty">Drop your first {isFish?'fish':'decoration'} here</p>}{items.map(item=>{const selected=p.selected?.type===type&&p.selected.id===item.id,form='form'in item?natureForm(item.form):naturalDefaults;return <article data-item={item.id} key={item.id} className={'owned-card'+(selected?' selected':'')}>
 <button className="owned-portrait" aria-label={'Select '+catalog[item.kind].name} aria-pressed={selected} onClick={()=>p.onSelect({type,id:item.id})}><span style={{filter:`hue-rotate(${isFish?('hue'in item?item.hue:0)||0:form.hue}deg)`}}><Thumbnail type={type} kind={item.kind}/></span><b>{catalog[item.kind].name}</b></button>
 <button className="copy-item" aria-label={'Copy '+catalog[item.kind].name} disabled={(isFish?state.fish.length:state.decor.length)>=(isFish?80:180)} onClick={()=>{if(isFish)p.onChange({fish:[...state.fish,{...item,id:uid()}]});else if('x'in item)p.onChange({decor:[...state.decor,{...item,id:uid(),x:Math.min(1.5,item.x+.04)}]});}}><Copy size={14}/></button><button className="remove-item" aria-label={'Remove '+catalog[item.kind].name} onClick={()=>p.onRemove({type,id:item.id})}><Trash2 size={15}/></button>
 <Dial label="Size" value={item.size*100} min={isFish?40:20} max={isFish?250:600} onChange={v=>update(item.id,{size:v/100})} onBegin={p.begin} onEnd={p.end}/>
 {!isFish&&'x'in item&&item.kind!==UFO_KIND&&<Dial label="Rotate" value={item.tilt||0} min={-180} max={180} unit="°" onChange={tilt=>update(item.id,{tilt})} onBegin={p.begin} onEnd={p.end}/>}
 {!isFish&&'x'in item&&DECOR[item.kind].category==='Stone'&&<Dial label="Stack height" value={(item.elevation||0)*100} min={0} max={600} unit="" onChange={v=>update(item.id,{elevation:v/100})} onBegin={p.begin} onEnd={p.end}/>}
 {!isFish&&item.kind===GLASS_KIND&&'x'in item&&<label className="color-control"><span>Pebble color</span><input aria-label="Individual glass pebble color" type="color" value={item.glassColor||'#48cbea'} onChange={e=>{p.begin();update(item.id,{glassColor:e.target.value});}} onBlur={p.end}/></label>}
 {selected&&<details className="item-more"><summary>{isFish?'Color':'More controls'}</summary>{isFish?<Dial label="Color" value={('hue'in item?item.hue:0)||0} min={-180} max={180} unit="°" onChange={hue=>update(item.id,{hue})} onBegin={p.begin} onEnd={p.end}/>:<>
 {'x'in item&&<><Dial label="Left / right" value={projectPoint((item.x-.5)*15,0,((item.y-.73)/.25-.5)*5.1,1,1).x*100} min={0} max={100} onChange={v=>{const scale=projectPoint(0,0,((item.y-.73)/.25-.5)*5.1,1,1).scale;update(item.id,{x:(v/100-.5)*16/scale/15+.5});}} onBegin={p.begin} onEnd={p.end}/><Dial label={item.kind===UFO_KIND?'Chain length':'Back / front'} value={(item.y-.73)/.25*100} onChange={v=>update(item.id,{y:.73+v/100*.25})} onBegin={p.begin} onEnd={p.end}/><Dial label="Depth turn" value={item.rotation} min={-180} max={180} unit="°" onChange={rotation=>update(item.id,{rotation})} onBegin={p.begin} onEnd={p.end}/></>}
 {([['hue','Color',-90,90],['moss','Moss',0,100]] as const).map(([key,label,min,max])=><Dial key={key} label={label} value={form[key]*(['width','height','burial'].includes(key)?100:1)} min={min} max={max} onChange={v=>update(item.id,{form:{...form,[key]:v/(['width','height','burial'].includes(key)?100:1)}})} onBegin={p.begin} onEnd={p.end}/>)}
 {'flip'in item&&<button className="text-button" onClick={()=>{p.begin();update(item.id,{flip:!item.flip});p.end();}}>Mirror</button>}</>}
 </details>}</article>;})}</div></section>
 <section className="catalog"><div className="inventory-title"><h2>{'Add '+(isFish?'fish':p.category==='Ornaments'?'decor':p.category?.toLowerCase()||'decor')}</h2><span>{filtered.length} choices</span></div>

 <div className="collection-grid">{shown.map(({spec,kind})=><article className="collection-card" key={kind} draggable onDragStart={e=>{e.dataTransfer.setData('application/x-tank-item',JSON.stringify({type,kind}));e.dataTransfer.effectAllowed='copy';}}><button className="catalog-portrait" aria-label={"Add "+spec.name} disabled={(isFish?state.fish.length:state.decor.length)>=(isFish?80:180)} onClick={()=>p.onAdd(kind)}><Thumbnail type={type} kind={kind}/><b>{spec.name}</b><Plus className="add-symbol" size={14}/></button>{!isFish&&kind>=80&&kind<UFO_KIND&&<small>Scene kit</small>}</article>)}</div>
 {!shown.length&&<p className="drop-empty">No items in this category.</p>}{totalPages>1&&<div className="inventory-pages"><button aria-label="Previous page" disabled={page<=0} onClick={()=>setPage(x=>x-1)}><ChevronLeft/>Back</button><span>{Math.min(page+1,totalPages)} / {totalPages}</span><button aria-label="Next page" disabled={page>=totalPages-1} onClick={()=>setPage(x=>x+1)}>Next<ChevronRight/></button></div>}
 </section></div>;
}
