'use client';
import {useEffect,useRef,useState} from 'react';
import {Fish,Sprout,Sun,Wind,Maximize,Minimize,SlidersHorizontal,X,Plus,Minus,Trash2,Play,Pause,Volume2,VolumeX,Waves,Check,Move,RotateCcw} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import Aquarium,{type TankState,type Decoration} from './tank';
const species=['Neon tetra','Golden angelfish','Orange discus','Red guppy','Pearl gourami','Harlequin rasbora'];
const plants=['Green stems','Java fern','Red ludwigia','Seiryu stone','Branching driftwood','Moss stone'];
const initial:TankState={fish:[9,2,2,3,1,5],decor:[{id:1,kind:0,x:.08,y:.91,size:1.15,flip:false},{id:2,kind:1,x:.27,y:.94,size:.85,flip:false},{id:3,kind:4,x:.32,y:.92,size:1.4,flip:false},{id:4,kind:3,x:.69,y:.94,size:1.1,flip:false},{id:5,kind:0,x:.9,y:.9,size:1.3,flip:true},{id:6,kind:2,x:.78,y:.92,size:.9,flip:false},{id:7,kind:5,x:.52,y:.96,size:.75,flip:false}],bubblers:[{id:1,x:.18,power:40,size:35},{id:2,x:.82,power:30,size:25}],substrate:0,color:'#c5f3ee',brightness:80,angle:40,caustics:45,speed:35,paused:false};
function Range({label,value,onChange,min=0,max=100,suffix='%'}:{label:string,value:number,onChange:(v:number)=>void,min?:number,max?:number,suffix?:string}){return <label className="range"><span>{label}<b>{Math.round(value)}{suffix}</b></span><Slider aria-label={label} min={min} max={max} value={[value]} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)}/></label>}
export default function Home(){
const [state,setState]=useState<TankState>(initial),[ready,setReady]=useState(false),[panel,setPanel]=useState(true),[ambient,setAmbient]=useState(false),[selected,setSelected]=useState<number|null>(null),[sound,setSound]=useState(false),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(false),[saved,setSaved]=useState(true);
const audio=useRef<AudioContext|null>(null),wake=useRef<any>(null);
useEffect(()=>{try{const v=JSON.parse(localStorage.getItem('stillwater-v1')||'null');if(v&&Array.isArray(v.fish)&&v.fish.length===6&&v.fish.every((n:unknown)=>typeof n==='number'&&n>=0&&n<=60)&&Array.isArray(v.decor)&&Array.isArray(v.bubblers)&&/^#[a-f0-9]{6}$/i.test(v.color))setState({...initial,...v,paused:false});}catch{}setReady(true)},[]);
useEffect(()=>{if(ready)try{localStorage.setItem('stillwater-v1',JSON.stringify(state));setSaved(true)}catch{setSaved(false)}},[state,ready]);
const patch=(p:Partial<TankState>)=>setState(s=>({...s,...p}));
const updateDecor=(p:Partial<Decoration>)=>setState(s=>({...s,decor:s.decor.map(d=>d.id===selected?{...d,...p}:d)}));
useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setAmbient(false);setPanel(true);wake.current?.release()}};const fs=()=>{if(!document.fullscreenElement){setAmbient(false);wake.current?.release()}};document.addEventListener('keydown',key);document.addEventListener('fullscreenchange',fs);return()=>{document.removeEventListener('keydown',key);document.removeEventListener('fullscreenchange',fs);audio.current?.close();wake.current?.release()}},[]);
async function immerse(){if(ambient){setAmbient(false);setPanel(true);if(document.fullscreenElement)await document.exitFullscreen();wake.current?.release();return}setAmbient(true);setPanel(false);setSelected(null);try{await document.documentElement.requestFullscreen()}catch{setNotice('Fullscreen is unavailable here. Ambiance mode is still active.')}try{wake.current=await (navigator as any).wakeLock?.request('screen')}catch{}}
async function toggleSound(){if(sound){audio.current?.suspend();setSound(false);return}try{if(!audio.current){const a=new AudioContext();audio.current=a;const buf=a.createBuffer(1,a.sampleRate*4,a.sampleRate),data=buf.getChannelData(0);let v=0;for(let i=0;i<data.length;i++){v=(v+Math.random()*.08-.04)/1.02;data[i]=v*2.2}const source=a.createBufferSource();source.buffer=buf;source.loop=true;const filter=a.createBiquadFilter();filter.type='lowpass';filter.frequency.value=950;const gain=a.createGain();gain.gain.value=.16;source.connect(filter).connect(gain).connect(a.destination);source.start()}await audio.current.resume();setSound(true)}catch{setNotice('Audio is unavailable in this browser.')}}
const chosen=state.decor.find(d=>d.id===selected);
function addDecor(kind:number){const id=Date.now();patch({decor:[...state.decor,{id,kind,x:.35+Math.random()*.25,y:.91,size:1,flip:false}]});setSelected(id)}
return <main className={ambient?'aquarium-app ambient':'aquarium-app'}>
<Aquarium state={state} selected={selected} editing={panel&&!ambient} onSelect={setSelected} onMove={(id,x,y)=>setState(s=>({...s,decor:s.decor.map(d=>d.id===id?{...d,x,y}:d)}))} onReady={()=>setLoaded(true)} onError={()=>{setLoaded(true);setNotice('Some aquarium images could not load. Refresh to try again.')}}/>
{!loaded&&<div className="loading"><Waves size={34}/><p>Filling your little world…</p></div>}
<header className="topbar"><div className="brand"><Waves size={25}/><span>stillwater<span className="brand-dot">.</span></span><small>YOUR LIVING AQUARIUM</small></div><div className="top-actions"><span className="saved"><Check size={13}/>{saved?'Saved on this device':'Saving unavailable'}</span><button className="glass-button" onClick={()=>{setPanel(!panel);setSelected(null)}}><SlidersHorizontal size={16}/>{panel?'Hide studio':'Customize'}</button><button className="primary-button" onClick={immerse}><Maximize size={16}/>Enter ambiance</button></div></header>
{panel&&!ambient&&<aside className="studio"><div className="studio-heading"><div><span className="eyebrow">MAKE IT YOURS</span><h1>Aquarium studio</h1></div><button className="icon-button" aria-label="Close studio" onClick={()=>{setPanel(false);setSelected(null)}}><X size={18}/></button></div>
<Tabs defaultValue="scape"><TabsList className="studio-tabs"><TabsTrigger value="scape"><Sprout/>Scape</TabsTrigger><TabsTrigger value="fish"><Fish/>Fish</TabsTrigger><TabsTrigger value="light"><Sun/>Light</TabsTrigger><TabsTrigger value="air"><Wind/>Air</TabsTrigger></TabsList>
<TabsContent value="scape"><div className="section-heading"><h2>Aquascape</h2><span>{state.decor.length} pieces</span></div><p className="hint">Add a piece, then drag it into place.</p><div className="asset-grid">{plants.map((n,i)=><button className="asset-card" key={n} onClick={()=>addDecor(i)} disabled={state.decor.length>=35}><img src={'/apps/tank/assets/decor-'+i+'.png'} alt=""/><span>{n}</span><Plus size={14}/></button>)}</div>
{chosen&&<div className="selection"><div className="section-heading"><h2>{plants[chosen.kind]}</h2><button className="icon-button danger" aria-label="Remove selected decoration" onClick={()=>{patch({decor:state.decor.filter(d=>d.id!==selected)});setSelected(null)}}><Trash2 size={16}/></button></div><Range label="Size" value={chosen.size*100} min={45} max={180} onChange={v=>updateDecor({size:v/100})}/><Range label="Horizontal position" value={chosen.x*100} min={3} max={97} onChange={v=>updateDecor({x:v/100})}/><Range label="Depth" value={(chosen.y-.7)*1000} max={280} onChange={v=>updateDecor({y:.7+v/1000})} suffix=""/><button className="text-button" onClick={()=>updateDecor({flip:!chosen.flip})}><RotateCcw size={14}/>Mirror piece</button></div>}
<h2 className="section-title">Substrate</h2><div className="substrates">{['River sand','Black sand','Warm sand','White sand'].map((n,i)=><button key={n} aria-pressed={state.substrate===i} onClick={()=>patch({substrate:i})}><i className={'sand sand-'+i}/><span>{n}</span>{state.substrate===i&&<Check size={14}/>}</button>)}</div></TabsContent>
<TabsContent value="fish"><div className="section-heading"><h2>Your fish</h2><span>{state.fish.reduce((a,b)=>a+b,0)} swimming</span></div><p className="hint">A peaceful community, without the upkeep.</p><div className="fish-list">{species.map((n,i)=><div className="fish-row" key={n}><img src={'/apps/tank/assets/fish-'+i+'.png'} alt=""/><div><b>{n}</b><small>{['A shimmering little school','Long, graceful fins','A warm splash of color','Colorful, flowing tails','Gentle and unhurried','Better together'][i]}</small></div><div className="stepper"><button aria-label={'Remove '+n} disabled={!state.fish[i]} onClick={()=>patch({fish:state.fish.map((v,j)=>j===i?Math.max(0,v-1):v)})}><Minus size={13}/></button><span>{state.fish[i]}</span><button aria-label={'Add '+n} disabled={state.fish.reduce((a,b)=>a+b,0)>=60} onClick={()=>patch({fish:state.fish.map((v,j)=>j===i?v+1:v)})}><Plus size={13}/></button></div></div>)}</div><Range label="Swimming pace" value={state.speed} min={10} max={100} onChange={speed=>patch({speed})}/><p className="hint">Up to 60 fish. Small fish drift in loose groups.</p></TabsContent>
<TabsContent value="light"><h2 className="section-title">Set the mood</h2><div className="presets">{[{name:'Daylight',color:'#c5f3ee',b:80},{name:'Golden hour',color:'#ffbb76',b:70},{name:'Moonlight',color:'#639bff',b:32},{name:'Rose glow',color:'#e891dc',b:55}].map(p=><button key={p.name} onClick={()=>patch({color:p.color,brightness:p.b})}><i style={{background:p.color}}/>{p.name}</button>)}</div><label className="color-control"><span>LED color<small>Choose any color</small></span><input type="color" aria-label="LED light color" value={state.color} onChange={e=>patch({color:e.target.value})}/></label><Range label="Brightness" value={state.brightness} onChange={brightness=>patch({brightness})}/><Range label="Light direction" value={state.angle} onChange={angle=>patch({angle})} suffix=""/><Range label="Water shimmer" value={state.caustics} onChange={caustics=>patch({caustics})}/><p className="hint">Light direction changes where the glow falls and how decorations cast their shadows.</p></TabsContent>
<TabsContent value="air"><div className="section-heading"><h2>Bubble makers</h2><button className="text-button" disabled={state.bubblers.length>=5} onClick={()=>patch({bubblers:[...state.bubblers,{id:Date.now(),x:.5,power:40,size:30}]})}><Plus size={14}/>Add</button></div><p className="hint">Small streams of bubbles, just where you like.</p>{!state.bubblers.length&&<p className="empty">Still waters. Add a bubbler for a little movement.</p>}{state.bubblers.map((b,i)=><div className="bubbler" key={b.id}><div className="section-heading"><h3>Air stone {i+1}</h3><button className="icon-button" aria-label={'Remove air stone '+(i+1)} onClick={()=>patch({bubblers:state.bubblers.filter(x=>x.id!==b.id)})}><Trash2 size={15}/></button></div>{(['x','power','size'] as const).map((key,j)=><Range key={key} label={['Position','Flow','Bubble size'][j]} value={key==='x'?b.x*100:b[key]} min={key==='x'?3:0} max={key==='x'?97:100} onChange={v=>patch({bubblers:state.bubblers.map(a=>a.id===b.id?{...a,[key]:key==='x'?v/100:v}:a)})}/>)}</div>)}</TabsContent>
</Tabs><footer className="studio-footer"><Move size={14}/>{selected?'Drag the selected piece to arrange it.':'Your little world. Exactly as you like it.'}</footer></aside>}
<div className="bottom-bar"><div className="tank-caption"><span className="live-dot"/>{state.paused?'A moment of stillness':'A little less rush. A little more wonder.'}</div><div className="transport"><button className="icon-button" aria-label={state.paused?'Resume animation':'Pause animation'} onClick={()=>patch({paused:!state.paused})}>{state.paused?<Play size={17}/>:<Pause size={17}/>}</button><span/><button className="icon-button" aria-label={sound?'Mute water sound':'Play water sound'} onClick={toggleSound}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><span/><button className="icon-button" aria-label="Enter ambiance mode" onClick={immerse}><Maximize size={17}/></button></div></div>
{ambient&&<button className="exit-ambient" onClick={immerse}><Minimize size={15}/>Exit ambiance · Esc</button>}
{notice&&<button className="notice" onClick={()=>setNotice('')}>{notice}<X size={15}/></button>}
</main>}

