import {Chain} from './Chain';
import {WaterLight} from './WaterLight';
import {UFO_KIND,GLASS_KIND,newBase} from './decorLibrary';
import {drawGlass} from './glass';
import {drawUFO} from './ufo';
import {useEffect,useRef} from 'react';
import {Vector3 as V} from 'three';
import {type TankState,type Selection,DECOR,SPECIES,SUBSTRATES,clamp} from './state';
import {createBrain,stepFish,startleFish,type Brain,type Food,type Obstacle} from './behavior';
import {getPhoto,loadPhoto,type Photo} from './photos';
import {projectPoint,unprojectGround} from './perspective';
import {heightAt,COLS,ROWS,gridPoint,type SculptBrush} from './terrain';
import {TerrainRenderer} from './TerrainRenderer';
import {natureForm,natureAsset} from './nature';
import {Fantail3D} from './Fantail3D';
import {Betta3D} from './Betta3D';
export type {TankState,Decoration} from './state';
type Props={showUFO:boolean;getMenuAnchor:()=>{x:number;y:number}|null;brush:SculptBrush|null;onSculpt:(x:number,z:number,dt:number)=>void;state:TankState;selected:Selection;editing:boolean;feeding:boolean;relax:boolean;audioPlaying:boolean;breathLevel:()=>number;onSelect:(s:Selection)=>void;onMove:(id:number,x:number,y:number)=>void;onResize:(id:number,size:number)=>void;onRotate:(id:number,rotation:number)=>void;onStack:(id:number,target:number)=>void;onDragStart:()=>void;onDragEnd:()=>void;onReady:()=>void;onError:(message:string)=>void};
function decorPosition(d:{x:number;y:number;elevation?:number;kind?:number;size?:number},state?:TankState){const x=(d.x-.5)*15,z=((d.y-.73)/.25-.5)*5.1;let ground=state?heightAt(state.terrain,x,z):0;

 return new V(x,ground+(d.elevation||0),z);}
function makeObstacles(state:TankState):Obstacle[]{const out:Obstacle[]=[];for(const d of state.decor){const spec=DECOR[d.kind],p=decorPosition(d,state),r=spec.width*d.size*natureForm(d.form).width*.36,ht=spec.height*d.size*natureForm(d.form).height;const angle=d.rotation*Math.PI/180;const add=(x:number,y:number,z:number,radius:number,soft=false)=>{out.push({center:new V(x*Math.cos(angle)+z*Math.sin(angle),y,z*Math.cos(angle)-x*Math.sin(angle)).add(p),radius,soft});};
 if(spec.shape==='ufo'||spec.shape==='glass')continue;if(spec.category==='Plants'){add(0,ht*.35,0,r*.6,true);continue;}
 if(['arch','ruin','pagoda'].includes(spec.shape)){for(let s of [-1,1]){add(s*spec.width*d.size*.38,ht*.28,0,r*.45);add(s*spec.width*d.size*.38,ht*.65,0,r*.45);}add(0,ht*.84,0,r*.5);}
 else if(['log','pot','cave'].includes(spec.shape)){add(0,ht*.8,0,r*.75);add(0,.1,-r*.9,r*.35);add(0,.1,r*.9,r*.35);}
 else if(spec.category==='Wood'){add(0,ht*.2,0,r*.5);add(r*.6,ht*.5,0,r*.3);add(-r*.6,ht*.4,0,r*.3);}
 else add(0,Math.min(ht*.4,r*.65),0,Math.min(r,ht*.65));
 }return out;}
export default function Aquarium(props:Props){const foreground=useRef<HTMLCanvasElement>(null),canvas=useRef<HTMLCanvasElement>(null),current=useRef(props);current.current=props;
 useEffect(()=>{const el=canvas.current!,ctx=el.getContext('2d',{alpha:false});if(!ctx){current.current.onError('The aquarium could not start in this browser.');return;}const c=ctx,overlay=foreground.current!,top=overlay.getContext('2d')!;let relaxTime=0,lightTime=0;
 let alive=true,frame=0,last=performance.now(),time=0,w=1,h=1,dpr=1,background:HTMLImageElement|null=null,caustics:HTMLImageElement|null=null,terrain:TerrainRenderer|null=null,moss:HTMLImageElement|null=null;
 let fantail:Fantail3D|null=null;try{fantail=new Fantail3D();fantail.load().catch(error=>console.warn('Fantail uses photographic fallback:',error));}catch(error){console.warn('3D unavailable; using photographic fish:',error);}
 let betta:Betta3D|null=null,bettaLoading=false;
 const keychains=new Map<number,Chain>();let motionDt=0,waterLight:WaterLight|null=null;const contacts=new Map<number,{key:string;value:number}>();const fishTints=new Map<string,HTMLCanvasElement>();let lastDraw=0;let frameCost=0;let renderBudget=1000/60;const baseLayer=document.createElement('canvas');let baseKey='';
 const pendingDecor=new Set<number>();
 const fishPhotos=new Map<number,Photo>(),decorPhotos=new Map<number,Photo>();
 const fish=new Map<number,{brain:Brain;facing:number;pitch:number}>(),food:Food[]=[];let foodId=0,obstacles:Obstacle[]=[],lastDecor:TankState['decor']|null=null,lastTerrain:TankState['terrain']|null=null;const plants=new Map<number,{bend:number;velocity:number}>();const finishes=new Map<string,HTMLCanvasElement>();
 type Hit={selection:NonNullable<Selection>;inverse:DOMMatrix;rect:{x:number;y:number;w:number;h:number};photo?:Photo};let hits:Hit[]=[],handle:{x:number;y:number;id:number;anchorX:number;anchorY:number;size:number}|null=null;
 let dragPoint:{x:number;y:number}|null=null;let painting=false,paintPoint:{x:number;y:number}|null=null,paintTime=0;
 let drag:{kind:'move';id:number;dx:number;dy:number;floating?:boolean}|{kind:'resize';id:number;size:number;rotation:number;startX:number;distance:number;anchorX:number;anchorY:number}|null=null;
 const readyJobs=[loadPhoto('/apps/tank/assets/background.jpg').then(image=>{background=image;}),loadPhoto('/apps/tank/assets/nature-caustics.png').then(image=>{caustics=image;waterLight=new WaterLight(image);}),loadPhoto('/apps/tank/assets/nature-moss.png').then(image=>{moss=image;}),Promise.all([loadPhoto('/apps/tank/assets/nature-sand.png'),loadPhoto('/apps/tank/assets/nature-soil.png'),loadPhoto('/apps/tank/assets/floor-library.png')]).then(([sand,soil,floors])=>{terrain=new TerrainRenderer(sand,soil,floors);}),...SPECIES.map((_,i)=>getPhoto('fish',i).then(p=>{fishPhotos.set(i,p);})),...Array.from(new Set(current.current.state.decor.map(d=>d.kind))).map(i=>getPhoto('decor',i).then(p=>{decorPhotos.set(i,p);}))];
 Promise.allSettled(readyJobs).then(results=>{if(!alive)return;current.current.onReady();if(results.some(r=>r.status==='rejected'))current.current.onError('Some aquarium photos did not load. Please refresh after the project finishes syncing.');});
 const observer=new ResizeObserver(()=>{w=el.clientWidth;h=el.clientHeight;dpr=Math.min(window.devicePixelRatio||1,1.5,Math.sqrt(3000000/Math.max(1,w*h)));el.width=Math.round(w*dpr);el.height=Math.round(h*dpr);overlay.width=el.width;overlay.height=el.height;c.setTransform(dpr,0,0,dpr,0,0);});observer.observe(el);
 const addHit=(selection:NonNullable<Selection>,rect:Hit['rect'],photo?:Photo)=>{if(current.current.editing)hits.push({selection,rect,photo,inverse:c.getTransform().inverse()});else if(selection.type==='fish'||selection.type==='decor'&&current.current.state.decor.find(d=>d.id===selection.id)?.kind===UFO_KIND)hits.push({selection,rect,photo,inverse:c.getTransform().inverse()});};
 const drawPhoto=(p:Photo,x:number,y:number,width:number,height:number)=>c.drawImage(p.image,p.sx,p.sy,p.sw,p.sh,x,y,width,height);
 function drawFish(item:{brain:Brain;facing:number;pitch:number},dt:number){const f=item.brain,p=fishPhotos.get(f.kind);if(!p)return;const y=SPECIES[f.kind].zone<.5?Math.max(f.position.y,heightAt(current.current.state.terrain,f.position.x,f.position.z)+SPECIES[f.kind].length*f.size*1.3*p.sh/p.sw*.5+.025):f.position.y,projection=projectPoint(f.position.x,y,f.position.z,w,h),unit=h*.91/6,fw=SPECIES[f.kind].length*f.size*unit*projection.scale*(f.kind===18?1.55:1.3),fh=fw*p.sh/p.sw;
  if(f.kind===15&&betta){const side=fw*2.95;let image:HTMLCanvasElement|null=null;try{image=betta.draw(f,dt,side*dpr);}catch(error){console.warn('Betta renderer stopped:',error);betta.dispose();betta=null;}if(image){c.save();c.translate(projection.x,projection.y);c.globalAlpha=.78+.22*projection.scale/1.1;const hue=current.current.state.fish.find(x=>x.id===f.id)?.hue||0;c.filter=hue?`hue-rotate(${hue}deg)`:'none';c.drawImage(image,-side/2,-side/2,side,side);const hw=fw*(.42+.58*Math.abs(Math.cos(f.heading)))/2,hh=fw*.64;addHit({type:'fish',id:f.id},{x:-hw,y:-hh,w:hw*2,h:hh*2});if(current.current.editing&&current.current.selected?.type==='fish'&&current.current.selected.id===f.id){c.strokeStyle='#d8edc7';c.setLineDash([3,5]);c.strokeRect(-hw-5,-hh-5,hw*2+10,hh*2+10);}c.restore();return;}}
  if(f.kind===18&&fantail){const side=fw*2.8/1.902;let image:HTMLCanvasElement|null=null;try{image=fantail.draw(f,dt,side*dpr);}catch(error){console.warn('Fantail renderer stopped:',error);fantail.dispose();fantail=null;}if(image){c.save();c.translate(projection.x,projection.y);c.globalAlpha=.76+.24*projection.scale/1.1;c.filter=(current.current.state.fish.find(x=>x.id===f.id)?.hue||0)?`hue-rotate(${current.current.state.fish.find(x=>x.id===f.id)?.hue||0}deg)`:'none';c.drawImage(image,-side/2,-side/2,side,side);const hw=fw*(.38+.62*Math.abs(Math.cos(f.heading)))/2,hh=fw*.40;addHit({type:'fish',id:f.id},{x:-hw,y:-hh,w:hw*2,h:hh*2});if(current.current.editing&&current.current.selected?.type==='fish'&&current.current.selected.id===f.id){c.strokeStyle='#d8edc7';c.setLineDash([3,5]);c.strokeRect(-hw-5,-hh-5,hw*2+10,hh*2+10);}c.restore();return;}}
  if(f.velocity.lengthSq()>.0005){const desired=Math.cos(f.heading);item.facing+=(desired-item.facing)*(1-Math.exp(-dt*3.5));const pitch=-clamp(Math.atan2(f.velocity.y,Math.max(.1,Math.abs(f.velocity.x))),-.3,.3);item.pitch+=(pitch-item.pitch)*(1-Math.exp(-dt*2));}
  const direction=item.facing<0?-1:1,foreshortening=Math.max(.045,Math.abs(item.facing)),bob=SPECIES[f.kind].zone<.5?0:Math.sin(time*.9+f.id)*h*.0013;
  c.save();c.translate(projection.x,projection.y+bob);c.rotate(item.pitch*direction);c.scale(direction*foreshortening,1);c.globalAlpha=.76+.24*projection.scale/1.1;
  const hue=current.current.state.fish.find(x=>x.id===f.id)?.hue||0,key=f.kind+'/'+hue;let tinted=fishTints.get(key);if(!tinted){tinted=document.createElement('canvas');const ratio=Math.min(1,768/Math.max(p.sw,p.sh));tinted.width=Math.max(1,Math.round(p.sw*ratio));tinted.height=Math.max(1,Math.round(p.sh*ratio));const tc=tinted.getContext('2d')!;tc.filter=hue?`hue-rotate(${hue}deg)`:'none';tc.drawImage(p.image,p.sx,p.sy,p.sw,p.sh,0,0,tinted.width,tinted.height);fishTints.set(key,tinted);if(fishTints.size>90)fishTints.delete(fishTints.keys().next().value!);}const strips=fw<60?8:12;for(let k=0;k<strips;k++){const u=k/strips,bend=Math.sin(f.phase+u*4)*fw*(f.mode==='scurry'?.045:(.012+Math.min(.02,f.velocity.length()*.012))*(.18+.82*Math.max(0,Math.sin(f.phase*.31))))*(1-u)*(1-u)+f.turn*fw*.025*(1-u)*(1-u);c.drawImage(tinted,u*tinted.width,0,tinted.width/strips,tinted.height,-fw/2+k*fw/strips,-fh/2+bend,fw/strips+.4,fh);}
  addHit({type:'fish',id:f.id},{x:-fw/2,y:-fh/2,w:fw,h:fh},p);
  if(current.current.editing&&current.current.selected?.type==='fish'&&current.current.selected.id===f.id){c.globalAlpha=.6;c.strokeStyle='#d8edc7';c.lineWidth=1;c.setLineDash([3,5]);c.strokeRect(-fw/2-5,-fh/2-5,fw+10,fh+10);}c.restore();
 }
 function finishedPhoto(d:TankState['decor'][number],p:Photo){const f=natureForm(d.form),key=[d.kind,f.hue,f.saturation,f.lightness,f.moss].join('/'),old=finishes.get(key);if(old)return old;const canvas=document.createElement('canvas');const resolution=Math.min(1,2048/Math.max(p.sw,p.sh));canvas.width=Math.round(p.sw*resolution);canvas.height=Math.round(p.sh*resolution);const k=canvas.getContext('2d')!;k.filter=`hue-rotate(${f.hue}deg) saturate(${f.saturation}%) brightness(${f.lightness}%)`;k.drawImage(p.image,p.sx,p.sy,p.sw,p.sh,0,0,canvas.width,canvas.height);k.filter='none';if(f.moss&&moss){const overlay=document.createElement('canvas');overlay.width=canvas.width;overlay.height=canvas.height;const m=overlay.getContext('2d')!;for(let i=0;i<Math.ceil(f.moss/5);i++){const x=((i*.618+d.kind*.013)%1)*canvas.width,y=((i*.371+d.kind*.017)%1)*canvas.height*.85,size=canvas.width*(.2+(i%3)*.08);m.drawImage(moss,x-size/2,y-size*.3,size,size*.7);}m.globalCompositeOperation='destination-in';m.drawImage(canvas,0,0);k.drawImage(overlay,0,0);}finishes.set(key,canvas);return canvas;}
 function drawDecor(d:TankState['decor'][number]){
 if(d.kind===GLASS_KIND){const pos=decorPosition(d,current.current.state),q=projectPoint(pos.x,pos.y,pos.z,w,h),scale=d.size*h*.91/6*q.scale*.28/56;c.save();c.translate(q.x,q.y-Math.hypot(28*Math.sin((d.tilt||0)*Math.PI/180),14.1*Math.cos((d.tilt||0)*Math.PI/180))*scale+1.5);c.rotate((d.tilt||0)*Math.PI/180);c.scale(scale,scale);drawGlass(c,d.glassColor||'#48cbea');addHit({type:'decor',id:d.id},{x:-29,y:-16,w:58,h:32});c.restore();return;}

 if(d.kind===UFO_KIND){if(!current.current.showUFO){keychains.delete(d.id);return;}const pos=decorPosition(d,current.current.state),anchor=current.current.getMenuAnchor()||{x:projectPoint(pos.x,5.7,pos.z,w,h).x,y:0},form=natureForm(d.form),scale=d.size*h/600,length=Math.max(35,Math.min(h*(.10+(d.y-.73)/.25*.18),Math.max(35,h*.48-anchor.y)));
 let chain=keychains.get(d.id);if(!chain){chain=new Chain();keychains.set(d.id,chain);}const nodes=chain.step(anchor.x,anchor.y,length,motionDt),tip=nodes[nodes.length-1],before=nodes[nodes.length-2],angle=Math.atan2(tip.x-before.x,tip.y-before.y);
 c.save();c.strokeStyle='#b6c4d5';c.lineWidth=1.5;c.beginPath();for(let i=1;i<nodes.length;i++){const a=nodes[i-1],b=nodes[i],distance=Math.hypot(b.x-a.x,b.y-a.y),n=Math.max(1,Math.ceil(distance/6));for(let j=0;j<n;j++){const t=j/n,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;c.moveTo(x+1.6,y);c.ellipse(x,y,1.6,3,Math.atan2(a.x-b.x,b.y-a.y),0,Math.PI*2);}}c.stroke();c.translate(tip.x,tip.y);c.rotate(-angle*.5+d.rotation*Math.PI/180);c.translate(0,20*scale*form.height);c.scale(scale*form.width*(d.flip?-1:1),scale*form.height);if(form.hue)c.filter=`hue-rotate(${form.hue}deg)`;drawUFO(c,time);addHit({type:'decor',id:d.id},{x:-48,y:-28,w:96,h:55});c.restore();return;}

 const p=decorPhotos.get(d.kind);if(!p){if(!pendingDecor.has(d.kind)){pendingDecor.add(d.kind);getPhoto('decor',d.kind).then(photo=>{if(alive)decorPhotos.set(d.kind,photo);}).catch(error=>console.warn('Decoration unavailable',error));}return;}const state=current.current.state,f=natureForm(d.form),pos=decorPosition(d,state),point=projectPoint(pos.x,pos.y,pos.z,w,h),spec=DECOR[d.kind],photo=finishedPhoto(d,p);let dh=spec.height*d.size*f.height*h*.91/6*point.scale,dw=dh*p.sw/p.sh*f.width;
  // World-space size stays consistent at every screen density.
  const horizontal=(d.flip?-1:1)*(Math.cos(d.rotation*Math.PI/180)<0?-1:1)*(.62+.38*Math.abs(Math.cos(d.rotation*Math.PI/180))),width=dw*Math.abs(horizontal),ground=point.y,burial=1.5,tilt=(d.tilt||0)*Math.PI/180;
  const motion=plants.get(d.id)?.bend||0,plant=spec.category==='Plants'&&spec.shape!=='moss',sway=plant?Math.sin(time*.8+d.id)*state.current*.00065+motion:0;
  c.save();c.translate(point.x,ground+1);c.scale(Math.max(1,width*.5),Math.max(2,dh*.03));const shadow=c.createRadialGradient(0,0,.05,0,0,1);shadow.addColorStop(0,'rgba(5,16,10,.55)');shadow.addColorStop(1,'rgba(5,16,10,0)');c.fillStyle=shadow;c.beginPath();c.arc(0,0,1,0,Math.PI*2);c.fill();c.restore();
  c.save();c.beginPath();c.moveTo(0,0);c.lineTo(w,0);for(let i=40;i>=0;i--){const x=pos.x+(i/40-.5)*Math.max(4,width/w*20),y=heightAt(state.terrain,x,pos.z),q=projectPoint(x,y,pos.z,w,h);c.lineTo(q.x,q.y+2);}c.closePath();c.clip();let contact=0;{const contactKey=[dw,dh,horizontal,tilt].join('/'),cached=contacts.get(d.id);if(cached?.key===contactKey)contact=cached.value;else{contact=-Infinity;for(let yy=0;yy<p.maskHeight;yy++)for(let xx=0;xx<p.maskWidth;xx++){if(p.mask[(yy*p.maskWidth+xx)*4+3]<30)continue;const lx=((xx+.5)/p.maskWidth-.5)*dw*horizontal,ly=((yy+1)/p.maskHeight-1)*dh;contact=Math.max(contact,Math.sin(tilt)*lx+Math.cos(tilt)*ly);}if(!Number.isFinite(contact))contact=0;contacts.set(d.id,{key:contactKey,value:contact});}}
  c.translate(point.x,ground+burial-contact);c.rotate(tilt);c.scale(horizontal,1);c.transform(1,0,Math.tan(f.lean*Math.PI/180),1,0,0);
  for(let copy=f.density-1;copy>=0;copy--){const offset=(copy-(f.density-1)/2)*dw*.17,scale=1-copy*.055;const strips=plant?12:1;for(let i=0;i<strips;i++){const u=i/strips,tip=1-u,bend=(sway*dh+f.bend/100*dw*.55)*tip*tip;const ripple=plant?Math.sin(time*1.4+u*7+d.id)*state.current*.00009*dh*tip:0;c.drawImage(photo,0,u*photo.height,photo.width,photo.height/strips,offset-dw*scale/2+bend+ripple,-dh*scale+i*dh*scale/strips,dw*scale,dh*scale/strips+.65);}}
  addHit({type:'decor',id:d.id},{x:-dw/2,y:-dh,w:dw,h:dh},p);c.restore();

  if(current.current.editing&&current.current.selected?.type==='decor'&&current.current.selected.id===d.id){const x=point.x-width/2,y=ground-dh;c.save();c.strokeStyle='#daedc8';c.lineWidth=1;c.setLineDash([4,5]);c.strokeRect(x-5,y-5,width+10,dh+6);c.setLineDash([]);const hx=x+width+5,hy=y-5;c.fillStyle='#dcebc8';if(!f.locked){c.fillRect(hx-6,hy-6,12,12);handle={x:hx,y:hy,id:d.id,anchorX:point.x,anchorY:ground,size:d.size};}c.restore();}
 }
 function drawBubbleFeature(b:TankState['bubblers'][number],c:CanvasRenderingContext2D=ctx!,time:number=relaxTime){const z=(b.depth-.5)*5,position=(b.x-.5)*15,floor=heightAt(current.current.state.terrain,position,z),base=projectPoint(position,floor,z,w,h),amount=Math.ceil(b.power*(b.style===1?3.5:b.style===2?2.8:1.2));if(current.current.editing){const width=b.style===1?w*b.width/100*.8:12;addHit({type:'bubbler',id:b.id},{x:base.x-width/2,y:base.y-9,w:width,h:18});}
  c.beginPath();for(let i=0;i<amount;i++){const seed=((i*73.139+b.id*.017)%1+1)%1;let progress=(time*(.09+(i%7)*.006)+i/Math.max(1,amount))%1,phase=progress*Math.PI*4;let x=position+Math.sin(phase+i)*(.025+progress*.08),depth=z;const spread=b.width/100*14;if(b.style===1)x=clamp(position+(((i*.618033)%1)-.5)*spread,-7.4,7.4)+Math.sin(phase+i)*.07;if(b.style===2){x+=Math.sin(i*19)*.3+progress*.18;depth+=Math.cos(i)*.18;}if(b.style===3){x+=Math.cos(phase+i*.15)*(.1+progress*.3);depth+=Math.sin(phase+i*.15)*(.1+progress*.3);}if(b.style===4){progress=(time*.16+Math.floor(i/10)*.27+i%10*.01)%1;x+=Math.sin(i)*.06;}if(b.style===5){x+=Math.cos(i*2.399)*spread*.09;depth+=Math.sin(i*2.399)*spread*.09;}x+=Math.sin(time*.22+progress)*current.current.state.current*.002*progress;const front=b.style===1&&b.depth>=.98,cycle=Math.floor(time*(.09+(i%7)*.006)+i/Math.max(1,amount)),px=((i*.618033+Math.sin(time*.055+i)*.065+cycle*.137)%1+1)%1;const pt=front?{x:px*(w+40)-20,y:h+15-progress*(h+45),scale:1}:projectPoint(x,heightAt(current.current.state.terrain,x,depth)+progress*(6-heightAt(current.current.state.terrain,x,depth)),depth,w,h),r=(1.2+b.size*.042)*(seed*.5+.65)*pt.scale*Math.min(w/1000,1.5)*(b.style===2?.6:1);c.moveTo(pt.x+r,pt.y);c.arc(pt.x,pt.y,r,0,Math.PI*2);c.moveTo(pt.x-r*.05,pt.y-r*.28);c.arc(pt.x-r*.27,pt.y-r*.28,r*.22,0,Math.PI*2);}c.strokeStyle='rgba(218,245,242,.4)';c.lineWidth=.8;c.stroke();
 }
 function render(now:number){if(!alive)return;frame=requestAnimationFrame(render);if(now-lastDraw<renderBudget-1||document.hidden)return;lastDraw=now;const started=performance.now();const rawDt=Math.min((now-last)/1000,.08);last=now;if(document.hidden)return;const p=current.current,s=p.state,dt=s.paused?0:rawDt;motionDt=rawDt;time+=dt;relaxTime+=p.relax?rawDt:dt;lightTime+=(p.relax?rawDt:dt)*s.waveSpeed/35;top.setTransform(dpr,0,0,dpr,0,0);top.clearRect(0,0,w,h);c.setTransform(dpr,0,0,dpr,0,0);c.globalAlpha=1;c.globalCompositeOperation='source-over';c.fillStyle='#09272d';c.fillRect(0,0,w,h);
  const bk=[w,h,s.color,s.brightness].join('/');if(background&&bk!==baseKey){baseKey=bk;baseLayer.width=Math.round(w);baseLayer.height=Math.round(h);const bg=baseLayer.getContext('2d')!;bg.drawImage(background,0,0,w,h);const water=bg.createLinearGradient(0,h*.52,0,h);water.addColorStop(0,'rgba(8,35,37,0)');water.addColorStop(.35,'#15322f');water.addColorStop(1,'#172821');bg.fillStyle=water;bg.fillRect(0,h*.52,w,h*.48);}
  if(background){const drift=p.relax&&s.drift?Math.sin(time*.025)*w*.003:0;c.drawImage(baseLayer,-w*.004+drift,-h*.004,w*1.008,h*1.008);}
  waterLight?.update(lightTime,w,h,s.caustics,s.color,s.angle,s.brightness,s.waveSize,s.waveDepth,s.waveMotion);waterLight?.draw(c,w,h);
  if(painting&&paintPoint&&current.current.brush&&now/1000-paintTime>=.05){const q=terrain?.pick(paintPoint.x/w,paintPoint.y/h,s.terrain);if(q)current.current.onSculpt(q.x,q.z,Math.min(.1,now/1000-paintTime));paintTime=now/1000;}
  terrain?.rebuild(s.terrain,w,h,dpr);
  if(s.decor!==lastDecor||s.terrain!==lastTerrain){lastDecor=s.decor;lastTerrain=s.terrain;obstacles=makeObstacles(s);const active=new Set(s.decor.map(d=>{const f=natureForm(d.form);return [d.kind,f.hue,f.saturation,f.lightness,f.moss].join('/');}));for(const key of finishes.keys())if(!active.has(key))finishes.delete(key);const placed=new Set(s.decor.map(d=>d.id));for(const id of plants.keys())if(!placed.has(id))plants.delete(id);for(const id of keychains.keys())if(!placed.has(id))keychains.delete(id);}const ids=new Set(s.fish.map(f=>f.id));fantail?.retain(ids);betta?.retain(ids);if(!betta&&!bettaLoading&&s.fish.some(f=>f.kind===15)){bettaLoading=true;try{betta=new Betta3D();betta.load().catch(error=>{console.warn('Betta uses photographic fallback:',error);betta?.dispose();betta=null;}).finally(()=>{bettaLoading=false;});}catch(error){console.warn('3D unavailable; using photographic betta:',error);betta=null;bettaLoading=false;}}for(const[id]of fish)if(!ids.has(id))fish.delete(id);for(const f of s.fish){let item=fish.get(f.id);if(!item||item.brain.kind!==f.kind){item={brain:createBrain(f),facing:Math.random()>.5?1:-1,pitch:0};fish.set(f.id,item);}item.brain.size=f.size;}
  const brains=[...fish.values()].map(f=>f.brain);for(const item of fish.values())if(dt)stepFish(item.brain,brains,obstacles,food,dt,s.speed,s.current,Math.random,s.terrain);
  for(let i=food.length-1;i>=0;i--){food[i].age+=dt;food[i].position.y=Math.max(heightAt(s.terrain,food[i].position.x,food[i].position.z)+.05,food[i].position.y-dt*.13);if(food[i].age>35)food.splice(i,1);}
  for(const d of s.decor)if(DECOR[d.kind].category==='Plants'){let spring=plants.get(d.id);if(!spring){spring={bend:0,velocity:0};plants.set(d.id,spring);}const pos=decorPosition(d,s),form=natureForm(d.form),height=DECOR[d.kind].height*d.size*form.height;let force=0;for(const f of brains){const distance=Math.hypot(f.position.x-pos.x,f.position.z-pos.z);if(distance<DECOR[d.kind].width*d.size+.35&&f.position.y>pos.y&&f.position.y<pos.y+height)force+=f.velocity.x*(1-distance/(DECOR[d.kind].width*d.size+.35))*.75;}spring.velocity+=(force-spring.bend*7-spring.velocity*3)*dt;spring.bend=clamp(spring.bend+spring.velocity*dt,-.24,.24);}
  
  hits=[];handle=null;const layers:{z:number;draw:()=>void}[]=[];if(terrain)for(const strip of terrain.strips)layers.push({z:strip.z-.001,draw:()=>terrain!.drawStrip(c,strip)});for(const d of s.decor)if(d.kind!==UFO_KIND)layers.push({z:decorPosition(d).z+Math.min(.3,DECOR[d.kind].width*d.size*.07),draw:()=>drawDecor(d)});for(const f of fish.values())layers.push({z:f.brain.position.z,draw:()=>drawFish(f,dt)});for(const b of s.bubblers)if(!p.relax&&!(b.style===1&&b.depth>=.98))layers.push({z:(b.depth-.5)*5,draw:()=>drawBubbleFeature(b)});for(const f of food)layers.push({z:f.position.z,draw:()=>{const pt=projectPoint(f.position.x,f.position.y,f.position.z,w,h);c.fillStyle='#cba878';c.beginPath();c.ellipse(pt.x,pt.y,2.2*pt.scale,1.5*pt.scale,.4,0,Math.PI*2);c.fill();}});layers.sort((a,b)=>a.z-b.z).forEach(l=>l.draw());drawGrid();
  waterLight?.draw(c,w,h,true);for(const b of s.bubblers)if(!p.relax&&b.style===1&&b.depth>=.98)drawBubbleFeature(b);for(const d of s.decor)if(d.kind===UFO_KIND)drawDecor(d);
  c.save();c.globalCompositeOperation='soft-light';c.globalAlpha=.22;c.fillStyle=s.color;c.fillRect(0,0,w,h);c.restore();c.fillStyle=`rgba(0,10,16,${Math.max(0,(75-s.brightness)/100*.75)})`;c.fillRect(0,0,w,h);
  if(p.relax){
   // A DOM foreground canvas crosses every UI layer without intercepting clicks.
   const emitters=s.bubblers.filter(b=>b.power>0),flow=emitters.reduce((n,b)=>n+b.power,0),size=emitters.length?emitters.reduce((n,b)=>n+b.size,0)/emitters.length:25;
   drawBubbleFeature({id:7919,x:.5,depth:1,power:clamp(flow,28,70),size,style:1,width:100},top,relaxTime);
   const wash=top.createLinearGradient(0,0,w,h),phase=relaxTime*.075;
   wash.addColorStop(0,`rgba(2,21,28,${.025+.018*Math.sin(phase)})`);
   wash.addColorStop(.5,`rgba(142,213,228,${.012+.01*Math.sin(phase+2)})`);
   wash.addColorStop(1,`rgba(2,21,28,${.025+.018*Math.sin(phase+4)})`);
   top.fillStyle=wash;top.fillRect(0,0,w,h);
  }
  frameCost=frameCost*.96+(performance.now()-started)*.04;renderBudget=frameCost>23?1000/30:frameCost<12?1000/60:renderBudget;
  for(let i=0;i<48;i++){const px=((i*.618+time*.0012)%1)*w,py=(((i*.371-time*.002)%1+1)%1)*h;c.fillStyle='rgba(219,239,221,.16)';c.fillRect(px,py,1.2,1.2);}
 }
 function drawGrid(){if(!current.current.brush?.grid||!current.current.editing)return;c.save();c.strokeStyle='rgba(180,240,255,.28)';c.lineWidth=.6;for(let row=0;row<ROWS;row+=4){c.beginPath();for(let col=0;col<COLS;col++){const q=gridPoint(col,row),p=projectPoint(q.x,heightAt(current.current.state.terrain,q.x,q.z)+.006,q.z,w,h);col?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y);}c.stroke();}for(let col=0;col<COLS;col+=4){c.beginPath();for(let row=0;row<ROWS;row++){const q=gridPoint(col,row),p=projectPoint(q.x,heightAt(current.current.state.terrain,q.x,q.z)+.006,q.z,w,h);row?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y);}c.stroke();}c.restore();}
 function coordinates(e:PointerEvent){const r=el.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
 function down(e:PointerEvent){dragPoint=null;const p=current.current,point=coordinates(e);if(p.editing&&p.brush){const q=terrain?.pick(point.x/w,point.y/h,p.state.terrain);if(q){painting=true;paintPoint=point;paintTime=performance.now()/1000;p.onDragStart();p.onSculpt(q.x,q.z,.05);el.setPointerCapture(e.pointerId);}return;}if(p.editing&&handle&&Math.hypot(point.x-handle.x,point.y-handle.y)<18){drag={kind:'resize',id:handle.id,size:handle.size,rotation:p.state.decor.find(d=>d.id===handle!.id)?.rotation||0,startX:point.x-handle.anchorX,distance:Math.max(1,Math.hypot(point.x-handle.anchorX,point.y-handle.anchorY)),anchorX:handle.anchorX,anchorY:handle.anchorY};p.onDragStart();el.setPointerCapture(e.pointerId);return;}
  if(p.feeding&&!p.relax){if(food.length<40){for(let i=0;i<6;i++)food.push({id:++foodId,position:new V(clamp((point.x/w-.5)*16/.89+(Math.random()-.5)*.3,-7,7),5.5,(Math.random()-.5)*.4),age:0});}return;}
  let chosen:Hit|undefined;for(const item of [...hits].reverse()){const local=item.inverse.transformPoint(new DOMPoint(point.x*dpr,point.y*dpr)),r=item.rect,u=(local.x-r.x)/r.w,v=(local.y-r.y)/r.h;if(u<0||u>1||v<0||v>1)continue;if(item.photo){const photo=item.photo,x=Math.min(photo.maskWidth-1,Math.floor(u*photo.maskWidth)),y=Math.min(photo.maskHeight-1,Math.floor(v*photo.maskHeight));if(photo.mask[(y*photo.maskWidth+x)*4+3]<30)continue;}chosen=item;break;}
  if(chosen?.selection.type==='decor'&&current.current.state.decor.find(d=>d.id===chosen!.selection.id)?.kind===UFO_KIND)keychains.get(chosen.selection.id)?.kick();
  if(chosen?.selection.type==='fish'){const item=fish.get(chosen.selection.id);if(item)startleFish(item.brain,item.brain.position.clone().add(new V((Math.random()-.5)*.3,0,.3)));}
  if(p.relax||!p.editing)return;p.onSelect(chosen?.selection??null);if(chosen?.selection.type==='decor'){const d=p.state.decor.find(d=>d.id===chosen!.selection.id)!;if(d.kind===UFO_KIND){drag={kind:'move',id:d.id,dx:point.x/w-d.x,dy:point.y/h-(.10+(d.y-.73)/.25*.18),floating:true};p.onDragStart();el.setPointerCapture(e.pointerId);return;}if(natureForm(d.form).locked)return;const pos=decorPosition(d,p.state),anchor=projectPoint(pos.x,pos.y,pos.z,w,h);drag={kind:'move',id:d.id,dx:(point.x-anchor.x)/w,dy:(point.y-anchor.y)/h};p.onDragStart();el.setPointerCapture(e.pointerId);}
 }
 function move(e:PointerEvent){const point=coordinates(e);dragPoint=point;if(painting){paintPoint=point;return;}if(!drag){el.style.cursor=current.current.feeding?'crosshair':handle&&Math.hypot(point.x-handle.x,point.y-handle.y)<18?'nesw-resize':'';return;}if(drag.kind==='resize'){const distance=Math.hypot(point.x-drag.anchorX,point.y-drag.anchorY);const turn=Math.acos(clamp((point.x-drag.anchorX)/Math.max(1,Math.abs(drag.startX)),-1,1))*180/Math.PI;current.current.onRotate(drag.id,((drag.rotation+turn+540)%360)-180);current.current.onResize(drag.id,clamp(drag.size*distance/drag.distance,.2,6));return;}if(drag.floating){current.current.onMove(drag.id,clamp(point.x/w-drag.dx,.03,.97),clamp(.73+(point.y/h-drag.dy-.10)/.18*.25,.73,.98));return;}const q=terrain?.pick(point.x/w-drag.dx,point.y/h-drag.dy,current.current.state.terrain);const pos=q?{x:clamp(q.x/15+.5,-.5,1.5),y:clamp(.73+(q.z/5.1+.5)*.25,.73,.98)}:unprojectGround(point.x/w-drag.dx,point.y/h-drag.dy);current.current.onMove(drag.id,pos.x,pos.y);}
 function up(){if(painting){painting=false;paintPoint=null;current.current.onDragEnd();}if(drag){if(drag.kind==='move'&&dragPoint){const moving=current.current.state.decor.find(d=>d.id===drag!.id);if(moving&&DECOR[moving.kind].category==='Stone'){for(const hit of [...hits].reverse()){if(hit.selection.type!=='decor'||hit.selection.id===moving.id)continue;const target=current.current.state.decor.find(d=>d.id===hit.selection.id);if(!target||DECOR[target.kind].category!=='Stone')continue;const local=hit.inverse.transformPoint(new DOMPoint(dragPoint.x*dpr,dragPoint.y*dpr)),r=hit.rect;if(local.x>=r.x&&local.x<=r.x+r.w&&local.y>=r.y&&local.y<=r.y+r.h){current.current.onStack(moving.id,target.id);break;}}}}drag=null;dragPoint=null;current.current.onDragEnd();}}
 el.addEventListener('pointerdown',down);el.addEventListener('pointermove',move);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);el.addEventListener('lostpointercapture',up);frame=requestAnimationFrame(render);
 return()=>{fantail?.dispose();betta?.dispose();alive=false;cancelAnimationFrame(frame);observer.disconnect();el.removeEventListener('pointerdown',down);el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up);el.removeEventListener('lostpointercapture',up);};
 },[]);
 return <><canvas ref={canvas} className={'tank-canvas'+(props.feeding?' feeding':'')} aria-label="Photographic aquarium. Click an ornament to edit it or drag its corner handle across to turn and resize. Click a fish to startle it."/><canvas ref={foreground} aria-hidden="true" className="relax-foreground" style={{display:props.relax?'block':'none'}}/></>;
}
