import {COLS,ROWS,gridPoint,heightAt,type Terrain} from './terrain';
import {projectPoint} from './perspective';
import {SUBSTRATES} from './state';
type P={x:number;y:number};
// Cached depth strips let foreground banks occlude fish and roots naturally.
export class TerrainRenderer{
 strips:{z:number;canvas:HTMLCanvasElement;y:number}[]=[];private last:Terrain|null=null;private width=0;private height=0;private scale=1;private variants:HTMLCanvasElement[]=[];private patterns=new WeakMap<CanvasRenderingContext2D,Map<CanvasImageSource,CanvasPattern>>();
 constructor(private sand:HTMLImageElement,private soil:HTMLImageElement,private atlas?:HTMLImageElement){}
 rebuild(t:Terrain,w:number,h:number,dpr:number){if(this.last===t&&this.width===w&&this.height===h&&this.scale===dpr)return;const previous=this.last,full=!previous||this.width!==w||this.height!==h||this.scale!==dpr||previous.floorColor!==t.floorColor||previous.tint!==t.tint||previous.grain!==t.grain;this.last=t;this.width=w;this.height=h;this.scale=dpr;
 if(previous?.floorColor!==t.floorColor)this.variants=[];const textures=[this.sand,this.soil];const variants=this.variants;for(const i of new Set(t.materials)){if(variants[i])continue;const s=SUBSTRATES[i];const canvas=document.createElement('canvas');canvas.width=canvas.height=1024;const c=canvas.getContext('2d')!;const image=textures[s.grain>.03?1:0];if(this.atlas){const family=[6,20,21].includes(i)?3:[5,24,25].includes(i)?2:s.grain>.03?1:0;const sw=this.atlas.width/2,sh=this.atlas.height/2;for(let yy=0;yy<2;yy++)for(let xx=0;xx<2;xx++){c.save();c.translate(xx*512+(xx?512:0),yy*512+(yy?512:0));c.scale(xx?-1:1,yy?-1:1);c.drawImage(this.atlas,(family%2)*sw,Math.floor(family/2)*sh,sw,sh,0,0,512,512);c.restore();}}else c.drawImage(image,0,0,1024,1024);if(t.floorColor){c.globalCompositeOperation='color';c.fillStyle=t.floorColor;c.fillRect(0,0,1024,1024);c.globalCompositeOperation='multiply';c.globalAlpha=.45;c.fillRect(0,0,1024,1024);}else if(i!==0&&i!==6){c.globalCompositeOperation='color';c.globalAlpha=.65;c.fillStyle=s.color;c.fillRect(0,0,1024,1024);c.globalCompositeOperation='multiply';c.globalAlpha=.25;c.fillRect(0,0,1024,1024);}variants[i]=canvas;}
 const old=this.strips;this.strips=[];for(let row=0;row<ROWS-1;row++){if(!full&&old[row]&&previous){let changed=false;for(let i=row*COLS;i<(row+2)*COLS;i++)if(previous.heights[i]!==t.heights[i]||previous.materials[i]!==t.materials[i]){changed=true;break;}if(!changed){this.strips.push(old[row]);continue;}}const points:P[][]=[[],[]];let min=Infinity,max=-Infinity;for(let j=0;j<2;j++)for(let col=0;col<COLS;col++){const world=gridPoint(col,row+j),p=projectPoint(world.x,t.heights[(row+j)*COLS+col],world.z,w,h);if(col===0)p.x=-2;if(col===COLS-1)p.x=w+2;points[j].push(p);min=Math.min(min,p.y);max=Math.max(max,p.y);}const y=Math.floor(min)-2,bottom=row===ROWS-2?h:Math.ceil(max)+3,canvas=old[row]?.canvas||document.createElement('canvas');canvas.width=Math.round(w*dpr);canvas.height=Math.max(1,Math.ceil((bottom-y)*dpr));const c=canvas.getContext('2d')!;c.setTransform(dpr,0,0,dpr,0,-y*dpr);
 for(let col=0;col<COLS-1;col++){const a=points[0][col],b=points[0][col+1],d=points[1][col],e=points[1][col+1],index=row*COLS+col,material=t.materials[index];const source=variants[material],du=150*t.grain,dv=95*t.grain,u=col*du,v=row*dv,edge=(col===0||col===COLS-2)?Math.max(1,(b.x-a.x)/(w*.89/(COLS-1))):1,u0=col===0?du-du*edge:u,u1=col===COLS-2?u+du*edge:u+du;this.triangle(c,source,[a,b,d],[[u0,v],[u1,v],[u0,v+dv]]);this.triangle(c,source,[b,e,d],[[u1,v],[u1,v+dv],[u0,v+dv]]);
 c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.lineTo(e.x,e.y);c.lineTo(d.x,d.y);c.closePath();if(t.tint!=='#ffffff'){c.globalCompositeOperation='multiply';c.globalAlpha=.35;c.fillStyle=t.tint;c.fill();c.globalCompositeOperation='source-over';c.globalAlpha=1;}
}
 if(row===ROWS-2){c.save();c.beginPath();points[1].forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.lineTo(points[1][COLS-1].x,h+2);c.lineTo(points[1][0].x,h+2);c.closePath();c.clip();const source=variants[t.materials[row*COLS+Math.floor(COLS/2)]],pattern=c.createPattern(source,'repeat');if(pattern){c.save();const grain=.22/Math.max(.4,t.grain);c.scale(grain,grain);c.fillStyle=pattern;c.fillRect(-w/grain,0,w*3/grain,(h+2)/grain);c.restore();}const depth=c.createLinearGradient(0,min,0,h);depth.addColorStop(0,'rgba(8,20,16,.12)');depth.addColorStop(1,'rgba(3,12,10,.72)');c.fillStyle=depth;c.fillRect(0,min,w,h-min+2);if(t.tint!=='#ffffff'){c.globalCompositeOperation='multiply';c.globalAlpha=.35;c.fillStyle=t.tint;c.fillRect(0,min,w,h-min+2);}c.restore();}

 this.strips.push({z:gridPoint(0,row+1).z,canvas,y});}
 }
 private triangle(c:CanvasRenderingContext2D,image:CanvasImageSource,p:P[],uv:number[][]){const [a,b,d]=p,[s,t,u]=uv,den=(t[0]-s[0])*(u[1]-s[1])-(u[0]-s[0])*(t[1]-s[1]);if(Math.abs(den)<.001)return;const A=((b.x-a.x)*(u[1]-s[1])-(d.x-a.x)*(t[1]-s[1]))/den,B=((b.y-a.y)*(u[1]-s[1])-(d.y-a.y)*(t[1]-s[1]))/den,C=((d.x-a.x)*(t[0]-s[0])-(b.x-a.x)*(u[0]-s[0]))/den,D=((d.y-a.y)*(t[0]-s[0])-(b.y-a.y)*(u[0]-s[0]))/den;c.save();c.beginPath();const cx=(a.x+b.x+d.x)/3,cy=(a.y+b.y+d.y)/3;for(let i=0;i<3;i++){const dx=p[i].x-cx,dy=p[i].y-cy,len=Math.hypot(dx,dy)||1;const x=p[i].x+dx/len*.65,y=p[i].y+dy/len*.65;i?c.lineTo(x,y):c.moveTo(x,y);}c.closePath();c.clip();c.transform(A,B,C,D,a.x-A*s[0]-C*s[1],a.y-B*s[0]-D*s[1]);const sx=Math.min(...uv.map(v=>v[0])),sy=Math.min(...uv.map(v=>v[1])),sw=Math.max(...uv.map(v=>v[0]))-sx,sh=Math.max(...uv.map(v=>v[1]))-sy;let cache=this.patterns.get(c);if(!cache){cache=new Map();this.patterns.set(c,cache);}let pattern=cache.get(image);if(!pattern){pattern=c.createPattern(image,'repeat')||undefined;if(pattern)cache.set(image,pattern);}if(pattern){c.fillStyle=pattern;c.fillRect(sx-24,sy-24,sw+48,sh+48);}c.restore();}
 drawStrip(c:CanvasRenderingContext2D,strip:typeof this.strips[number]){c.drawImage(strip.canvas,0,strip.y,this.width,strip.canvas.height/this.scale);}
 pick(nx:number,ny:number,t:Terrain){let best:{x:number;z:number;height:number}|null=null;let error=Infinity;for(let i=0;i<=400;i++){const z=-2.6+i/400*5.2,scale=projectPoint(0,0,z,1,1).scale,x=(nx-.5)*16/scale,h=heightAt(t,x,z),p=projectPoint(x,h,z,1,1),distance=Math.abs(p.y-ny);if(distance<error){error=distance;best={x,z,height:h};}}return error<.055?best:null;}
}
