(() => {
  const S=window.OpsStore,D=window.OpsDomain;
  const labels={opsApps:'Apps',opsProjects:'Clients & projects',opsContact:'Project contact & team',opsNotes:'Walkthrough notes',opsField:'Field plan',opsUpload:'Photo upload',opsPhotos:'Photo library',opsPublish:'Website publishing',opsEstimate:'Estimate author',opsReview:'Estimate review'};
  const roots=new Set();let selected=localStorage.getItem('tagims-ops-project'),busy=false;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const project=()=>S.data.projects.find(p=>p.id===selected);
  const rows=t=>S.data[t].filter(r=>r.project_id===selected);
  const estimate=()=>rows('estimates').sort((a,b)=>b.version-a.version)[0];
  const button=(label,action,id='')=>`<button type="button" data-action="${action}" data-id="${esc(id)}">${label}</button>`;
  const input=(name,label,value='',type='text',required=false)=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`;
  const area=(name,label,value='')=>`<label>${label}<textarea name="${name}" rows="4">${esc(value)}</textarea></label>`;
  const options=(values,current)=>values.map(([v,l])=>`<option value="${v}" ${v===current?'selected':''}>${esc(l)}</option>`).join('');
  function status(message,error=false){const el=document.getElementById('ops-status');if(el){el.textContent=message;el.dataset.error=error;} }
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
  function dialog(title,fields,submit,label='Save'){
    const el=document.createElement('dialog');el.className='ops-dialog';el.innerHTML=`<form><h2>${esc(title)}</h2>${fields}<p class="ops-form-error" role="alert"></p><footer><button type="button" data-cancel>Cancel</button><button type="submit">${esc(label)}</button></footer></form>`;
    document.body.append(el);el.querySelector('[data-cancel]').onclick=()=>el.close();el.onclose=()=>el.remove();
    el.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=el.querySelector('[type=submit]');b.disabled=true;try{await submit(Object.fromEntries(new FormData(e.target)));el.close();refresh();}catch(err){el.querySelector('[role=alert]').textContent=err.message;}finally{b.disabled=false;}};
    el.showModal();return el;
  }
  function account(){dialog('Shared workspace',`<p>Sign in with your existing Supabase staff account. The local demo stays on this browser and does not upload records.</p>${input('email','Email','','email',true)}${input('password','Password','','password',true)}${button('Use local demo','demo')}${S.mode==='demo'?button('Import PHR photo backup','importPrototype'):''}${S.mode!=='signed-out'?button('Sign out','signout'):''}`,async f=>{await S.signIn(f.email,f.password);status('Signed in. Shared records loaded.');},'Sign in');}
  function choose(id){selected=id;localStorage.setItem('tagims-ops-project',id);refresh();}
  function refresh(){
    if(!project()&&S.data.projects.length)selected=S.data.projects[0].id;
    const b=document.getElementById('ops-account');if(b)b.textContent=S.mode==='cloud'?'Account':S.mode==='demo'?'Local demo':'Sign in';
    for(const el of roots){if(!el.isConnected){roots.delete(el);el._urls?.forEach(URL.revokeObjectURL);continue;}render(el);}
  }
  function newProject(){dialog('Create project',`<label>Existing client<select name="client_id"><option value="">Create a new client</option>${S.data.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label>${input('client','New client name')}${input('name','Project name','','text',true)}${input('address','Property address')}${input('phone','Client phone','','tel')}${input('email','Client email','','email')}`,async f=>{let clientId=f.client_id;if(!clientId)clientId=(await S.save('clients',{name:D.required(f.client,'Client name'),phone:f.phone,email:f.email})).id;const p=await S.save('projects',{client_id:clientId,name:f.name,address:f.address,status:'walkthrough'});choose(p.id);});}
  function newNote(){dialog('Walkthrough note',area('notes','Scope, observations, measurements, and decisions'),f=>S.save('walkthroughs',{project_id:selected,notes:D.required(f.notes,'Note')}));}
  function fieldForm(existing){const x=existing||{};dialog(x.id?'Edit field item':'Add field item',`<label>Type<select name="kind">${options(['material','punch','tool','supply','timeline','document'].map(x=>[x,x[0].toUpperCase()+x.slice(1)]),x.kind)}</select></label>${input('title','Item',x.title,'text',true)}${area('details','Details or HTTPS document link',x.details)}${input('due_date','Due date',x.due_date,'date')}`,f=>{if(f.kind==='document')f.details=D.safeLink(f.details);return S.save('field_items',{...x,...f,project_id:selected,due_date:f.due_date||null,status:x.status||'open'});});}
  function newEstimate(){dialog('Create estimate draft',area('notes','Shared scope and qualifications'),async f=>{await S.save('estimates',{project_id:selected,version:(estimate()?.version||0)+1,status:'draft',notes:f.notes,scope_confirmed:false});});}
  function estimateItem(existing){const e=estimate(),x=existing||{};if(!e||e.status!=='draft')throw new Error('Return this estimate to a new draft revision before changing it.');dialog(x.id?'Edit scope item':'Add scope item',`${input('description','Scope item',x.description,'text',true)}${input('quantity','Quantity (blank = TBD)',x.quantity??'')}${input('unit','Unit',x.unit||'job')}${input('unit_price','Unit price (blank = TBD)',x.unit_price??'')}`,f=>{if(f.quantity!=='')D.money(f.quantity);if(f.unit_price!=='')D.money(f.unit_price);return S.save('estimate_items',{...x,...f,estimate_id:e.id,quantity:f.quantity===''?null:Number(f.quantity),unit_price:f.unit_price===''?null:Number(f.unit_price)});});}
  function review(action){const e=estimate();const names={submit:'Submit for Inspector',inspector:'Complete Inspector review',reviewer:'Complete final Reviewer pass',revise:'Create revision'};dialog(names[action],action==='revise'?'<p>Create a new draft version. The reviewed version remains unchanged.</p>':`<p>This records your manual review; it does not run an AI review or send anything to the client.</p><label class="ops-check"><input name="confirmed" type="checkbox" required> ${action==='inspector'?'I inspected both copies, reconciled the scope and totals, and applied only Alex-approved corrections.':action==='reviewer'?'I inspected the final client copy, checked for private information and unresolved issues, and applied approved corrections.':'Proposed scope, quantities, client details, and assumptions are confirmed for inspection.'}</label>`,()=>S.review(e.id,action),names[action]);}
  function photoEdit(p){dialog('Photo details',`${input('caption','Caption',p.caption)}${input('room','Room / work area',p.room)}<label>Stage<select name="stage">${options(['unsorted','before','during','after'].map(s=>[s,s[0].toUpperCase()+s.slice(1)]),p.stage)}</select></label>`,f=>S.save('photos',{...p,...f}));}
  async function exportGallery(){const photos=rows('photos').filter(p=>p.website_public);if(!photos.length)throw new Error('Approve at least one photo first.');dialog('Export approved website gallery',`${input('title','Public project title (no client name)','','text',true)}${input('city','Public city (no street address)','','text',true)}<p>Exports only approved photos as resized JPEGs with source metadata removed. This creates a website-ready file; it does not publish to PColaHome.com.</p>`,async f=>{let figures='';for(const p of photos){const url=await S.image(p);try{const img=new Image();img.crossOrigin='anonymous';img.src=url;await img.decode();const scale=Math.min(1,1600/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);figures+=`<figure><img alt="${esc(p.caption||p.stage)}" src="${canvas.toDataURL('image/jpeg',0.85)}"><figcaption>${esc(p.caption||p.stage)}</figcaption></figure>`;}finally{if(url.startsWith('blob:'))URL.revokeObjectURL(url);}}download(new Blob([`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(f.title)}</title><style>body{font:16px system-ui;margin:40px auto;padding:20px;max-width:1000px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}figure{margin:0}img{width:100%;border-radius:12px}</style><h1>${esc(f.title)}</h1><p>${esc(f.city)}</p><main>${figures}</main></html>`],{type:'text/html'}),'approved-project-gallery.html');status('Website gallery exported. Publishing and revoking exported copies are manual.');},'Export gallery');}
  async function contactRender(el,p,generation){try{const c=await S.contact(p);if(el._generation!==generation)return;const target=el.querySelector('.ops-contact');target.innerHTML=c?`<h3>${esc(c.name)}</h3><p>${esc(p.address||'Address pending')}</p><p>${esc(c.phone||'Phone pending')}<br>${esc(c.email||'Email pending')}</p>${c.phone?`<a href="tel:${esc(c.phone.replace(/[^+\d]/g,''))}">Call client</a>`:''} ${c.email?`<a href="mailto:${esc(c.email)}">Email client</a>`:''}`:'Contact not available.';}catch(e){if(el._generation===generation)el.querySelector('.ops-contact').textContent=e.message;}}
  function render(el){
    const type=el.dataset.opsType,p=project(),gen=(el._generation||0)+1;el._generation=gen;el._urls?.forEach(URL.revokeObjectURL);el._urls=[];
    const head=`<div class="ops-heading"><h2>${labels[type]}</h2><span>${esc(p?.name||'Choose a project')}</span></div>`+(p&&['opsProjects','opsContact'].includes(type)?`<p><strong>Next action:</strong> ${esc(p.next_action||'Schedule walkthrough')}${p.next_action_due?' · '+esc(p.next_action_due):''}</p>`:'');
    if(type==='opsApps'){el.innerHTML=`<div class="ops-heading"><h2>Your apps</h2><span>One Hub. Shared projects.</span></div><div class="ops-app-grid">${[['photo-center','Photo Center','Capture, organize, and approve project photos.'],['estimates','Estimates','Walkthrough → Author → Inspector → Reviewer.'],['crm','CRM','Clients, contacts, and the employee field plan.']].map(([path,title,copy])=>`<a href="/apps/${path}/"><h3>${title}</h3><p>${copy}</p><span>Open workspace →</span></a>`).join('')}</div><p class="ops-muted">Each app remembers its own Hub layout. Project records are shared.</p>${button('Sign in / local demo','account')}`;return;}
    if(S.mode==='signed-out'){el.innerHTML=head+'<p>Sign in to load your shared projects, or try the local demo.</p>'+button('Open workspace','account');return;}
    if(type==='opsProjects'){el.innerHTML=head+`<div class="ops-toolbar">${button('New project','newProject')}${button('Refresh','reload')}${S.mode==='demo'?button('Export local backup','backup'):''}</div><label>Project<select data-project><option value="">Choose a project</option>${S.data.projects.map(x=>`<option value="${x.id}" ${selected===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><div class="ops-records">${S.data.projects.map(x=>`<button class="ops-project ${x.id===selected?'selected':''}" data-action="selectProject" data-id="${x.id}"><strong>${esc(x.name)}</strong><span>${esc(x.address||'Address pending')}</span><small>${esc(x.status)}</small></button>`).join('')||'<p>No projects yet. Create your first project.</p>'}</div>`;return;}
    if(!p){el.innerHTML=head+'<p>Create or select a project in Clients & projects.</p>';return;}
    if(type==='opsContact'){el.innerHTML=head+'<div class="ops-contact">Loading contact…</div><hr>'+button('Edit project / contact','contact')+button('Assign employee access','team')+'<p class="ops-muted">Staff see only assigned projects. Owner controls team access and website approval.</p>';contactRender(el,p,gen);return;}
    if(type==='opsNotes'){el.innerHTML=head+button('Add walkthrough note','newNote')+`<div class="ops-records">${rows('walkthroughs').sort((a,b)=>String(b.occurred_at||b.created_at).localeCompare(String(a.occurred_at||a.created_at))).map(n=>`<article><time>${esc(new Date(n.occurred_at||n.created_at).toLocaleString())}</time><p class="ops-pre">${esc(n.notes)}</p></article>`).join('')||'<p>No notes yet. Record scope, measurements, selections, and unresolved questions here.</p>'}</div>`;return;}
    if(type==='opsField'){el.innerHTML=head+button('Add field item','field')+['material','punch','tool','supply','timeline','document'].map(kind=>`<h3>${{material:'Materials',punch:'Punch list',tool:'Tools',supply:'Supplies',timeline:'Timeline',document:'Documents'}[kind]}</h3>${rows('field_items').filter(x=>x.kind===kind).map(x=>`<article class="ops-field-row"><label class="ops-check"><input type="checkbox" data-complete="${x.id}" ${x.status==='done'?'checked':''}><span>${esc(x.title)}</span></label><p>${esc(x.details)}</p>${x.due_date?`<small>Due ${esc(x.due_date)}</small>`:''}${kind==='document'&&/^https:\/\//.test(x.details||'')?` <a href="${esc(x.details)}" target="_blank" rel="noopener noreferrer">Open document</a>`:''}${button('Edit','editField',x.id)}</article>`).join('')||'<p class="ops-muted">No items added.</p>'}`).join('');return;}
    if(type==='opsUpload'){el.innerHTML=head+`<p>Add photos to <strong>${esc(p.name)}</strong>.</p><label>Choose photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple data-upload></label><label>Take a photo<input type="file" accept="image/*" capture="environment" data-upload></label><p class="ops-muted">JPEG, PNG, WebP · up to 20 MB each. HEIC requires conversion. Originals remain private.</p><p class="ops-upload-state" role="status"></p>`;return;}
    if(type==='opsPhotos'||type==='opsPublish'){
      const photos=rows('photos').filter(x=>type!=='opsPublish'||x.website_public);
      el.innerHTML=head+(type==='opsPublish'?'<p>Approved photos are ready for a website export. Exported files are separate copies; revocation here does not remove copies already published elsewhere.</p>'+button('Export website gallery','exportGallery'):'<p>Stage labels and website approval are independent. Internal photos never enter the gallery export.</p>')+`<div class="ops-photo-grid">${photos.map(x=>`<article><img data-photo="${x.id}" alt="${esc(x.caption||x.name||'Project photo')}" loading="lazy"><strong>${esc(x.name||'Project photo')}</strong><small>${esc(x.stage)} · ${x.website_public?'Website approved':'Internal only'}</small><p>${esc(x.caption)}</p>${button('Edit details','editPhoto',x.id)}${button(x.website_public?'Revoke approval':'Approve for website','approvePhoto',x.id)}</article>`).join('')||'<p>No photos in this view.</p>'}</div>`;
      photos.forEach(async photo=>{try{const url=await S.image(photo);if(gen!==el._generation||!el.isConnected){if(url.startsWith('blob:'))URL.revokeObjectURL(url);return;}if(url.startsWith('blob:'))el._urls.push(url);el.querySelector(`[data-photo="${photo.id}"]`).src=url;}catch(e){if(gen===el._generation){const img=el.querySelector(`[data-photo="${photo.id}"]`);if(img)img.alt='Image unavailable: '+e.message;}}});return;
    }
    const e=estimate();
    if(!e){el.innerHTML=head+'<p>No estimate draft yet.</p>'+button('Create estimate','newEstimate');return;}
    const items=S.data.estimate_items.filter(x=>x.estimate_id===e.id);let total;try{total=D.display(D.total(items));}catch{total='TBD — unresolved quantities / prices';}
    if(type==='opsEstimate'){el.innerHTML=head+`<p><strong>Version ${e.version}</strong> · ${esc(e.status.replaceAll('_',' '))}</p><p class="ops-pre">${esc(e.notes)}</p><table><thead><tr><th>Scope</th><th>Qty</th><th>Unit price</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.description)}</td><td>${esc(x.quantity??'TBD')} ${esc(x.unit)}</td><td>${x.unit_price===null?'TBD':esc(D.display(D.money(x.unit_price)))}</td><td>${e.status==='draft'?button('Edit','editItem',x.id):''}</td></tr>`).join('')}</tbody></table><p><strong>Scope subtotal: ${total}</strong></p><p class="ops-muted">Draft scope pricing only. Payment schedule, agreement, and contractor/client PDF production remain separate review deliverables.</p>${e.status==='draft'?button('Add scope item','item')+button('Edit scope / confirmation','scope'):''}`;return;}
    if(type==='opsReview'){el.innerHTML=head+`<p><strong>Version ${e.version} · ${esc(e.status.replaceAll('_',' '))}</strong></p><ol><li>Author prepares contractor and matching client drafts.</li><li>Inspector checks both copies. Alex approves exact corrections.</li><li>Reviewer inspects the final client copy and approved corrections.</li></ol><p>Scope confirmed: <strong>${e.scope_confirmed?'Yes':'No'}</strong><br>Scope subtotal: <strong>${esc(total)}</strong></p>${e.status==='draft'?button('Submit for Inspector','submit'):e.status==='internal_review'?button('Record Inspector clearance','inspector'):e.status==='final_review'?button('Record final Reviewer clearance','reviewer'):button('Create new revision','revise')}<p class="ops-muted">These are manual workflow records. No AI review, client sending, or signature request runs automatically.</p>`;}
  }
  const actions={account,newProject,newNote,field:()=>fieldForm(),newEstimate,item:()=>estimateItem(),exportGallery,
    importPrototype:()=>{document.querySelector('.ops-dialog')?.close();dialog('Import Photo Management backup','<p>Import the original prototype backup into the local demo. Existing IDs are preserved. Public approval must be reviewed again. Duplicate IDs cancel the entire import without replacing your work.</p><label>PHR backup<input type="file" name="backup" accept=".json" required></label>',async f=>{const count=await OpsImportPrototype(f.backup);status(`Imported ${count.projects} projects and ${count.photos} photos locally.`);},'Import');},
    async demo(){await S.demo();document.querySelector('.ops-dialog')?.close();status('Local demo · saved in this browser only. Export backups before clearing browser data.');},
    async signout(){await S.signOut();document.querySelector('.ops-dialog')?.close();status('Signed out.');},reload:()=>S.reload(),selectProject:choose,
    editField:id=>fieldForm(S.data.field_items.find(x=>x.id===id)),editItem:id=>estimateItem(S.data.estimate_items.find(x=>x.id===id)),editPhoto:id=>photoEdit(S.data.photos.find(x=>x.id===id)),
    approvePhoto:id=>{const p=S.data.photos.find(x=>x.id===id);dialog(p.website_public?'Revoke website approval':'Approve for website','<p>Confirm this photo has permission for public use and contains no private information.</p>',()=>S.publication(p,!p.website_public),'Confirm');},
    scope:()=>{const e=estimate();dialog('Scope and assumptions',area('notes','Shared scope, exclusions, and qualifications',e.notes)+`<label class="ops-check"><input name="confirmed" type="checkbox" ${e.scope_confirmed?'checked':''}> Alex has confirmed the proposed scope and material assumptions.</label>`,f=>S.save('estimates',{...e,notes:f.notes,scope_confirmed:f.confirmed==='on'}));},
    contact:()=>{const p=project(),c=S.data.clients.find(x=>x.id===p.client_id);if(!c)throw new Error('Only the project owner can edit client records.');dialog('Project and client details',input('name','Project name',p.name,'text',true)+input('address','Property address',p.address)+input('client_name','Client name',c.name,'text',true)+input('phone','Phone',c.phone,'tel')+input('email','Email',c.email,'email')+`<label>Stage<select name="status">${options(['lead','walkthrough','estimating','review','active','complete','archived'].map(x=>[x,x]),p.status)}</select></label>`+input('next_action','Next action',p.next_action||'Schedule walkthrough','text',true)+input('next_action_due','Next action due',p.next_action_due,'date'),async f=>{await S.save('clients',{...c,name:f.client_name,phone:f.phone,email:f.email});await S.save('projects',{...p,name:f.name,address:f.address,status:f.status,next_action:f.next_action,next_action_due:f.next_action_due||null});});},
    team:()=>dialog('Assign registered employee',input('email','Employee account email','','email',true)+`<label>Access<select name="role">${options([['field','Field — notes, photos, work plan'],['viewer','Viewer — read assigned project'],['estimator','Estimator — estimates and field records'],['manager','Manager — field records and estimates']])}</select></label><p>The employee must already have a registered account. Assignment does not send an invitation.</p>`,f=>S.members(selected,f.email,f.role)),
    backup:async()=>download(new Blob([JSON.stringify(await S.exportBackup())],{type:'application/json'}),'tagims-local-backup.json'),
    submit:()=>review('submit'),inspector:()=>review('inspector'),reviewer:()=>review('reviewer'),revise:()=>review('revise')
  };
  document.addEventListener('click',async ev=>{const b=ev.target.closest('[data-action]');if(!b||!b.closest('.ops-root,.ops-dialog'))return;try{await actions[b.dataset.action]?.(b.dataset.id);}catch(e){status(e.message,true);}});
  document.addEventListener('change',async ev=>{const t=ev.target;try{if(t.matches('[data-project]'))choose(t.value);if(t.matches('[data-complete]')){const x=S.data.field_items.find(x=>x.id===t.dataset.complete);await S.save('field_items',{...x,status:t.checked?'done':'open'});}if(t.matches('[data-upload]')){if(busy)throw new Error('Wait for the current upload to finish.');busy=true;const id=selected;let saved=0;const failures=[];for(const file of t.files){status(`Saving ${file.name}…`);try{await S.upload(id,file);saved++;}catch(e){failures.push(file.name+': '+e.message);}}status(`${saved} photo(s) saved ${S.mode==='cloud'?'to shared storage':'on this browser'}.${failures.length?' Failed: '+failures.join('; '):''}`,failures.length>0);if(!failures.length)t.value='';busy=false;}}catch(e){busy=false;status(e.message,true);refresh();}});
  const renderers=Object.fromEntries(Object.keys(labels).map(type=>[type,()=>{const el=document.createElement('div');el.className='ops-root hub-data-widget';el.dataset.opsType=type;roots.add(el);render(el);return el;}]));
  window.OpsWidgets={labels,renderers,account,start(){S.on(refresh);S.restore().then(()=>status(S.mode==='cloud'?'Shared workspace connected.':S.mode==='demo'?'Local demo · saved in this browser only.':'Sign in for shared records, or choose the local demo.')).catch(e=>status(e.message,true));}};
})();
